'use client';

import { useState, useEffect } from 'react';
import { evaluateSpecGate } from '@/lib/spec-gate';

const DRAFT_STORAGE_KEY = 'cvf_business_strategy_wizard_draft';

interface WizardField {
    id: string;
    type: 'text' | 'textarea' | 'select';
    label: string;
    placeholder?: string;
    required: boolean;
    options?: string[];
    rows?: number;
    tip?: string;
}

interface WizardStep {
    id: number;
    name: string;
    icon: string;
    description: string;
    required: boolean;
    fields: WizardField[];
    isReview?: boolean;
}

interface WizardData {
    [key: string]: string;
}

interface BusinessStrategyWizardProps {
    onBack: () => void;
}

const WIZARD_STEPS: WizardStep[] = [
    {
        id: 1,
        name: 'Context & Goals',
        icon: '🎯',
        description: 'Xác định bối cảnh và mục tiêu chiến lược',
        required: true,
        fields: [
            { id: 'strategicQuestion', type: 'textarea', label: 'Câu hỏi chiến lược', placeholder: 'VD: Có nên mở rộng thị trường miền Trung?', required: true, rows: 2, tip: '💡 Một câu hỏi cụ thể cần quyết định' },
            { id: 'businessContext', type: 'textarea', label: 'Business Context', placeholder: 'Mô tả về công ty, ngành, thị trường hiện tại...', required: true, rows: 3, tip: '💡 Background cần thiết để phân tích' },
            { id: 'strategicGoals', type: 'textarea', label: 'Strategic Goals', placeholder: 'VD:\n- Tăng revenue 30% trong 2 năm\n- Đa dạng hóa nguồn thu', required: true, rows: 3 },
            { id: 'constraints', type: 'textarea', label: 'Constraints', placeholder: 'VD:\n- Budget: $500K\n- Timeline: 18 months\n- No new hires', required: false, rows: 2 },
            { id: 'stakeholders', type: 'text', label: 'Key Stakeholders', placeholder: 'VD: CEO, CFO, Sales Director, Board', required: false },
        ]
    },
    {
        id: 2,
        name: 'Options Analysis',
        icon: '📊',
        description: 'Phân tích các phương án',
        required: true,
        fields: [
            { id: 'options', type: 'textarea', label: 'Strategic Options (3-5)', placeholder: 'Option A: ...\nOption B: ...\nOption C: ...\nOption D (Status quo): ...', required: true, rows: 5, tip: '💡 Liệt kê tất cả options khả thi, bao gồm "không làm gì"' },
            { id: 'criteria', type: 'textarea', label: 'Evaluation Criteria', placeholder: 'VD:\n- ROI potential\n- Risk level\n- Time to implement\n- Resource requirements', required: true, rows: 3, tip: '💡 Tiêu chí để so sánh options' },
            { id: 'priorities', type: 'textarea', label: 'Criteria Weights', placeholder: 'VD:\n- ROI: 40%\n- Risk: 25%\n- Time: 20%\n- Resources: 15%', required: false, rows: 3 },
        ]
    },
    {
        id: 3,
        name: 'SWOT & Risk',
        icon: '⚖️',
        description: 'Phân tích SWOT và rủi ro',
        required: true,
        fields: [
            { id: 'strengths', type: 'textarea', label: 'Strengths', placeholder: 'VD:\n- Strong brand recognition\n- Experienced team\n- Healthy cash flow', required: true, rows: 3, tip: '💡 Điểm mạnh nội bộ có thể tận dụng' },
            { id: 'weaknesses', type: 'textarea', label: 'Weaknesses', placeholder: 'VD:\n- Limited regional presence\n- Outdated tech stack', required: true, rows: 3, tip: '💡 Điểm yếu nội bộ cần khắc phục' },
            { id: 'opportunities', type: 'textarea', label: 'Opportunities', placeholder: 'VD:\n- Growing market demand\n- Competitor exit\n- New regulations favoring our model', required: true, rows: 3, tip: '💡 Cơ hội bên ngoài có thể nắm bắt' },
            { id: 'threats', type: 'textarea', label: 'Threats', placeholder: 'VD:\n- New entrants\n- Economic downturn\n- Supply chain disruption', required: true, rows: 3, tip: '💡 Mối đe dọa bên ngoài cần đề phòng' },
            { id: 'risks', type: 'textarea', label: 'Key Risks per Option', placeholder: 'Option A risks:\n- ...\nOption B risks:\n- ...', required: false, rows: 4 },
        ]
    },
    {
        id: 4,
        name: 'Review',
        icon: '✅',
        description: 'Xem lại và xuất Strategy Doc',
        required: true,
        isReview: true,
        fields: []
    }
];

function generateConsolidatedSpec(data: WizardData): string {
    const spec = `
# 📈 STRATEGIC DECISION DOCUMENT

> Generated by CVF Business Strategy Wizard
> Strategic Question: ${data.strategicQuestion || 'N/A'}

---

## 1️⃣ CONTEXT & GOALS

### Strategic Question
> ${data.strategicQuestion || 'N/A'}

### Business Context
${data.businessContext || 'N/A'}

### Strategic Goals
${data.strategicGoals || 'N/A'}

### Constraints
${data.constraints || 'No specific constraints defined'}

### Key Stakeholders
${data.stakeholders || 'N/A'}

---

## 2️⃣ OPTIONS ANALYSIS

### Strategic Options
${data.options || 'N/A'}

### Evaluation Criteria
${data.criteria || 'N/A'}

### Criteria Weights
${data.priorities || 'Equal weighting'}

---

## 3️⃣ SWOT ANALYSIS

### Strengths
${data.strengths || 'N/A'}

### Weaknesses
${data.weaknesses || 'N/A'}

### Opportunities
${data.opportunities || 'N/A'}

### Threats
${data.threats || 'N/A'}

### Risk Assessment
${data.risks || 'To be analyzed'}

---

## 📋 SUMMARY FOR AI

**STRATEGIC QUESTION:**
${data.strategicQuestion || 'N/A'}

**CONTEXT:**
${data.businessContext?.substring(0, 200) || 'N/A'}...

**OPTIONS TO EVALUATE:**
${data.options || 'N/A'}

**EVALUATION CRITERIA:**
${data.criteria || 'N/A'}

---

## 🎯 EXPECTED OUTPUTS

Based on this document, AI should generate:
1. **Options Comparison Matrix** - Score each option against criteria
2. **SWOT-Strategy Matrix** - SO, WO, ST, WT strategies
3. **Risk Assessment Table** - Likelihood × Impact for each risk
4. **Recommendation** - Preferred option with rationale
5. **Implementation Roadmap** - High-level milestones
6. **Key Success Metrics** - How to measure success

**REMEMBER:** 
- Be decisive - make a clear recommendation
- Support with data/logic, not just opinions
- Consider second-order effects
- Identify mitigation strategies for risks
`;

    return spec.trim();
}

export function BusinessStrategyWizard({ onBack }: BusinessStrategyWizardProps) {
    const [currentStep, setCurrentStep] = useState(1);
    const [wizardData, setWizardData] = useState<WizardData>({});
    const [showExport, setShowExport] = useState(false);
    const [hasDraft, setHasDraft] = useState(false);

    // Load draft from localStorage on mount
    useEffect(() => {
        const savedDraft = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (savedDraft) {
            try {
                const parsed = JSON.parse(savedDraft);
                if (parsed.data && Object.keys(parsed.data).length > 0) {
                    setHasDraft(true);
                }
            } catch (e) {
                // Invalid draft, ignore
            }
        }
    }, []);

    // Save draft to localStorage whenever data changes
    useEffect(() => {
        if (Object.keys(wizardData).length > 0) {
            localStorage.setItem(DRAFT_STORAGE_KEY, JSON.stringify({
                data: wizardData,
                step: currentStep,
                savedAt: new Date().toISOString()
            }));
        }
    }, [wizardData, currentStep]);

    // Load saved draft
    const loadDraft = () => {
        const savedDraft = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (savedDraft) {
            try {
                const parsed = JSON.parse(savedDraft);
                setWizardData(parsed.data || {});
                setCurrentStep(parsed.step || 1);
                setHasDraft(false);
            } catch (e) {
                // Invalid draft
            }
        }
    };

    // Clear draft
    const clearDraft = () => {
        localStorage.removeItem(DRAFT_STORAGE_KEY);
        setWizardData({});
        setCurrentStep(1);
        setHasDraft(false);
    };

    const currentStepConfig = WIZARD_STEPS.find(s => s.id === currentStep)!;

    // Check if can jump to a specific step
    const canJumpToStep = (targetStep: number): boolean => {
        if (targetStep <= currentStep) return true;
        for (let i = 1; i < targetStep; i++) {
            const step = WIZARD_STEPS.find(s => s.id === i);
            if (!step || !step.required) continue;
            const requiredFields = step.fields.filter(f => f.required);
            const allFilled = requiredFields.every(f => wizardData[f.id]?.trim());
            if (!allFilled) return false;
        }
        return true;
    };

    // Handle step click
    const handleStepClick = (stepId: number) => {
        if (canJumpToStep(stepId)) {
            setCurrentStep(stepId);
        }
    };

    // Handle field change
    const handleFieldChange = (fieldId: string, value: string) => {
        setWizardData(prev => ({ ...prev, [fieldId]: value }));
    };

    // Validate current step
    const isStepValid = () => {
        if (!currentStepConfig.required) return true;
        const requiredFields = currentStepConfig.fields.filter(f => f.required);
        return requiredFields.every(f => wizardData[f.id]?.trim());
    };

    // Calculate progress
    const progress = Math.round((currentStep / WIZARD_STEPS.length) * 100);

    // Handle export
    const handleExport = () => {
        setShowExport(true);
    };

    // Generate spec for review
    const generatedSpec = generateConsolidatedSpec(wizardData);
    const specGate = evaluateSpecGate(WIZARD_STEPS.flatMap(step => step.fields), wizardData);
    const canExport = specGate.status === 'PASS';
    const specGateLabel = specGate.status === 'PASS'
        ? 'Spec Gate: PASS — Đủ input để xuất'
        : specGate.status === 'CLARIFY'
            ? 'Spec Gate: CLARIFY — Thiếu input bắt buộc'
            : 'Spec Gate: FAIL — Không đủ dữ liệu để tạo spec';
    const specGateClass = specGate.status === 'PASS'
        ? 'bg-emerald-50 border-emerald-200 text-emerald-700'
        : specGate.status === 'CLARIFY'
            ? 'bg-amber-50 border-amber-200 text-amber-700'
            : 'bg-rose-50 border-rose-200 text-rose-700';

    if (showExport) {
        return (
            <div className="max-w-4xl mx-auto">
                <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-lg border border-gray-200 dark:border-gray-700">
                    <div className="flex items-center justify-between mb-6">
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                            📈 Strategy Document
                        </h2>
                        <button
                            onClick={() => setShowExport(false)}
                            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
                        >
                            ✕
                        </button>
                    </div>

                    <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-4 max-h-[60vh] overflow-y-auto mb-4">
                        <pre className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap font-mono">
                            {generatedSpec}
                        </pre>
                    </div>

                    <div className={`mb-4 p-3 rounded-lg border text-sm ${specGateClass}`}>
                        <div className="font-semibold">{specGateLabel}</div>
                        {specGate.missing.length > 0 && (
                            <div className="text-xs mt-1">
                                Thiếu input bắt buộc: {specGate.missing.map(field => field.label).join(', ')}
                            </div>
                        )}
                    </div>

                    <div className="flex gap-3">
                        <button
                            onClick={() => {
                                navigator.clipboard.writeText(generatedSpec);
                                alert('Đã copy Strategy Document vào clipboard!');
                            }}
                            disabled={!canExport}
                            className={`flex-1 py-3 rounded-lg font-medium transition-all ${canExport
                                    ? 'bg-gradient-to-r from-blue-600 to-indigo-600 text-white hover:from-blue-700 hover:to-indigo-700'
                                    : 'bg-gray-200 text-gray-400 cursor-not-allowed'
                                }`}
                        >
                            📋 Copy to Clipboard
                        </button>
                        <button
                            onClick={() => {
                                const blob = new Blob([generatedSpec], { type: 'text/markdown' });
                                const url = URL.createObjectURL(blob);
                                const a = document.createElement('a');
                                a.href = url;
                                a.download = `strategy-doc.md`;
                                a.click();
                            }}
                            disabled={!canExport}
                            className={`flex-1 py-3 rounded-lg font-medium transition-all ${canExport
                                    ? 'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600'
                                    : 'bg-gray-100 text-gray-400 cursor-not-allowed'
                                }`}
                        >
                            💾 Download .md
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex items-center gap-4 mb-6">
                <button
                    onClick={onBack}
                    className="p-2 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors text-gray-600 dark:text-gray-400"
                    title="Quay lại trang chủ"
                >
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                    </svg>
                </button>
                <div>
                    <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
                        📈 Business Strategy Wizard
                    </h1>
                    <p className="text-gray-600 dark:text-gray-400">
                        Tạo Strategic Decision Document qua 4 bước
                    </p>
                </div>
            </div>

            {/* Draft Banner */}
            {hasDraft && (
                <div className="mb-6 p-4 bg-amber-50 dark:bg-amber-900/30 border border-amber-200 dark:border-amber-800 rounded-lg flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <span className="text-2xl">📝</span>
                        <div>
                            <p className="font-medium text-amber-800 dark:text-amber-200">Bạn có bản nháp chưa hoàn thành</p>
                            <p className="text-sm text-amber-600 dark:text-amber-400">Tiếp tục từ lần trước hoặc bắt đầu mới</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <button
                            onClick={loadDraft}
                            className="px-4 py-2 bg-amber-500 text-white rounded-lg hover:bg-amber-600 transition-colors font-medium"
                        >
                            Tiếp tục
                        </button>
                        <button
                            onClick={clearDraft}
                            className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
                        >
                            Bắt đầu mới
                        </button>
                    </div>
                </div>
            )}

            {/* Progress Bar */}
            <div className="mb-8">
                <div className="flex justify-between text-sm text-gray-600 dark:text-gray-400 mb-2">
                    <span>Step {currentStep} / 4: {currentStepConfig.name}</span>
                    <span>{progress}%</span>
                </div>
                <div className="h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                    <div
                        className="h-full bg-gradient-to-r from-blue-600 to-indigo-600 transition-all duration-300"
                        style={{ width: `${progress}%` }}
                    />
                </div>
            </div>

            {/* Step Indicators - Clickable */}
            <div className="flex justify-between mb-8 overflow-x-auto pb-2">
                {WIZARD_STEPS.map(step => {
                    const isActive = step.id === currentStep;
                    const isCompleted = step.id < currentStep;
                    const canJump = canJumpToStep(step.id);

                    return (
                        <button
                            key={step.id}
                            onClick={() => handleStepClick(step.id)}
                            disabled={!canJump}
                            title={canJump ? `Nhấn để đến ${step.name}` : 'Hoàn thành các step trước để mở khóa'}
                            className={`flex flex-col items-center min-w-[80px] transition-all ${canJump ? 'cursor-pointer hover:scale-105' : 'cursor-not-allowed opacity-50'}`}
                        >
                            <div
                                className={`w-10 h-10 rounded-full flex items-center justify-center text-lg transition-all ${isActive
                                    ? 'bg-blue-600 text-white ring-4 ring-blue-200 dark:ring-blue-800'
                                    : isCompleted
                                        ? 'bg-green-500 text-white hover:bg-green-600'
                                        : canJump
                                            ? 'bg-gray-200 dark:bg-gray-700 text-gray-500 hover:bg-gray-300 dark:hover:bg-gray-600'
                                            : 'bg-gray-200 dark:bg-gray-700 text-gray-400'
                                    }`}
                            >
                                {isCompleted ? '✓' : step.icon}
                            </div>
                            <span className={`text-xs mt-1 text-center ${isActive ? 'font-bold text-blue-600' : 'text-gray-500'}`}>
                                {step.name}
                            </span>
                        </button>
                    );
                })}
            </div>

            {/* Current Step Content */}
            <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-lg border border-gray-200 dark:border-gray-700">
                <div className="flex items-center gap-3 mb-4">
                    <span className="text-3xl">{currentStepConfig.icon}</span>
                    <div>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                            Step {currentStep}: {currentStepConfig.name}
                        </h2>
                        <p className="text-sm text-gray-600 dark:text-gray-400">
                            {currentStepConfig.description}
                        </p>
                    </div>
                </div>

                {/* Review Step */}
                {currentStepConfig.isReview ? (
                    <div className="space-y-4">
                        <div className="p-4 bg-green-50 dark:bg-green-900/30 rounded-lg border border-green-200 dark:border-green-800">
                            <h3 className="font-bold text-green-800 dark:text-green-200 mb-2">🎉 Strategy Document sẵn sàng!</h3>
                            <p className="text-green-700 dark:text-green-300 text-sm">
                                Review document bên dưới và xuất khi sẵn sàng.
                            </p>
                        </div>

                        <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-4 max-h-96 overflow-y-auto">
                            <pre className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap font-mono">
                                {generatedSpec}
                            </pre>
                        </div>

                        <div className={`p-3 rounded-lg border text-sm ${specGateClass}`}>
                            <div className="font-semibold">{specGateLabel}</div>
                            {specGate.missing.length > 0 && (
                                <div className="text-xs mt-1">
                                    Thiếu input bắt buộc: {specGate.missing.map(field => field.label).join(', ')}
                                </div>
                            )}
                        </div>

                        <button
                            onClick={handleExport}
                            disabled={!canExport}
                            className={`w-full py-3 rounded-lg font-medium transition-all ${canExport
                                    ? 'bg-gradient-to-r from-blue-600 to-indigo-600 text-white hover:from-blue-700 hover:to-indigo-700'
                                    : 'bg-gray-200 text-gray-400 cursor-not-allowed'
                                }`}
                        >
                            📈 Xuất Strategy Document
                        </button>
                    </div>
                ) : (
                    /* Form Fields */
                    <div className="space-y-4">
                        {currentStepConfig.fields.map(field => (
                            <div key={field.id}>
                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                                    {field.label}
                                    {field.required && <span className="text-red-500 ml-1">*</span>}
                                </label>

                                {field.type === 'text' && (
                                    <input
                                        type="text"
                                        value={wizardData[field.id] || ''}
                                        onChange={e => handleFieldChange(field.id, e.target.value)}
                                        placeholder={field.placeholder}
                                        className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                    />
                                )}

                                {field.type === 'textarea' && (
                                    <textarea
                                        value={wizardData[field.id] || ''}
                                        onChange={e => handleFieldChange(field.id, e.target.value)}
                                        placeholder={field.placeholder}
                                        rows={field.rows || 3}
                                        className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                                    />
                                )}

                                {field.type === 'select' && field.options && (
                                    <select
                                        value={wizardData[field.id] || ''}
                                        onChange={e => handleFieldChange(field.id, e.target.value)}
                                        className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                    >
                                        <option value="">-- Chọn --</option>
                                        {field.options.map(opt => (
                                            <option key={opt} value={opt}>{opt}</option>
                                        ))}
                                    </select>
                                )}

                                {/* Field Tip */}
                                {field.tip && (
                                    <p className="mt-1 text-xs text-gray-500 dark:text-gray-400 italic">
                                        {field.tip}
                                    </p>
                                )}
                            </div>
                        ))}
                    </div>
                )}
            </div>

            {/* Navigation Buttons */}
            <div className="flex justify-between mt-6">
                <button
                    onClick={() => setCurrentStep(currentStep - 1)}
                    disabled={currentStep === 1}
                    className={`flex items-center gap-2 px-6 py-3 rounded-lg font-medium transition-all ${currentStep === 1
                        ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                        : 'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600'
                        }`}
                >
                    ← Trước
                </button>

                {currentStep < WIZARD_STEPS.length ? (
                    <button
                        onClick={() => setCurrentStep(currentStep + 1)}
                        disabled={currentStepConfig.required && !isStepValid()}
                        className={`flex items-center gap-2 px-6 py-3 rounded-lg font-medium transition-all ${currentStepConfig.required && !isStepValid()
                            ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                            : 'bg-blue-600 text-white hover:bg-blue-700'
                            }`}
                    >
                        Tiếp tục →
                    </button>
                ) : null}
            </div>
        </div>
    );
}
