'use client';

import { useState, useCallback } from 'react';
import ReactMarkdown from 'react-markdown';
import { Execution, QualityScore } from '@/types';
import { useLanguage } from '@/lib/i18n';

interface ResultViewerProps {
    execution: Execution;
    output: string;
    onAccept: () => void;
    onReject: () => void;
    onRetry: () => void;
    onBack: () => void;
    onSendToAgent?: (content: string) => void;
}

function QualityBadge({ score }: { score: number }) {
    let color = 'bg-gray-100 text-gray-700';
    let label = 'Pending';

    if (score >= 8) {
        color = 'bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300';
        label = '⭐ Excellent';
    } else if (score >= 6) {
        color = 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300';
        label = '✅ Good';
    } else if (score >= 4) {
        color = 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900 dark:text-yellow-300';
        label = '⚠️ Acceptable';
    } else {
        color = 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300';
        label = '❌ Poor';
    }

    return (
        <span className={`px-3 py-1 rounded-full text-sm font-medium ${color}`}>
            {label} ({score.toFixed(1)}/10)
        </span>
    );
}

function QualityBreakdown({ score }: { score: QualityScore }) {
    const metrics = [
        { name: 'Structure', value: score.structure },
        { name: 'Completeness', value: score.completeness },
        { name: 'Clarity', value: score.clarity },
        { name: 'Actionability', value: score.actionability },
    ];

    return (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {metrics.map((m) => (
                <div key={m.name} className="text-center">
                    <div className="text-2xl font-bold text-gray-900 dark:text-white">
                        {m.value.toFixed(1)}
                    </div>
                    <div className="text-sm text-gray-500">{m.name}</div>
                </div>
            ))}
        </div>
    );
}

type ExportLanguage = 'en' | 'vi';

const exportLabels = {
    en: {
        title: 'CVF Analysis Result',
        generated: 'Generated',
        template: 'Template',
        qualityScore: 'Quality Score',
        footer: 'Generated by CVF v1.5 UX Platform',
        copyBtn: '📋 Copy to Clipboard',
        downloadBtn: '💾 Download .md',
        downloadPdf: '📕 Download PDF',
        downloadDocx: '📘 Download Word',
        copied: '✅ Copied!',
        langLabel: 'Language',
        helpTitle: '💡 Export Result',
        helpDesc: 'Export completed analysis for storage or sharing',
        exporting: '⏳ Exporting...',
    },
    vi: {
        title: 'Kết Quả Phân Tích CVF',
        generated: 'Ngày tạo',
        template: 'Template',
        qualityScore: 'Điểm chất lượng',
        footer: 'Được tạo bởi CVF v1.5 UX Platform',
        copyBtn: '📋 Sao chép',
        downloadBtn: '💾 Tải xuống .md',
        downloadPdf: '📕 Tải PDF',
        downloadDocx: '📘 Tải Word',
        copied: '✅ Đã sao chép!',
        langLabel: 'Ngôn ngữ',
        helpTitle: '💡 Xuất Kết Quả',
        helpDesc: 'Xuất kết quả phân tích để lưu trữ hoặc chia sẻ',
        exporting: '⏳ Đang xuất...',
    },
};

export function ResultViewer({ execution, output, onAccept, onReject, onRetry, onBack, onSendToAgent }: ResultViewerProps) {
    const { language } = useLanguage();
    const [showDetails, setShowDetails] = useState(false);
    const [showExportMenu, setShowExportMenu] = useState(false);
    const [copied, setCopied] = useState(false);
    const [exportLang, setExportLang] = useState<ExportLanguage>(language as ExportLanguage);
    const [exporting, setExporting] = useState<string | null>(null);

    const labels = exportLabels[exportLang];

    // Generate export content - remove any existing footer from output to prevent duplication
    const generateExportContent = () => {
        const date = new Date().toISOString().split('T')[0];
        // Clean output - remove any existing CVF footer to prevent duplication
        const cleanOutput = output.replace(/\n---\n\*Generated by CVF.*\*/g, '').trim();

        return `---
# ${labels.title}
**${labels.generated}:** ${date}
**${labels.template}:** ${execution.templateName}
---

${cleanOutput}

---
*${labels.footer}*
`;
    };

    const handleCopyToClipboard = async () => {
        try {
            await navigator.clipboard.writeText(generateExportContent());
            setCopied(true);
            setTimeout(() => {
                setCopied(false);
            }, 1500);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    const handleExportToFile = () => {
        const content = generateExportContent();
        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `cvf-result-${execution.templateId}-${Date.now()}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        setShowExportMenu(false);
    };

    // Real PDF export using jsPDF
    const handleExportPdf = useCallback(async () => {
        setExporting('pdf');
        try {
            const { jsPDF } = await import('jspdf');
            const doc = new jsPDF({ unit: 'mm', format: 'a4' });
            const pageWidth = doc.internal.pageSize.getWidth();
            const margin = 15;
            const maxWidth = pageWidth - margin * 2;
            let y = 20;

            const addText = (text: string, fontSize: number, isBold = false) => {
                doc.setFontSize(fontSize);
                doc.setFont('helvetica', isBold ? 'bold' : 'normal');
                const lines = doc.splitTextToSize(text, maxWidth);
                for (const line of lines) {
                    if (y + fontSize * 0.5 > doc.internal.pageSize.getHeight() - 15) {
                        doc.addPage();
                        y = 20;
                    }
                    doc.text(line, margin, y);
                    y += fontSize * 0.45;
                }
            };

            // Title
            addText(labels.title, 18, true);
            y += 3;
            addText(`${labels.template}: ${execution.templateName}`, 11);
            addText(`${labels.generated}: ${new Date().toISOString().split('T')[0]}`, 11);
            y += 5;

            // Draw separator line
            doc.setDrawColor(200);
            doc.line(margin, y, pageWidth - margin, y);
            y += 8;

            // Parse markdown content into sections
            const rawContent = output.replace(/\n---\n\*Generated by CVF.*\*/g, '').trim();
            const contentLines = rawContent.split('\n');

            for (const line of contentLines) {
                const trimmed = line.trim();
                if (!trimmed) { y += 3; continue; }

                if (trimmed.startsWith('### ')) {
                    y += 2;
                    addText(trimmed.replace(/^###\s*/, ''), 12, true);
                    y += 1;
                } else if (trimmed.startsWith('## ')) {
                    y += 4;
                    addText(trimmed.replace(/^##\s*/, ''), 14, true);
                    y += 2;
                } else if (trimmed.startsWith('# ')) {
                    y += 4;
                    addText(trimmed.replace(/^#\s*/, ''), 16, true);
                    y += 2;
                } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
                    addText(`  \u2022 ${trimmed.replace(/^[-*]\s*/, '').replace(/\*\*/g, '')}`, 10);
                } else if (/^\d+\.\s/.test(trimmed)) {
                    addText(`  ${trimmed.replace(/\*\*/g, '')}`, 10);
                } else if (trimmed.startsWith('|')) {
                    // Table row: render as simple text
                    if (!trimmed.match(/^[|\s-]+$/)) {
                        const cells = trimmed.split('|').filter(c => c.trim()).map(c => c.trim());
                        addText(`  ${cells.join('  |  ')}`, 9);
                    }
                } else if (trimmed.startsWith('- [')) {
                    // Checklist items
                    const checked = trimmed.includes('[x]') || trimmed.includes('[X]');
                    const text = trimmed.replace(/^-\s*\[.?\]\s*/, '');
                    addText(`  ${checked ? '\u2611' : '\u2610'} ${text}`, 10);
                } else {
                    addText(trimmed.replace(/\*\*/g, ''), 10);
                }
            }

            // Footer
            y += 8;
            doc.setDrawColor(200);
            doc.line(margin, y, pageWidth - margin, y);
            y += 5;
            doc.setFontSize(8);
            doc.setFont('helvetica', 'italic');
            doc.text(labels.footer, margin, y);

            doc.save(`cvf-result-${execution.templateId}-${Date.now()}.pdf`);
        } catch (err) {
            console.error('PDF export failed:', err);
        } finally {
            setExporting(null);
            setShowExportMenu(false);
        }
    }, [output, execution, labels]);

    // Real Word (.docx) export using docx library
    const handleExportDocx = useCallback(async () => {
        setExporting('docx');
        try {
            const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } = await import('docx');
            const { saveAs } = await import('file-saver');

            const rawContent = output.replace(/\n---\n\*Generated by CVF.*\*/g, '').trim();
            const contentLines = rawContent.split('\n');
            const children: InstanceType<typeof Paragraph>[] = [];

            // Title
            children.push(new Paragraph({
                children: [new TextRun({ text: labels.title, bold: true, size: 36, color: '1a56db' })],
                heading: HeadingLevel.TITLE,
                spacing: { after: 200 },
            }));

            // Metadata
            children.push(new Paragraph({
                children: [
                    new TextRun({ text: `${labels.template}: `, bold: true, size: 22 }),
                    new TextRun({ text: execution.templateName, size: 22 }),
                ],
                spacing: { after: 50 },
            }));
            children.push(new Paragraph({
                children: [
                    new TextRun({ text: `${labels.generated}: `, bold: true, size: 22 }),
                    new TextRun({ text: new Date().toISOString().split('T')[0], size: 22 }),
                ],
                spacing: { after: 200 },
            }));

            // Separator
            children.push(new Paragraph({
                border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'cccccc' } },
                spacing: { after: 300 },
            }));

            // Parse content
            for (const line of contentLines) {
                const trimmed = line.trim();
                if (!trimmed) {
                    children.push(new Paragraph({ spacing: { after: 100 } }));
                    continue;
                }

                if (trimmed.startsWith('### ')) {
                    children.push(new Paragraph({
                        children: [new TextRun({ text: trimmed.replace(/^###\s*/, ''), bold: true, size: 24 })],
                        heading: HeadingLevel.HEADING_3,
                        spacing: { before: 200, after: 100 },
                    }));
                } else if (trimmed.startsWith('## ')) {
                    children.push(new Paragraph({
                        children: [new TextRun({ text: trimmed.replace(/^##\s*/, ''), bold: true, size: 28, color: '1a56db' })],
                        heading: HeadingLevel.HEADING_2,
                        spacing: { before: 300, after: 150 },
                    }));
                } else if (trimmed.startsWith('# ')) {
                    children.push(new Paragraph({
                        children: [new TextRun({ text: trimmed.replace(/^#\s*/, ''), bold: true, size: 32 })],
                        heading: HeadingLevel.HEADING_1,
                        spacing: { before: 300, after: 200 },
                    }));
                } else if (trimmed.startsWith('- [')) {
                    const checked = trimmed.includes('[x]') || trimmed.includes('[X]');
                    const text = trimmed.replace(/^-\s*\[.?\]\s*/, '');
                    children.push(new Paragraph({
                        children: [new TextRun({ text: `${checked ? '\u2611' : '\u2610'} ${text}`, size: 20 })],
                        indent: { left: 400 },
                    }));
                } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
                    const text = trimmed.replace(/^[-*]\s*/, '').replace(/\*\*/g, '');
                    // Handle bold markers within text
                    const parts = trimmed.replace(/^[-*]\s*/, '').split(/\*\*/);
                    const runs = parts.map((part, i) => new TextRun({ text: part, bold: i % 2 === 1, size: 20 }));
                    children.push(new Paragraph({
                        children: [new TextRun({ text: '\u2022 ', size: 20 }), ...runs],
                        indent: { left: 400 },
                        spacing: { after: 50 },
                    }));
                } else if (/^\d+\.\s/.test(trimmed)) {
                    const parts = trimmed.split(/\*\*/);
                    const runs = parts.map((part, i) => new TextRun({ text: part, bold: i % 2 === 1, size: 20 }));
                    children.push(new Paragraph({
                        children: runs,
                        indent: { left: 400 },
                        spacing: { after: 50 },
                    }));
                } else if (trimmed.startsWith('|') && !trimmed.match(/^[|\s-]+$/)) {
                    const cells = trimmed.split('|').filter(c => c.trim()).map(c => c.trim());
                    children.push(new Paragraph({
                        children: cells.map((cell, i) => new TextRun({
                            text: (i > 0 ? '  |  ' : '') + cell,
                            bold: i === 0,
                            size: 18,
                            font: 'Courier New',
                        })),
                        indent: { left: 200 },
                        spacing: { after: 30 },
                    }));
                } else {
                    const parts = trimmed.split(/\*\*/);
                    const runs = parts.map((part, i) => new TextRun({ text: part, bold: i % 2 === 1, size: 20 }));
                    children.push(new Paragraph({ children: runs, spacing: { after: 80 } }));
                }
            }

            // Footer
            children.push(new Paragraph({
                border: { top: { style: BorderStyle.SINGLE, size: 1, color: 'cccccc' } },
                spacing: { before: 400 },
            }));
            children.push(new Paragraph({
                children: [new TextRun({ text: labels.footer, italics: true, size: 16, color: '888888' })],
                alignment: AlignmentType.CENTER,
            }));

            const docFile = new Document({
                sections: [{ children }],
                creator: 'CVF v1.6 Agent Platform',
                title: `${execution.templateName} - CVF Result`,
            });

            const blob = await Packer.toBlob(docFile);
            saveAs(blob, `cvf-result-${execution.templateId}-${Date.now()}.docx`);
        } catch (err) {
            console.error('Word export failed:', err);
        } finally {
            setExporting(null);
            setShowExportMenu(false);
        }
    }, [output, execution, labels]);

    return (
        <div className="max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
                <div className="flex items-center gap-4">
                    <button
                        onClick={onBack}
                        className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                        aria-label={language === 'vi' ? 'Quay lại' : 'Go back'}
                    >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                        </svg>
                    </button>
                    <div>
                        <h1 className="text-2xl font-bold flex items-center gap-2">
                            <span className="text-green-500">✅</span>
                            <span>{execution.templateName} Complete</span>
                        </h1>
                    </div>
                </div>

                <div className="flex flex-wrap items-center gap-3">
                    {/* Export Dropdown */}
                    <div className="relative">
                        <button
                            onClick={() => setShowExportMenu(!showExportMenu)}
                            className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                        >
                            📄 Export
                        </button>

                        {showExportMenu && (
                            <div className="absolute right-0 mt-2 w-64 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 z-10">
                                {/* Help text */}
                                <div className="px-4 py-3 border-b border-gray-200 dark:border-gray-700">
                                    <div className="text-sm font-medium text-gray-900 dark:text-white">{labels.helpTitle}</div>
                                    <div className="text-xs text-gray-500 dark:text-gray-400 mt-1">{labels.helpDesc}</div>
                                </div>

                                {/* Language selector */}
                                <div className="px-4 py-2 border-b border-gray-200 dark:border-gray-700">
                                    <div className="text-xs text-gray-500 mb-1">{labels.langLabel}:</div>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={() => setExportLang('vi')}
                                            className={`px-3 py-1 text-xs rounded ${exportLang === 'vi'
                                                ? 'bg-blue-600 text-white'
                                                : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300'
                                                }`}
                                        >
                                            🇻🇳 Tiếng Việt
                                        </button>
                                        <button
                                            onClick={() => setExportLang('en')}
                                            className={`px-3 py-1 text-xs rounded ${exportLang === 'en'
                                                ? 'bg-blue-600 text-white'
                                                : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300'
                                                }`}
                                        >
                                            🇺🇸 English
                                        </button>
                                    </div>
                                </div>

                                {/* Action buttons */}
                                <button
                                    onClick={handleCopyToClipboard}
                                    className="w-full px-4 py-3 text-left hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center gap-2 text-sm"
                                >
                                    {copied ? labels.copied : labels.copyBtn}
                                </button>
                                <button
                                    onClick={handleExportToFile}
                                    className="w-full px-4 py-3 text-left hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center gap-2 text-sm"
                                >
                                    {labels.downloadBtn}
                                </button>

                                {/* Real PDF export */}
                                <button
                                    onClick={handleExportPdf}
                                    disabled={exporting === 'pdf'}
                                    className="w-full px-4 py-3 text-left hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center gap-2 text-sm disabled:opacity-50"
                                >
                                    {exporting === 'pdf' ? labels.exporting : labels.downloadPdf}
                                </button>

                                {/* Real Word export */}
                                <button
                                    onClick={handleExportDocx}
                                    disabled={exporting === 'docx'}
                                    className="w-full px-4 py-3 text-left hover:bg-gray-100 dark:hover:bg-gray-700 rounded-b-lg flex items-center gap-2 text-sm disabled:opacity-50"
                                >
                                    {exporting === 'docx' ? labels.exporting : labels.downloadDocx}
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Output Content */}
            <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4 sm:p-8">
                <div className="prose dark:prose-invert max-w-none">
                    <ReactMarkdown>{output}</ReactMarkdown>
                </div>
            </div>

            {/* Action Buttons */}
            <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
                <button
                    onClick={onAccept}
                    className="w-full sm:w-auto px-8 py-3 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg
                     shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center gap-2"
                >
                    <span>✅</span>
                    <span>Accept</span>
                </button>

                <button
                    onClick={onReject}
                    className="w-full sm:w-auto px-8 py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg
                     shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center gap-2"
                >
                    <span>❌</span>
                    <span>Reject</span>
                </button>

                <button
                    onClick={onRetry}
                    className="w-full sm:w-auto px-8 py-3 border border-gray-300 dark:border-gray-600 
                     hover:bg-gray-100 dark:hover:bg-gray-800
                     font-semibold rounded-lg transition-all duration-200 flex items-center justify-center gap-2"
                >
                    <span>↻</span>
                    <span>Retry</span>
                </button>

                {onSendToAgent && (
                    <button
                        onClick={() => onSendToAgent(generateExportContent())}
                        className="w-full sm:w-auto px-8 py-3 bg-gradient-to-r from-purple-600 to-blue-600 
                         hover:from-purple-700 hover:to-blue-700 text-white font-semibold rounded-lg
                         shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center gap-2"
                    >
                        <span>🤖</span>
                        <span>Send to Agent</span>
                    </button>
                )}
            </div>

            {/* Metadata */}
            <div className="mt-8 text-center text-sm text-gray-500">
                Executed at {new Date().toLocaleString()} • Duration: 12.5s
            </div>
        </div>
    );
}
