import { Template } from '@/types';

export const businessTemplates: Template[] = [
    {
        id: 'business_strategy_wizard',
        name: '📈 Chiến lược Kinh doanh',
        icon: '📈',
        description: 'Wizard nhiều bước tạo Tài liệu Quyết định Chiến lược qua 4 bước: Bối cảnh → Phương án → SWOT/Rủi ro → Đánh giá',
        category: 'business',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Strategy Document', 'SWOT Analysis', 'Options Matrix', 'Recommendation'],
        difficulty: 'advanced',
    },
    {
        id: 'strategy_analysis',
        name: 'Phân tích Chiến lược',
        icon: '📊',
        description: 'Phân tích chiến lược kinh doanh, so sánh các phương án',
        category: 'business',
        fields: [
            { id: 'topic', type: 'text', label: 'Chủ đề chiến lược', placeholder: 'VD: Mở rộng thị trường miền Trung', required: true, section: 'required', hint: 'Nêu rõ quyết định hoặc hướng đi chiến lược cần phân tích', example: 'Mở rộng thị trường miền Trung cho dòng sản phẩm FMCG' },
            { id: 'context', type: 'textarea', label: 'Bối cảnh', placeholder: 'Mô tả ngành, quy mô, thị trường...', required: true, rows: 4, section: 'required', hint: 'Cung cấp càng nhiều bối cảnh càng tốt: ngành, quy mô công ty, thị phần, xu hướng', example: 'Công ty SaaS B2B, 200 nhân viên, doanh thu $5M/năm. Thị trường đang tăng trưởng 15%/năm.' },
            { id: 'options', type: 'textarea', label: 'Các phương án (nếu có)', placeholder: 'Liệt kê các options đang cân nhắc', required: false, rows: 3, section: 'advanced', hint: 'Mỗi phương án 1 dòng, AI sẽ phân tích ưu/nhược điểm', example: '1. Mở chi nhánh trực tiếp\n2. Hợp tác với đối tác địa phương\n3. Bán hàng online' },
            { id: 'constraints', type: 'text', label: 'Ràng buộc', placeholder: 'Budget, timeline, resources...', required: false, section: 'advanced', hint: 'Giới hạn ngân sách, thời gian, nhân lực', example: 'Budget tối đa $500K, phải hoàn thành trong Q3 2026' },
            { id: 'priority', type: 'select', label: 'Ưu tiên', options: ['Growth', 'Stability', 'Cost Optimization'], default: 'Growth', required: false, section: 'advanced', hint: 'Chọn mục tiêu ưu tiên hàng đầu cho chiến lược' },
        ],
        intentPattern: `INTENT:
Tôi muốn phân tích chiến lược [topic].

CONTEXT:
[context]

OPTIONS:
[options]

CONSTRAINTS:
[constraints]

PRIORITY: [priority]

SUCCESS CRITERIA:
- Phân tích rõ ưu/nhược điểm
- Xác định rủi ro chính  
- Đưa ra khuyến nghị có căn cứ`,
        outputExpected: ['Executive Summary', 'Assumptions & Missing Data', 'SWOT Analysis', 'Options Comparison', 'Risk Assessment', 'Recommendations', 'Success Criteria Check', 'Next Actions'],
        outputTemplate: `# Strategy Analysis Output

## Executive Summary
- Goal:
- Primary recommendation:
- Rationale:

## Assumptions & Missing Data
- Missing inputs:
- Assumptions used:

## SWOT Analysis
| Strengths | Weaknesses | Opportunities | Threats |
| --- | --- | --- | --- |
| ... | ... | ... | ... |

## Options Comparison
| Option | Pros | Cons | Cost/Impact | Risks | Notes |
| --- | --- | --- | --- | --- | --- |
| Option A |  |  |  |  |  |
| Option B |  |  |  |  |  |

## Risk Assessment
- Top risks (ranked):
1. ...
2. ...
- Mitigations:
- ...

## Recommendations
- Recommendation 1:
- Recommendation 2 (if needed):

## Success Criteria Check
- [ ] Phân tích rõ ưu/nhược điểm
- [ ] Xác định rủi ro chính
- [ ] Đưa ra khuyến nghị có căn cứ

## Next Actions
- Questions for user:
- Data to confirm:
`,
        difficulty: 'medium',
        sampleOutput: `# Strategy Analysis: Market Expansion

## Executive Summary
Strategic analysis suggests that expanding into the Central region is a viable growth path (Score: 8.5/10), provided that logistics challenges can be mitigated.

## ROI Analysis
- **Estimated Cost:** $500,000
- **Projected Revenue (Year 1):** $1,200,000
- **Break-even Point:** Month 9

## Strategic Options
| Option | Pros | Cons |
|--------|------|------|
| **Direct Expansion** | High control, higher margins | High capex, slow rollout |
| **Partnership** | Fast market entry, low risk | Lower margins, brand dilution risk |

## Recommendation
Proceed with **Partnership** model for the first 12 months to test market demand before committing significant Capex.
`,
    },
    {
        id: 'risk_assessment',
        name: 'Đánh giá Rủi ro',
        icon: '⚠️',
        description: 'Đánh giá rủi ro với kế hoạch giảm thiểu',
        category: 'business',
        fields: [
            { id: 'subject', type: 'text', label: 'Chủ đề đánh giá', placeholder: 'VD: Dự án cloud migration', required: true, section: 'required', hint: 'Dự án, quyết định, hoặc thay đổi cần đánh giá rủi ro', example: 'Migration hệ thống ERP từ on-premise lên AWS' },
            { id: 'description', type: 'textarea', label: 'Mô tả chi tiết', placeholder: 'Mô tả dự án/quyết định cần đánh giá', required: true, rows: 4, section: 'required', hint: 'Mô tả scope, mục tiêu, và những gì đang lo ngại', example: 'Chuyển đổi hệ thống ERP SAP sang cloud. Hiện có 500 users, 10TB data. Lo ngại về downtime và bảo mật.' },
            { id: 'stakeholders', type: 'text', label: 'Stakeholders', placeholder: 'Ai bị ảnh hưởng?', required: false, section: 'advanced', hint: 'Liệt kê các bên liên quan chịu ảnh hưởng', example: 'CTO, team DevOps, khách hàng doanh nghiệp, bộ phận kế toán' },
            { id: 'timeline', type: 'text', label: 'Timeline', placeholder: 'Thời gian thực hiện', required: false, section: 'advanced', hint: 'Thời gian dự kiến triển khai', example: '6 tháng, bắt đầu từ Q2 2026' },
            { id: 'tolerance', type: 'select', label: 'Risk Tolerance', options: ['Low', 'Medium', 'High'], default: 'Medium', required: false, section: 'advanced', hint: 'Mức độ chấp nhận rủi ro: Low = rất thận trọng, High = chấp nhận rủi ro cao' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá rủi ro của [subject].

DESCRIPTION:
[description]

STAKEHOLDERS: [stakeholders]
TIMELINE: [timeline]
RISK TOLERANCE: [tolerance]

SUCCESS CRITERIA:
- Xác định 5-10 rủi ro chính
- Phân loại theo mức độ (High/Medium/Low)
- Đề xuất mitigation cho mỗi rủi ro`,
        outputExpected: ['Risk Matrix', 'Top Risks', 'Mitigation Plans', 'Contingency Plans', 'Recommendations'],
        difficulty: 'medium',
    },
    {
        id: 'competitor_review',
        name: 'Phân tích Đối thủ',
        icon: '🔍',
        description: 'Phân tích đối thủ cạnh tranh',
        category: 'business',
        fields: [
            { id: 'company', type: 'text', label: 'Công ty của bạn', placeholder: 'Tên và mô tả ngắn', required: true, section: 'required', hint: 'Tên công ty và lĩnh vực hoạt động chính', example: 'ShopX — sàn thương mại điện tử cho hàng thủ công Việt Nam' },
            { id: 'competitors', type: 'textarea', label: 'Đối thủ chính', placeholder: 'Liệt kê các đối thủ cần phân tích', required: true, rows: 3, section: 'required', hint: 'Mỗi đối thủ 1 dòng, có thể kèm URL hoặc mô tả ngắn', example: '1. Shopee — sàn TMĐT lớn nhất ĐNA\n2. Tiki — sàn TMĐT Việt Nam\n3. Etsy — sàn hàng thủ công quốc tế' },
            { id: 'industry', type: 'text', label: 'Ngành', placeholder: 'VD: E-commerce, Fintech...', required: true, section: 'required', hint: 'Ngành hoạt động chung của bạn và đối thủ', example: 'E-commerce hàng thủ công / handmade' },
            { id: 'criteria', type: 'textarea', label: 'Tiêu chí so sánh', placeholder: 'Giá, chất lượng, marketing, tech...', required: false, rows: 2, section: 'advanced', hint: 'Các khía cạnh bạn muốn so sánh giữa các đối thủ', example: 'Giá cả, trải nghiệm người dùng, chính sách ship hàng, hỗ trợ seller' },
        ],
        intentPattern: `INTENT:
Tôi muốn phân tích đối thủ cạnh tranh trong ngành [industry].

MY COMPANY: [company]

COMPETITORS:
[competitors]

COMPARISON CRITERIA:
[criteria]

SUCCESS CRITERIA:
- Ma trận so sánh các đối thủ
- Điểm mạnh/yếu từng đối thủ
- Cơ hội khác biệt hóa`,
        outputExpected: ['Competitor Matrix', 'SWOT per Competitor', 'Differentiation Opportunities', 'Market Positioning'],
        difficulty: 'medium',
    },
];
