import { Template } from '@/types';

export const developmentTemplates: Template[] = [
    {
        id: 'app_builder_wizard',
        name: '🧙 Xây dựng Ứng dụng',
        icon: '🧙',
        description: 'Multi-step wizard tạo spec qua 8 bước. Khuyên dùng cho app phức tạp!',
        category: 'development',
        difficulty: 'medium',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Complete App Spec', 'All Design Decisions', 'Build Ready Output'],
    },
    {
        id: 'build_my_app',
        name: '🚀 Tạo Ứng dụng',
        icon: '🚀',
        description: 'Mô tả ý tưởng app → AI tự quyết định mọi thứ và build cho bạn. Dành cho người không biết code.',
        category: 'development',
        difficulty: 'easy',
        fields: [
            { id: 'appIdea', type: 'textarea', label: 'Ý tưởng App', placeholder: 'VD: "Tôi muốn app quản lý công việc cá nhân, có thể thêm task, đặt deadline, nhắc nhở..."', required: true, rows: 4, section: 'required', hint: 'Mô tả bằng ngôn ngữ tự nhiên, AI sẽ tự xác định requirements', example: 'App quản lý chi tiêu cá nhân: thêm giao dịch, phân loại, xem biểu đồ, nhắc nhở khi vượt ngân sách' },
            { id: 'appType', type: 'select', label: 'Loại App', options: ['Desktop App (cài trên máy)', 'CLI Tool (dòng lệnh)', 'Web App', 'Mobile App'], required: true, section: 'required', hint: 'Chọn nền tảng chính của ứng dụng' },
            { id: 'targetUser', type: 'text', label: 'Ai sẽ dùng?', placeholder: 'VD: Tôi dùng cá nhân, Team nhỏ 5 người, Khách hàng...', required: true, section: 'required', hint: 'Ai là người dùng chính của app?', example: 'Tôi dùng cá nhân để quản lý chi tiêu hàng ngày' },
            { id: 'platform', type: 'select', label: 'Chạy trên', options: ['Windows', 'macOS', 'Linux', 'Cả 3 hệ điều hành', 'Web Browser'], required: true, section: 'required', hint: 'Nền tảng mà app cần chạy được' },
            { id: 'preferences', type: 'textarea', label: 'Yêu cầu thêm (optional)', placeholder: 'VD: Giao diện tối, đơn giản, offline được...', required: false, rows: 2, section: 'advanced', hint: 'Yêu cầu đặc biệt về giao diện, offline, ngôn ngữ...', example: 'Dark mode, hoạt động offline, tiếng Việt' },
        ],
        intentPattern: `INTENT:
Tôi muốn AI build cho tôi một [appType].

Ý TƯỞNG:
[appIdea]

THÔNG TIN:
- Người dùng: [targetUser]
- Platform: [platform]
- Yêu cầu thêm: [preferences]

QUAN TRỌNG - YÊU CẦU CHO AI:
Đây là Vibe Coding - User chỉ mô tả ý tưởng, AI chịu trách nhiệm 100% về:
1. Phân tích requirements
2. Chọn tech stack phù hợp
3. Thiết kế architecture
4. Thiết kế database (nếu cần)
5. Build toàn bộ app
6. Test và packaging

User chỉ đánh giá kết quả cuối cùng.`,
        outputExpected: ['Complete Working App', 'Setup Instructions', 'User Guide'],
    },
    {
        id: 'app_builder_complete',
        name: '📦 Tạo Ứng dụng Hoàn chỉnh',
        icon: '📦',
        description: 'Tạo spec hoàn chỉnh với đầy đủ thông tin kỹ thuật. Dành cho người hiểu quy trình CVF.',
        category: 'development',
        difficulty: 'advanced',
        fields: [
            // Section 1: Requirements
            { id: 'appName', type: 'text', label: '1. Tên App', placeholder: 'VD: TaskFlow', required: true, section: 'required', hint: 'Tên ngắn gọn, dễ nhớ', example: 'TaskFlow' },
            { id: 'appType', type: 'select', label: '2. Loại App', options: ['Desktop (Cross-platform)', 'CLI Tool', 'Desktop + CLI', 'Web SPA', 'Mobile'], required: true, section: 'required', hint: 'Chọn loại app phù hợp với nhu cầu' },
            { id: 'problem', type: 'textarea', label: '3. Vấn đề cần giải quyết', placeholder: 'Mô tả vấn đề user đang gặp phải', required: true, rows: 3, section: 'required', hint: 'Vấn đề cụ thể mà app giải quyết', example: 'Developer cần track tasks nhưng Jira quá phức tạp, cần tool nhẹ, chạy local' },
            { id: 'targetUsers', type: 'text', label: '4. Target Users', placeholder: 'VD: Developer cá nhân, Team nhỏ', required: true, section: 'required', hint: 'Nhóm người dùng chính', example: 'Developer cá nhân và team nhỏ (2-5 người)' },
            { id: 'coreFeatures', type: 'textarea', label: '5. Core Features (3-5)', placeholder: '1. Feature A\n2. Feature B\n3. Feature C', required: true, rows: 4, section: 'required', hint: 'Liệt kê 3-5 tính năng quan trọng nhất', example: '1. CRUD tasks với title, description, status\n2. Kanban board view\n3. Filter/search tasks\n4. Keyboard shortcuts' },

            // Section 2: Technical Preferences
            { id: 'platforms', type: 'text', label: '6. Target Platforms', placeholder: 'Windows, macOS, Linux...', required: true, section: 'required', hint: 'Hệ điều hành cần hỗ trợ', example: 'Windows + macOS' },
            { id: 'techPreference', type: 'text', label: '7. Tech Preference (optional)', placeholder: 'VD: Tauri, Electron, Python...', required: false, section: 'advanced', hint: 'Để trống nếu muốn AI tự chọn', example: 'Tauri + React' },
            { id: 'dataStorage', type: 'select', label: '8. Data Storage', options: ['None', 'Local Files (JSON/YAML)', 'Local Database (SQLite)', 'Cloud Database'], required: false, section: 'advanced', hint: 'Cách lưu trữ dữ liệu của app' },
            { id: 'offlineRequired', type: 'select', label: '9. Offline Mode', options: ['Required', 'Nice to have', 'Not needed'], required: false, section: 'advanced', hint: 'App có cần hoạt động khi không có internet?' },

            // Section 3: App-specific
            { id: 'uiStyle', type: 'select', label: '10. UI Style', options: ['Modern Dark', 'Clean Light', 'Minimal', 'No UI (CLI only)'], required: false, section: 'advanced', hint: 'Phong cách giao diện' },
            { id: 'specialFeatures', type: 'textarea', label: '11. Special Features', placeholder: 'VD: System tray, Keyboard shortcuts, Notifications...', required: false, rows: 2, section: 'advanced', hint: 'Tính năng đặc biệt của desktop/CLI', example: 'System tray icon, global hotkey Ctrl+Shift+T, desktop notifications' },

            // Section 4: Constraints
            { id: 'outOfScope', type: 'textarea', label: '12. Out of Scope', placeholder: 'Những gì KHÔNG làm trong v1', required: false, rows: 2, section: 'advanced', hint: 'Giới hạn scope để AI không over-engineer', example: 'Không cần multi-user, không cần mobile, không cần cloud sync' },
            { id: 'constraints', type: 'text', label: '13. Constraints', placeholder: 'VD: Bundle < 50MB, No internet required', required: false, section: 'advanced', hint: 'Giới hạn kỹ thuật', example: 'Bundle < 30MB, startup < 2s' },
        ],
        intentPattern: `INTENT:
Tạo Complete App Specification cho [appName] - một [appType].

═══════════════════════════════════════════════════
SECTION 1: REQUIREMENTS
═══════════════════════════════════════════════════

**Problem Statement:**
[problem]

**Target Users:** [targetUsers]

**Core Features:**
[coreFeatures]

**Out of Scope:**
[outOfScope]

═══════════════════════════════════════════════════
SECTION 2: TECHNICAL REQUIREMENTS
═══════════════════════════════════════════════════

**Platforms:** [platforms]
**Tech Preference:** [techPreference]
**Data Storage:** [dataStorage]
**Offline Mode:** [offlineRequired]
**Constraints:** [constraints]

═══════════════════════════════════════════════════
SECTION 3: UI/UX REQUIREMENTS
═══════════════════════════════════════════════════

**UI Style:** [uiStyle]
**Special Features:** [specialFeatures]

═══════════════════════════════════════════════════
AI INSTRUCTIONS
═══════════════════════════════════════════════════

Dựa trên spec này, hãy thực hiện THEO THỨ TỰ:

**Phase A - Discovery:** Xác nhận bạn hiểu đúng requirements.

**Phase B - Design:** 
- Chọn tech stack (KHÔNG hỏi user chọn)
- Thiết kế architecture
- Thiết kế database schema (nếu cần)
- Thiết kế API/commands (nếu cần)

**Phase C - Build:**
- Build từng component
- Tạo full source code
- Tạo config files

**Phase D - Review:**
- Tóm tắt những gì đã build
- Hướng dẫn setup và chạy
- Hướng dẫn packaging/distribution`,
        outputExpected: [
            'Tech Stack Decision',
            'Architecture Diagram',
            'Database Schema (if needed)',
            'Complete Source Code',
            'Setup & Run Instructions',
            'Packaging Guide'
        ],
    },
    {
        id: 'individual_skills_folder',
        name: '📂 Skill Templates (8)',
        icon: '📂',
        description: '8 templates riêng lẻ cho từng khâu: Requirements, Tech Stack, Architecture, Database, API, Desktop/CLI, Deployment.',
        category: 'development',
        difficulty: 'medium',
        fields: [],
        intentPattern: '',
        outputExpected: [],
        isFolder: true, // This is a folder, not a template
    },
    {
        id: 'app_requirements_spec',
        name: 'Spec Yêu cầu Ứng dụng',
        icon: '📑',
        description: 'Thu thập requirements cho app mới, định nghĩa scope và success criteria',
        category: 'development',
        difficulty: 'medium',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'VD: TaskFlow - Quản lý công việc', required: true, section: 'required', hint: 'Tên app kèm mô tả ngắn', example: 'TaskFlow — Quản lý công việc cá nhân' },
            { id: 'appType', type: 'select', label: 'App Type', options: ['Desktop', 'CLI Tool', 'Mobile', 'Web App', 'API Service'], required: true, section: 'required', hint: 'Loại ứng dụng cần build' },
            { id: 'problem', type: 'textarea', label: 'Problem Statement', placeholder: 'Vấn đề cần giải quyết là gì?', required: true, rows: 3, section: 'required', hint: 'Mô tả vấn đề thực tế mà app giải quyết', example: 'Developer cần tool nhẹ, chạy local để track tasks hàng ngày mà không cần Jira' },
            { id: 'targetUsers', type: 'text', label: 'Target Users', placeholder: 'Ai sẽ dùng app này?', required: true, section: 'required', hint: 'Mô tả người dùng chính', example: 'Developer cá nhân, thích terminal-based tools' },
            { id: 'coreFeatures', type: 'textarea', label: 'Core Features (3-5)', placeholder: '1. Feature 1\n2. Feature 2\n3. Feature 3', required: true, rows: 4, section: 'required', hint: 'Liệt kê 3-5 tính năng quan trọng nhất cho v1', example: '1. CRUD tasks\n2. Priority levels\n3. Due date + reminder\n4. Search/filter\n5. Export to Markdown' },
            { id: 'outOfScope', type: 'textarea', label: 'Out of Scope', placeholder: 'Những gì KHÔNG làm trong phiên bản này', required: true, rows: 3, section: 'required', hint: 'Định nghĩa rõ những gì không làm để kiểm soát scope', example: 'Không cần multi-user, không cần mobile app, không cần cloud sync' },
            { id: 'successCriteria', type: 'textarea', label: 'Success Criteria', placeholder: 'Khi nào app được coi là done?', required: true, rows: 2, section: 'required', hint: 'Tiêu chí cụ thể, đo lường được', example: 'User có thể CRUD tasks, filter theo status, và app chạy stable trên Windows/macOS' },
            { id: 'platform', type: 'text', label: 'Platform', placeholder: 'Windows, macOS, Linux...', required: false, section: 'advanced', hint: 'Hệ điều hành cần hỗ trợ', example: 'Windows + macOS' },
            { id: 'dataStorage', type: 'select', label: 'Data Storage', options: ['None', 'Local File', 'Local Database (SQLite)', 'Cloud'], required: false, section: 'advanced', hint: 'Cách lưu trữ dữ liệu của app' },
        ],
        intentPattern: `INTENT:
Tôi muốn tạo App Requirements Specification cho [appName].

APP INFO:
- Type: [appType]
- Target Users: [targetUsers]
- Platform: [platform]
- Data Storage: [dataStorage]

PROBLEM STATEMENT:
[problem]

CORE FEATURES:
[coreFeatures]

OUT OF SCOPE:
[outOfScope]

SUCCESS CRITERIA:
[successCriteria]

OUTPUT REQUIREMENTS:
- Problem statement rõ ràng
- Core features có priority
- Out of scope được định nghĩa
- Success criteria có thể measure được`,
        outputExpected: ['Requirements Document', 'Feature List with Priority', 'Scope Definition', 'Success Metrics'],
    },
    {
        id: 'tech_stack_selection',
        name: 'Chọn Tech Stack',
        icon: '⚙️',
        description: 'Chọn công nghệ phù hợp cho app dựa trên requirements',
        category: 'development',
        difficulty: 'medium',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appType', type: 'select', label: 'App Type', options: ['Desktop (Cross-platform)', 'CLI Tool', 'Mobile (Cross-platform)', 'Web SPA', 'API Backend'], required: true, section: 'required', hint: 'Loại app quyết định các lựa chọn tech khác nhau' },
            { id: 'performancePriority', type: 'select', label: 'Performance Priority', options: ['Low', 'Medium', 'High', 'Critical'], required: true, section: 'required', hint: 'Mức ưu tiên về hiệu năng: Critical = latency-sensitive, real-time' },
            { id: 'devSpeed', type: 'select', label: 'Development Speed Priority', options: ['Low', 'Medium', 'High'], required: true, section: 'required', hint: 'Ưu tiên tốc độ phát triển: High = cần ship nhanh' },
            { id: 'platforms', type: 'text', label: 'Target Platforms', placeholder: 'Windows, macOS, Linux...', required: true, section: 'required', hint: 'Các platform cần hỗ trợ', example: 'Windows + macOS + Linux' },
            { id: 'dataNeeds', type: 'select', label: 'Data Storage Needs', options: ['None', 'Local Only', 'Cloud Only', 'Both'], required: true, section: 'required', hint: 'Nơi lưu trữ dữ liệu của ứng dụng' },
            { id: 'offlineRequired', type: 'select', label: 'Offline Required?', options: ['Yes', 'No', 'Partial'], required: true, section: 'required', hint: 'App có cần hoạt động khi mất mạng?' },
            { id: 'teamExp', type: 'text', label: 'Team Experience', placeholder: 'VD: Python, JavaScript', required: false, section: 'advanced', hint: 'Ngôn ngữ/framework team đã quen', example: 'TypeScript, React, Python' },
            { id: 'langPreference', type: 'text', label: 'Language Preference', placeholder: 'Ngôn ngữ ưu tiên (nếu có)', required: false, section: 'advanced', hint: 'Để trống để AI tự đề xuất', example: 'Rust hoặc TypeScript' },
            { id: 'bundleSize', type: 'text', label: 'Bundle Size Constraint', placeholder: 'VD: < 50MB', required: false, section: 'advanced', hint: 'Giới hạn kích thước file cài đặt', example: '< 30MB' },
        ],
        intentPattern: `INTENT:
So sánh và recommend tech stack cho [appType].

REQUIREMENTS:
- Performance Priority: [performancePriority]
- Development Speed: [devSpeed]
- Target Platforms: [platforms]
- Data Storage: [dataNeeds]
- Offline Required: [offlineRequired]
- Bundle Size: [bundleSize]

TEAM CONTEXT:
- Experience: [teamExp]
- Language Preference: [langPreference]

OUTPUT REQUIREMENTS:
- Compare at least 2 options per layer
- Clear reasoning for each choice
- Trade-offs acknowledged
- Final stack consistent with requirements`,
        outputExpected: ['Options Comparison Tables', 'Recommended Stack', 'Trade-offs Analysis', 'Setup Commands'],
    },
    {
        id: 'architecture_design',
        name: 'Thiết kế Kiến trúc',
        icon: '🧱',
        description: 'Thiết kế kiến trúc hệ thống với component diagram',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required', hint: 'Tên app cần thiết kế kiến trúc', example: 'TaskFlow' },
            { id: 'techStack', type: 'text', label: 'Tech Stack', placeholder: 'VD: Tauri + Vue 3 + SQLite', required: true, section: 'required', hint: 'Tech stack đã chọn cho app', example: 'Tauri + React + SQLite' },
            { id: 'coreFeatures', type: 'textarea', label: 'Core Features', placeholder: 'Các tính năng chính', required: true, rows: 3, section: 'required', hint: 'Danh sách features để AI thiết kế components phù hợp', example: '1. Task CRUD\n2. Kanban board\n3. Search & filter\n4. Keyboard shortcuts' },
            { id: 'appType', type: 'select', label: 'Architecture Type', options: ['Desktop App', 'CLI Tool', 'Web SPA', 'API Backend', 'Full-stack'], required: true, section: 'required', hint: 'Loại kiến trúc quyết định các layers và patterns' },
            { id: 'dataFlow', type: 'textarea', label: 'Data Flow', placeholder: 'VD: User → UI → Backend → DB → UI', required: true, rows: 2, section: 'required', hint: 'Luồng dữ liệu chính của app', example: 'User → React UI → Tauri commands → SQLite → React UI' },
            { id: 'integrations', type: 'text', label: 'External Integrations', placeholder: 'VD: REST API, File system (hoặc None)', required: false, section: 'advanced', hint: 'Hệ thống bên ngoài cần kết nối', example: 'File system (export Markdown), GitHub API (import issues)' },
            { id: 'stateComplexity', type: 'select', label: 'State Complexity', options: ['Simple', 'Medium', 'Complex'], required: false, section: 'advanced', hint: 'Simple = useState, Medium = Zustand, Complex = Redux/MobX' },
        ],
        intentPattern: `INTENT:
Thiết kế architecture cho [appName].

TECH STACK: [techStack]
APP TYPE: [appType]

CORE FEATURES:
[coreFeatures]

DATA FLOW:
[dataFlow]

EXTERNAL INTEGRATIONS: [integrations]
STATE COMPLEXITY: [stateComplexity]

OUTPUT REQUIREMENTS:
- System diagram (ASCII art)
- Component breakdown với responsibilities
- Directory structure
- Data flow documentation
- Key design decisions`,
        outputExpected: ['System Diagram', 'Component Breakdown', 'Directory Structure', 'Data Flow', 'Design Decisions'],
    },
    {
        id: 'database_schema',
        name: 'Thiết kế Database Schema',
        icon: '🗄️',
        description: 'Thiết kế database schema với ERD và SQL',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required', hint: 'Tên app cần thiết kế database', example: 'TaskFlow' },
            { id: 'dbType', type: 'select', label: 'Database Type', options: ['SQLite', 'PostgreSQL', 'MySQL', 'MongoDB'], required: true, section: 'required', hint: 'Loại database: SQLite cho local app, PostgreSQL cho server' },
            { id: 'entities', type: 'textarea', label: 'Main Entities', placeholder: 'VD: User, Task, Category, Tag', required: true, rows: 2, section: 'required', hint: 'Các entity/bảng chính của hệ thống', example: 'User, Project, Task, Category, Tag' },
            { id: 'relationships', type: 'textarea', label: 'Relationships', placeholder: 'VD: User has many Tasks, Task belongs to Category', required: true, rows: 3, section: 'required', hint: 'Mối quan hệ giữa các entity', example: 'User has many Projects\nProject has many Tasks\nTask belongs to Category\nTask has many Tags (M:N)' },
            { id: 'keyFields', type: 'textarea', label: 'Key Fields per Entity', placeholder: 'VD: Task: title, description, due_date, status', required: true, rows: 3, section: 'required', hint: 'Các trường quan trọng của mỗi entity', example: 'Task: title, description, status (todo/doing/done), priority, due_date\nUser: email, name, avatar' },
            { id: 'queryNeeds', type: 'textarea', label: 'Common Queries', placeholder: 'VD: Search by title, filter by status', required: false, rows: 2, section: 'advanced', hint: 'Các query thường dùng để AI tối ưu index', example: 'Tasks by status, tasks by due_date range, full-text search title' },
            { id: 'audit', type: 'select', label: 'Audit Requirements', options: ['None', 'Created/Updated timestamps', 'Full audit trail'], required: false, section: 'advanced', hint: 'Có cần lưu lịch sử thay đổi?' },
        ],
        intentPattern: `INTENT:
Thiết kế database schema cho [appName].

DATABASE: [dbType]

ENTITIES:
[entities]

RELATIONSHIPS:
[relationships]

KEY FIELDS:
[keyFields]

COMMON QUERIES:
[queryNeeds]

AUDIT: [audit]

OUTPUT REQUIREMENTS:
- ERD diagram (ASCII art)
- Table definitions với data types
- SQL CREATE statements
- Index recommendations
- Sample queries`,
        outputExpected: ['ERD Diagram', 'Table Definitions', 'SQL Schema', 'Indexes', 'Sample Queries'],
    },
    {
        id: 'api_design',
        name: 'Spec Thiết kế API',
        icon: '🔌',
        description: 'Thiết kế REST API với endpoints và request/response format',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App/Service Name', placeholder: 'Tên API', required: true, section: 'required', hint: 'Tên app hoặc service cần thiết kế API', example: 'TaskFlow API' },
            { id: 'apiStyle', type: 'select', label: 'API Style', options: ['REST', 'GraphQL', 'IPC (Desktop)'], required: true, section: 'required', hint: 'REST cho web, IPC cho desktop app (Tauri/Electron)' },
            { id: 'resources', type: 'textarea', label: 'Resources/Entities', placeholder: 'VD: User, Task, Category', required: true, rows: 2, section: 'required', hint: 'Các resource/entity chính của API', example: 'User, Project, Task, Category, Tag' },
            { id: 'operations', type: 'textarea', label: 'Operations per Resource', placeholder: 'VD: Task: CRUD + complete, archive', required: true, rows: 3, section: 'required', hint: 'Các thao tác cho mỗi resource', example: 'Task: CRUD + complete + archive + assign\nProject: CRUD + add member\nUser: register + login + update profile' },
            { id: 'auth', type: 'select', label: 'Authentication', options: ['None', 'JWT Bearer', 'API Key', 'OAuth2'], required: true, section: 'required', hint: 'Phương thức xác thực cho API' },
            { id: 'pagination', type: 'select', label: 'Pagination', options: ['Not needed', 'Offset/Limit', 'Cursor-based'], required: false, section: 'advanced', hint: 'Offset/Limit dễ implement, Cursor-based hiệu quả hơn với data lớn' },
            { id: 'responseFormat', type: 'select', label: 'Response Format', options: ['JSON', 'XML', 'Both'], default: 'JSON', required: false, section: 'advanced', hint: 'Định dạng response trả về' },
        ],
        intentPattern: `INTENT:
Thiết kế API specification cho [appName].

API STYLE: [apiStyle]
AUTH: [auth]
RESPONSE FORMAT: [responseFormat]
PAGINATION: [pagination]

RESOURCES:
[resources]

OPERATIONS:
[operations]

OUTPUT REQUIREMENTS:
- All endpoints documented
- Request/Response format with examples
- Error codes and messages
- Authentication details
- Pagination for list endpoints`,
        outputExpected: ['API Overview', 'Endpoint Documentation', 'Request/Response Examples', 'Error Codes', 'Auth Details'],
    },
    {
        id: 'desktop_app_spec',
        name: 'Spec Ứng dụng Desktop',
        icon: '🖥️',
        description: 'Spec cho desktop app: windows, menus, shortcuts, tray',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required', hint: 'Tên app desktop cần tạo spec', example: 'TaskFlow' },
            { id: 'framework', type: 'select', label: 'Framework', options: ['Tauri', 'Electron', 'PyQt/PySide', 'Wails', 'Native'], required: true, section: 'required', hint: 'Tauri = nhẹ + Rust, Electron = Node.js + Chrome, PyQt = Python' },
            { id: 'platforms', type: 'text', label: 'Target Platforms', placeholder: 'Windows, macOS, Linux', required: true, section: 'required', hint: 'Hệ điều hành cần hỗ trợ', example: 'Windows + macOS' },
            { id: 'windowType', type: 'select', label: 'Window Type', options: ['Single Window', 'Multi-Window', 'Frameless'], required: true, section: 'required', hint: 'Single = 1 cửa sổ, Frameless = custom title bar' },
            { id: 'defaultSize', type: 'text', label: 'Default Size', placeholder: 'VD: 1024x768', required: true, section: 'required', hint: 'Kích thước cửa sổ mặc định', example: '1200x800' },
            { id: 'menuBar', type: 'textarea', label: 'Menu Bar', placeholder: 'VD: File (New, Save, Exit), Edit, Help', required: true, rows: 2, section: 'required', hint: 'Cấu trúc menu bar của app', example: 'File (New Project, Save, Export, Exit)\nEdit (Undo, Redo, Preferences)\nHelp (About, Docs)' },
            { id: 'tray', type: 'select', label: 'System Tray', options: ['No', 'Yes - Basic', 'Yes - With Quick Actions'], required: false, section: 'advanced', hint: 'Icon ở system tray khi minimize' },
            { id: 'shortcuts', type: 'textarea', label: 'Keyboard Shortcuts', placeholder: 'VD: Ctrl+N new, Ctrl+S save', required: false, rows: 2, section: 'advanced', hint: 'Phím tắt cho các thao tác thường dùng', example: 'Ctrl+N: New task\nCtrl+S: Save\nCtrl+F: Search\nCtrl+Q: Quit' },
            { id: 'nativeFeatures', type: 'text', label: 'Native Features', placeholder: 'VD: Notifications, File dialogs', required: false, section: 'advanced', hint: 'Tính năng native OS cần dùng', example: 'Desktop notifications, native file dialogs, auto-start' },
        ],
        intentPattern: `INTENT:
Tạo Desktop App Specification cho [appName].

FRAMEWORK: [framework]
PLATFORMS: [platforms]
WINDOW: [windowType], [defaultSize]

MENU BAR:
[menuBar]

SYSTEM TRAY: [tray]

KEYBOARD SHORTCUTS:
[shortcuts]

NATIVE FEATURES: [nativeFeatures]

OUTPUT REQUIREMENTS:
- Window configuration complete
- Menu structure với shortcuts
- System tray behavior
- Platform-specific notes
- Lifecycle behavior (startup, close)`,
        outputExpected: ['Window Config', 'Menu Structure', 'Shortcuts Table', 'Tray Behavior', 'Platform Notes'],
    },
    {
        id: 'cli_tool_spec',
        name: 'Spec Công cụ CLI',
        icon: '⌨️',
        description: 'Spec cho command-line tool: commands, arguments, options',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'toolName', type: 'text', label: 'Tool Name', placeholder: 'VD: taskflow hoặc tf', required: true, section: 'required', hint: 'Tên lệnh ngắn gọn, dễ gõ', example: 'tf (TaskFlow CLI)' },
            { id: 'purpose', type: 'textarea', label: 'Purpose', placeholder: 'Tool này làm gì?', required: true, rows: 2, section: 'required', hint: 'Mô tả ngắn về mục đích của CLI tool', example: 'Quản lý tasks từ terminal: thêm, xem, hoàn thành, xóa tasks nhanh chóng' },
            { id: 'commands', type: 'textarea', label: 'Commands', placeholder: 'VD: add, list, done, delete, search, config', required: true, rows: 2, section: 'required', hint: 'Danh sách commands chính', example: 'add, list, done, delete, search, config, export' },
            { id: 'targetUsers', type: 'text', label: 'Target Users', placeholder: 'Ai sẽ dùng?', required: true, section: 'required', hint: 'Ai là người dùng chính?', example: 'Developer thích làm việc từ terminal' },
            { id: 'language', type: 'select', label: 'Language', options: ['Python (Click)', 'Rust (Clap)', 'Go (Cobra)', 'Node.js (Commander)', 'Other'], required: true, section: 'required', hint: 'Ngôn ngữ và CLI framework' },
            { id: 'configLocation', type: 'text', label: 'Config Location', placeholder: 'VD: ~/.toolname/config.yaml', required: false, section: 'advanced', hint: 'Nơi lưu file cấu hình', example: '~/.tf/config.yaml' },
            { id: 'dataStorage', type: 'text', label: 'Data Storage', placeholder: 'VD: ~/.toolname/data.json', required: false, section: 'advanced', hint: 'Nơi lưu dữ liệu của tool', example: '~/.tf/tasks.db (SQLite)' },
            { id: 'outputFormats', type: 'text', label: 'Output Formats', placeholder: 'VD: text, json, table', required: false, section: 'advanced', hint: 'Định dạng output hỗ trợ', example: 'text (default), json, table, csv' },
        ],
        intentPattern: `INTENT:
Tạo CLI Tool Specification cho [toolName].

PURPOSE:
[purpose]

TARGET USERS: [targetUsers]
LANGUAGE: [language]

COMMANDS:
[commands]

CONFIG: [configLocation]
DATA: [dataStorage]
OUTPUT FORMATS: [outputFormats]

OUTPUT REQUIREMENTS:
- All commands documented
- Arguments và options clear
- Exit codes defined
- Config file format
- Examples cho mỗi command`,
        outputExpected: ['Command Documentation', 'Arguments/Options', 'Exit Codes', 'Config Format', 'Usage Examples'],
    },
    {
        id: 'local_deployment',
        name: 'Spec Triển khai Local',
        icon: '💿',
        description: 'Packaging và distribution spec cho local apps',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required', hint: 'Tên app cần tạo deployment spec', example: 'TaskFlow' },
            { id: 'appType', type: 'select', label: 'App Type', options: ['Desktop (Tauri)', 'Desktop (Electron)', 'CLI Tool', 'Service'], required: true, section: 'required', hint: 'Loại app quyết định cách packaging' },
            { id: 'platforms', type: 'text', label: 'Target Platforms', placeholder: 'Windows, macOS, Linux', required: true, section: 'required', hint: 'Các platform cần build installer', example: 'Windows (.msi) + macOS (.dmg)' },
            { id: 'distribution', type: 'select', label: 'Distribution Method', options: ['GitHub Releases', 'Website Download', 'Package Manager (npm/pip)', 'Internal Only'], required: true, section: 'required', hint: 'Kênh phân phối app đến users' },
            { id: 'autoUpdate', type: 'select', label: 'Auto-Update', options: ['No', 'Yes - Prompt User', 'Yes - Silent'], required: false, section: 'advanced', hint: 'Auto-update giúp users luôn dùng version mới nhất' },
            { id: 'signing', type: 'select', label: 'Code Signing', options: ['No', 'Windows Only', 'macOS Only', 'Both'], required: false, section: 'advanced', hint: 'Code signing giúp tránh cảnh báo SmartScreen/Gatekeeper' },
            { id: 'dependencies', type: 'text', label: 'Runtime Dependencies', placeholder: 'VD: None, .NET, Python', required: false, section: 'advanced', hint: 'Phần mềm cần cài trước khi chạy app', example: 'None (standalone binary)' },
        ],
        intentPattern: `INTENT:
Tạo Deployment Specification cho [appName].

APP TYPE: [appType]
PLATFORMS: [platforms]
DISTRIBUTION: [distribution]

AUTO-UPDATE: [autoUpdate]
CODE SIGNING: [signing]
DEPENDENCIES: [dependencies]

OUTPUT REQUIREMENTS:
- Build artifacts for all platforms
- Build commands
- Installer configuration
- Distribution process
- Code signing steps (if applicable)
- Testing checklist`,
        outputExpected: ['Build Artifacts', 'Build Commands', 'Installer Config', 'CI/CD Config', 'Distribution Process'],
    },
];
