import { Template } from '@/types';

export const developmentTemplates: Template[] = [
    {
        id: 'app_builder_wizard',
        name: '🧙 Xây dựng Ứng dụng',
        icon: '🧙',
        description: 'Multi-step wizard tạo app spec với governed packet, review và live path. Khuyên dùng cho app phức tạp!',
        category: 'development',
        difficulty: 'medium',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Complete App Spec', 'All Design Decisions', 'Build Ready Output'],
    },
    {
        id: 'build_my_app',
        name: '🚀 Tạo Ứng dụng',
        icon: '🚀',
        description: 'Mô tả ý tưởng app để CVF route vào governed starter path cho người không biết code.',
        category: 'development',
        difficulty: 'easy',
        fields: [
            { id: 'appIdea', type: 'textarea', label: 'Ý tưởng App', placeholder: 'VD: "Tôi muốn app quản lý công việc cá nhân, có thể thêm task, đặt deadline, nhắc nhở..."', required: true, rows: 4, section: 'required', hint: 'Mô tả bằng ngôn ngữ tự nhiên, AI sẽ tự xác định requirements', example: 'App quản lý chi tiêu cá nhân: thêm giao dịch, phân loại, xem biểu đồ, nhắc nhở khi vượt ngân sách' },
            { id: 'appType', type: 'select', label: 'Loại App', options: ['Desktop App (cài trên máy)', 'CLI Tool (dòng lệnh)', 'Web App', 'Mobile App'], required: true, section: 'required', hint: 'Chọn nền tảng chính của ứng dụng' },
            { id: 'targetUser', type: 'text', label: 'Ai sẽ dùng?', placeholder: 'VD: Tôi dùng cá nhân, Team nhỏ 5 người, Khách hàng...', required: true, section: 'required', hint: 'Ai là người dùng chính của app?', example: 'Tôi dùng cá nhân để quản lý chi tiêu hàng ngày' },
            { id: 'platform', type: 'select', label: 'Chạy trên', options: ['Windows', 'macOS', 'Linux', 'Cả 3 hệ điều hành', 'Web Browser'], required: true, section: 'required', hint: 'Nền tảng mà app cần chạy được' },
            { id: 'preferences', type: 'textarea', label: 'Yêu cầu thêm (optional)', placeholder: 'VD: Giao diện tối, đơn giản, offline được...', required: false, rows: 2, section: 'advanced', hint: 'Yêu cầu đặc biệt về giao diện, offline, ngôn ngữ...', example: 'Dark mode, hoạt động offline, tiếng Việt' },
        ],
        intentPattern: `INTENT:
Tôi muốn AI build cho tôi một [appType].

Ý TƯỞNG:
[appIdea]

THÔNG TIN:
- Người dùng: [targetUser]
- Platform: [platform]
- Yêu cầu thêm: [preferences]

OUTPUT REQUIREMENTS:
- Translate the user's idea into a working app without asking them to choose frameworks or technical patterns
- AI is responsible for requirements analysis, tech stack selection, architecture, database design, and full build
- User only evaluates the final result

SUCCESS CRITERIA:
- Produce a working [appType] for [targetUser] on [platform]
- The app solves the described idea end-to-end
- Setup instructions are non-technical and runnable without terminal expertise`,
        outputExpected: ['Complete Working App', 'Setup Instructions', 'User Guide'],
    },
    {
        id: 'app_builder_complete',
        name: '📦 Tạo Ứng dụng Hoàn chỉnh',
        icon: '📦',
        description: 'Biến brief sản phẩm đầy đủ thành packet build-ready để non-coder vẫn mô tả rõ mục tiêu, phạm vi và ranh giới mà không phải chọn stack hay hạ tầng.',
        category: 'development',
        difficulty: 'advanced',
        fields: [
            { id: 'appName', type: 'text', label: '1. Tên app / sản phẩm', placeholder: 'VD: TaskFlow', required: true, section: 'required', hint: 'Tên gọi dễ nhớ để packet và handoff bám đúng sản phẩm.', example: 'TaskFlow' },
            { id: 'appType', type: 'select', label: '2. Đây là loại sản phẩm gì?', options: ['Desktop App', 'CLI Tool', 'Desktop + CLI', 'Web App', 'Mobile App'], required: true, section: 'required', hint: 'Chỉ cần chọn loại bề mặt chính, không cần nói framework.' },
            { id: 'problem', type: 'textarea', label: '3. Nó giải quyết vấn đề gì?', placeholder: 'Mô tả pain point hoặc công việc đang bị chậm, rối, tốn công...', required: true, rows: 3, section: 'required', hint: 'Tập trung vào vấn đề thật ngoài đời thay vì giải pháp kỹ thuật.', example: 'Team nhỏ cần theo dõi công việc hằng ngày nhưng Jira quá nặng và mất thời gian cập nhật.' },
            { id: 'targetUsers', type: 'text', label: '4. Ai sẽ dùng sản phẩm này?', placeholder: 'Nhóm người dùng chính', required: true, section: 'required', hint: 'Nói rõ ai hưởng lợi trực tiếp từ app.', example: 'Developer cá nhân và team nhỏ 2-5 người' },
            { id: 'coreFeatures', type: 'textarea', label: '5. Những việc quan trọng nhất app phải làm được', placeholder: 'Liệt kê 3-5 capability cốt lõi cho phiên bản đầu', required: true, rows: 4, section: 'required', hint: 'Mô tả theo hành động của người dùng hoặc kết quả họ cần đạt.', example: '1. Tạo và cập nhật task\n2. Xem task theo board\n3. Lọc theo trạng thái\n4. Nhắc việc sắp tới hạn' },
            { id: 'successCriteria', type: 'textarea', label: '6. Khi nào bạn xem đây là phiên bản đạt yêu cầu?', placeholder: 'Các dấu hiệu hoàn thành hoặc kết quả phải thấy được', required: true, rows: 3, section: 'required', hint: 'Viết như checklist nghiệm thu ở góc nhìn non-coder.', example: 'Người dùng tạo task trong 1 phút, xem board mượt trên desktop, và không cần internet để dùng các chức năng chính.' },
            { id: 'mustPreserve', type: 'textarea', label: '7. Những gì phải giữ nguyên', placeholder: 'Logic, dữ liệu, route, integration, quy trình, câu chữ bắt buộc...', required: false, rows: 3, section: 'advanced', hint: 'Giúp builder biết ranh giới không được phá khi thực hiện.', example: 'Giữ nguyên webhook gửi báo cáo, format export CSV hiện tại, và tên gói dịch vụ đang công bố.' },
            { id: 'platforms', type: 'text', label: '8. App cần chạy ở đâu?', placeholder: 'Windows, macOS, Web browser, Android...', required: true, section: 'required', hint: 'Nói rõ nơi người dùng thực sự dùng sản phẩm.', example: 'Windows + macOS' },
            { id: 'dataNeeds', type: 'textarea', label: '9. App cần nhớ / xử lý loại dữ liệu nào?', placeholder: 'Thông tin người dùng, task, tệp đính kèm, báo cáo...', required: false, rows: 2, section: 'advanced', hint: 'Không cần nói database, chỉ cần mô tả loại dữ liệu và mức nhạy cảm.', example: 'Task, deadline, ghi chú nội bộ, người phụ trách, file đính kèm nhỏ' },
            { id: 'lookAndFeel', type: 'text', label: '10. Bạn muốn cảm giác giao diện ra sao?', placeholder: 'Mô tả phong cách mong muốn', required: false, section: 'advanced', hint: 'Nói bằng cảm giác hoặc mức độ ưu tiên: gọn, rõ, premium, data-heavy...', example: 'Tối giản, tập trung công việc, đọc nhanh, ít nhiễu' },
            { id: 'outOfScope', type: 'textarea', label: '11. Những gì chưa làm ở phiên bản này', placeholder: 'Giới hạn rõ để tránh làm quá scope', required: false, rows: 2, section: 'advanced', hint: 'Nêu các phần deliberately chưa làm để packet không overbuild.', example: 'Chưa cần multi-user, chưa cần mobile app riêng, chưa cần cloud sync' },
            { id: 'constraints', type: 'textarea', label: '12. Ràng buộc hoặc điều kiện đặc biệt', placeholder: 'Deadline, ngân sách, rule nội bộ, vận hành offline, quy định...', required: false, rows: 2, section: 'advanced', hint: 'Bất kỳ giới hạn nào ảnh hưởng cách builder triển khai.', example: 'Phải dùng được offline, rollout nội bộ trong 3 tuần, không yêu cầu cài thêm runtime phức tạp' },
        ],
        intentPattern: `INTENT:
Tôi muốn tạo một app brief đầy đủ nhưng vẫn theo chuẩn non-coder.

APP / PRODUCT NAME: [appName]
APP TYPE: [appType]

PROBLEM TO SOLVE:
[problem]

TARGET USERS:
[targetUsers]

CORE FEATURES:
[coreFeatures]

SUCCESS CRITERIA:
[successCriteria]

MUST PRESERVE:
[mustPreserve]

PLATFORMS:
[platforms]

DATA NEEDS:
[dataNeeds]

LOOK AND FEEL:
[lookAndFeel]

OUT OF SCOPE:
[outOfScope]

CONSTRAINTS:
[constraints]

OUTPUT REQUIREMENTS:
- Ask only for business intent, user outcomes, constraints, and preservation rules
- Do not ask the end user to choose frameworks, databases, or hidden technical patterns
- Translate this into a builder-ready governed packet
- Include acceptance criteria and handoff boundaries`,
        outputExpected: [
            'Product Brief',
            'Core Workflows',
            'Protected Constraints',
            'Builder Plan',
            'Acceptance Criteria',
            'Handoff Checklist'
        ],
        outputTemplate: `# Complete App Brief

## 1. Product Goal

## 2. Must-Have Workflows

## 3. Data And Constraints

## 4. Protected Boundaries

## 5. Builder Plan

## 6. Acceptance Criteria`,
    },
    {
        id: 'individual_skills_folder',
        name: '📂 Bộ Skill Templates (8)',
        icon: '📂',
        description: '8 templates riêng lẻ cho từng khâu: Requirements, Tech Stack, Architecture, Database, API, Desktop/CLI, Deployment.',
        category: 'development',
        difficulty: 'medium',
        fields: [],
        intentPattern: '',
        outputExpected: [],
        isFolder: true, // This is a folder, not a template
    },
    {
        id: 'app_requirements_spec',
        name: 'Spec Yêu cầu Ứng dụng',
        icon: '📑',
        description: 'Thu thập requirements cho app mới, định nghĩa scope và success criteria',
        category: 'development',
        difficulty: 'medium',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'VD: TaskFlow - Quản lý công việc', required: true, section: 'required', hint: 'Tên app kèm mô tả ngắn', example: 'TaskFlow — Quản lý công việc cá nhân' },
            { id: 'appType', type: 'select', label: 'App Type', options: ['Desktop', 'CLI Tool', 'Mobile', 'Web App', 'API Service'], required: true, section: 'required', hint: 'Loại ứng dụng cần build' },
            { id: 'problem', type: 'textarea', label: 'Problem Statement', placeholder: 'Vấn đề cần giải quyết là gì?', required: true, rows: 3, section: 'required', hint: 'Mô tả vấn đề thực tế mà app giải quyết', example: 'Developer cần tool nhẹ, chạy local để track tasks hàng ngày mà không cần Jira' },
            { id: 'targetUsers', type: 'text', label: 'Target Users', placeholder: 'Ai sẽ dùng app này?', required: true, section: 'required', hint: 'Mô tả người dùng chính', example: 'Developer cá nhân, thích terminal-based tools' },
            { id: 'coreFeatures', type: 'textarea', label: 'Core Features (3-5)', placeholder: '1. Feature 1\n2. Feature 2\n3. Feature 3', required: true, rows: 4, section: 'required', hint: 'Liệt kê 3-5 tính năng quan trọng nhất cho v1', example: '1. CRUD tasks\n2. Priority levels\n3. Due date + reminder\n4. Search/filter\n5. Export to Markdown' },
            { id: 'outOfScope', type: 'textarea', label: 'Out of Scope', placeholder: 'Những gì KHÔNG làm trong phiên bản này', required: true, rows: 3, section: 'required', hint: 'Định nghĩa rõ những gì không làm để kiểm soát scope', example: 'Không cần multi-user, không cần mobile app, không cần cloud sync' },
            { id: 'successCriteria', type: 'textarea', label: 'Success Criteria', placeholder: 'Khi nào app được coi là done?', required: true, rows: 2, section: 'required', hint: 'Tiêu chí cụ thể, đo lường được', example: 'User có thể CRUD tasks, filter theo status, và app chạy stable trên Windows/macOS' },
            { id: 'platform', type: 'text', label: 'Platform', placeholder: 'Windows, macOS, Linux...', required: false, section: 'advanced', hint: 'Hệ điều hành cần hỗ trợ', example: 'Windows + macOS' },
            { id: 'dataStorage', type: 'select', label: 'Data Storage', options: ['None', 'Local File', 'Local Database (SQLite)', 'Cloud'], required: false, section: 'advanced', hint: 'Cách lưu trữ dữ liệu của app' },
        ],
        intentPattern: `INTENT:
Tôi muốn tạo App Requirements Specification cho [appName].

APP INFO:
- Type: [appType]
- Target Users: [targetUsers]
- Platform: [platform]
- Data Storage: [dataStorage]

PROBLEM STATEMENT:
[problem]

CORE FEATURES:
[coreFeatures]

OUT OF SCOPE:
[outOfScope]

SUCCESS CRITERIA:
[successCriteria]

OUTPUT REQUIREMENTS:
- Problem statement rõ ràng
- Core features có priority
- Out of scope được định nghĩa
- Success criteria có thể measure được`,
        outputExpected: ['Requirements Document', 'Feature List with Priority', 'Scope Definition', 'Success Metrics'],
    },
    {
        id: 'architecture_design',
        name: 'Thiết kế Kiến trúc',
        icon: '🧱',
        description: 'Thiết kế kiến trúc hệ thống với component diagram',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required', hint: 'Tên app cần thiết kế kiến trúc', example: 'TaskFlow' },
            { id: 'techStack', type: 'text', label: 'Tech Stack', placeholder: 'VD: Tauri + Vue 3 + SQLite', required: true, section: 'required', hint: 'Tech stack đã chọn cho app', example: 'Tauri + React + SQLite' },
            { id: 'coreFeatures', type: 'textarea', label: 'Core Features', placeholder: 'Các tính năng chính', required: true, rows: 3, section: 'required', hint: 'Danh sách features để AI thiết kế components phù hợp', example: '1. Task CRUD\n2. Kanban board\n3. Search & filter\n4. Keyboard shortcuts' },
            { id: 'appType', type: 'select', label: 'Architecture Type', options: ['Desktop App', 'CLI Tool', 'Web SPA', 'API Backend', 'Full-stack'], required: true, section: 'required', hint: 'Loại kiến trúc quyết định các layers và patterns' },
            { id: 'dataFlow', type: 'textarea', label: 'Data Flow', placeholder: 'VD: User → UI → Backend → DB → UI', required: true, rows: 2, section: 'required', hint: 'Luồng dữ liệu chính của app', example: 'User → React UI → Tauri commands → SQLite → React UI' },
            { id: 'integrations', type: 'text', label: 'External Integrations', placeholder: 'VD: REST API, File system (hoặc None)', required: false, section: 'advanced', hint: 'Hệ thống bên ngoài cần kết nối', example: 'File system (export Markdown), GitHub API (import issues)' },
            { id: 'stateComplexity', type: 'select', label: 'State Complexity', options: ['Simple', 'Medium', 'Complex'], required: false, section: 'advanced', hint: 'Simple = useState, Medium = Zustand, Complex = Redux/MobX' },
        ],
        intentPattern: `INTENT:
Thiết kế architecture cho [appName].

TECH STACK: [techStack]
APP TYPE: [appType]

CORE FEATURES:
[coreFeatures]

DATA FLOW:
[dataFlow]

EXTERNAL INTEGRATIONS: [integrations]
STATE COMPLEXITY: [stateComplexity]

OUTPUT REQUIREMENTS:
- System diagram (ASCII art)
- Component breakdown với responsibilities
- Directory structure
- Data flow documentation
- Key design decisions`,
        outputExpected: ['System Diagram', 'Component Breakdown', 'Directory Structure', 'Data Flow', 'Design Decisions'],
    },
    {
        id: 'api_design',
        name: 'Spec Thiết kế API',
        icon: '🔌',
        description: 'Biến nhu cầu trao đổi dữ liệu thành integration handoff packet để non-coder mô tả hợp đồng vận hành mà không phải tự chọn kiểu API.',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: '1. Hệ thống / integration này tên gì?', placeholder: 'Tên app, service, hoặc kết nối cần mô tả', required: true, section: 'required', hint: 'Dùng tên mà team đang gọi hằng ngày.', example: 'TaskFlow integration với CRM' },
            { id: 'whoUsesIt', type: 'text', label: '2. Ai dùng hoặc phụ thuộc vào integration này?', placeholder: 'Team, vai trò, hoặc hệ thống liên quan', required: true, section: 'required', hint: 'Nói rõ ai là bên gửi/nhận chính.', example: 'Sales ops, CRM nội bộ, website lead form' },
            { id: 'jobsToSupport', type: 'textarea', label: '3. Integration này phải hỗ trợ những việc gì?', placeholder: 'Liệt kê các hành động hay tình huống chính', required: true, rows: 3, section: 'required', hint: 'Mô tả theo nhu cầu vận hành hoặc business workflow.', example: 'Tạo lead mới từ website, cập nhật trạng thái lead, đồng bộ thông tin tư vấn, đánh dấu lead đủ điều kiện.' },
            { id: 'informationExchanged', type: 'textarea', label: '4. Những thông tin nào cần đi qua lại?', placeholder: 'Tên, email, trạng thái, đơn hàng, tài liệu...', required: true, rows: 3, section: 'required', hint: 'Chỉ cần mô tả dữ liệu theo nghĩa business.', example: 'Tên khách, email, số điện thoại, nhu cầu tư vấn, nguồn lead, trạng thái xử lý, ghi chú sales.' },
            { id: 'rulesApprovals', type: 'textarea', label: '5. Có rule quyền hạn / phê duyệt nào không?', placeholder: 'Ai được gửi, ai được sửa, khi nào cần duyệt, điều gì bị cấm...', required: false, rows: 3, section: 'advanced', hint: 'Giúp packet có guardrails về permission và approval.', example: 'Chỉ sales manager được sửa trạng thái “Won”, lead trùng phải được merge thay vì tạo mới, export cần log.' },
            { id: 'mustPreserve', type: 'textarea', label: '6. Những gì phải giữ nguyên', placeholder: 'Logic hiện có, integration cũ, field bắt buộc, compliance rule...', required: false, rows: 2, section: 'advanced', hint: 'Những ranh giới builder không được phá.', example: 'Giữ nguyên CRM lead ID hiện tại, không làm hỏng webhook cũ, không bỏ log phê duyệt.' },
        ],
        intentPattern: `INTENT:
Tôi muốn biến nhu cầu trao đổi dữ liệu này thành integration handoff packet.

SYSTEM / INTEGRATION NAME: [appName]
WHO USES IT: [whoUsesIt]
JOBS TO SUPPORT: [jobsToSupport]
INFORMATION EXCHANGED: [informationExchanged]
RULES / APPROVALS: [rulesApprovals]
MUST PRESERVE: [mustPreserve]

OUTPUT REQUIREMENTS:
- Describe the contract in plain-language business terms first
- Translate it into builder-ready operations and payload sketches without asking the user to choose API style
- Include permissions / approval notes and preservation constraints
- End with an acceptance checklist a non-coder can validate`,
        outputExpected: ['Integration Overview', 'Operations & data flow', 'Payload sketch', 'Permission / approval notes', 'Acceptance Checklist'],
        outputTemplate: `# Integration Handoff Packet

## 1. Purpose Of The Integration

## 2. Operations The Builder Must Support

## 3. Information That Moves

## 4. Permissions And Safeguards

## 5. Protected Constraints

## 6. Acceptance Checklist`,
    },
    {
        id: 'cli_tool_spec',
        name: 'Spec Công cụ CLI',
        icon: '⌨️',
        description: 'Spec cho command-line tool: commands, arguments, options',
        category: 'development',
        difficulty: 'advanced',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'toolName', type: 'text', label: 'Tool Name', placeholder: 'VD: taskflow hoặc tf', required: true, section: 'required', hint: 'Tên lệnh ngắn gọn, dễ gõ', example: 'tf (TaskFlow CLI)' },
            { id: 'purpose', type: 'textarea', label: 'Purpose', placeholder: 'Tool này làm gì?', required: true, rows: 2, section: 'required', hint: 'Mô tả ngắn về mục đích của CLI tool', example: 'Quản lý tasks từ terminal: thêm, xem, hoàn thành, xóa tasks nhanh chóng' },
            { id: 'commands', type: 'textarea', label: 'Commands', placeholder: 'VD: add, list, done, delete, search, config', required: true, rows: 2, section: 'required', hint: 'Danh sách commands chính', example: 'add, list, done, delete, search, config, export' },
            { id: 'targetUsers', type: 'text', label: 'Target Users', placeholder: 'Ai sẽ dùng?', required: true, section: 'required', hint: 'Ai là người dùng chính?', example: 'Developer thích làm việc từ terminal' },
            { id: 'language', type: 'select', label: 'Language', options: ['Python (Click)', 'Rust (Clap)', 'Go (Cobra)', 'Node.js (Commander)', 'Other'], required: true, section: 'required', hint: 'Ngôn ngữ và CLI framework' },
            { id: 'configLocation', type: 'text', label: 'Config Location', placeholder: 'VD: ~/.toolname/config.yaml', required: false, section: 'advanced', hint: 'Nơi lưu file cấu hình', example: '~/.tf/config.yaml' },
            { id: 'dataStorage', type: 'text', label: 'Data Storage', placeholder: 'VD: ~/.toolname/data.json', required: false, section: 'advanced', hint: 'Nơi lưu dữ liệu của tool', example: '~/.tf/tasks.db (SQLite)' },
            { id: 'outputFormats', type: 'text', label: 'Output Formats', placeholder: 'VD: text, json, table', required: false, section: 'advanced', hint: 'Định dạng output hỗ trợ', example: 'text (default), json, table, csv' },
        ],
        intentPattern: `INTENT:
Tạo CLI Tool Specification cho [toolName].

PURPOSE:
[purpose]

TARGET USERS: [targetUsers]
LANGUAGE: [language]

COMMANDS:
[commands]

CONFIG: [configLocation]
DATA: [dataStorage]
OUTPUT FORMATS: [outputFormats]

OUTPUT REQUIREMENTS:
- All commands documented
- Arguments và options clear
- Exit codes defined
- Config file format
- Examples cho mỗi command`,
        outputExpected: ['Command Documentation', 'Arguments/Options', 'Exit Codes', 'Config Format', 'Usage Examples'],
    },
    // === Vibe Workflow Templates (linked to new skills) ===
    {
        id: 'vibe_workflow_folder',
        name: '🎨 Vibe Workflow (4)',
        icon: '🎨',
        description: 'Vibe-to-Spec, Logic Mapping, Debug, Packaging — tools for non-coders to go from idea to delivered app.',
        category: 'development',
        difficulty: 'easy',
        fields: [],
        intentPattern: '',
        outputExpected: [],
        isFolder: true,
    },
    {
        id: 'vibe_to_spec',
        name: 'Vibe-to-Spec Translator',
        icon: '✨',
        description: 'Convert vague vibe descriptions ("make it feel luxurious") into a concrete Vibe Mapping Table AI can use.',
        category: 'development',
        difficulty: 'easy',
        parentFolder: 'vibe_workflow_folder',
        fields: [
            { id: 'vibeDescription', type: 'textarea', label: 'Vibe Description', placeholder: 'e.g. "I want it to look luxurious and professional like a banking app"', required: true, rows: 3, section: 'required', hint: 'Describe the feeling or style you want — in plain language', example: '"Clean and minimal like Notion, not too flashy"' },
            { id: 'appType', type: 'select', label: 'App Type', options: ['Personal Finance Manager', 'Task Manager', 'Reporting Dashboard', 'Inventory Tracker', 'Other'], required: true, section: 'required', hint: 'What kind of app is this? Helps AI map the vibe to the right context' },
            { id: 'targetUsers', type: 'text', label: 'Target Users', placeholder: 'e.g. Office workers, homemakers, students', required: false, section: 'advanced', hint: 'Who will use this app?', example: 'Non-technical office workers, age 25–45' },
        ],
        intentPattern: `INTENT:
Apply CVF Skill: Vibe-to-Spec Translator

APP TYPE: [appType]
TARGET USERS: [targetUsers]

VIBE DESCRIPTION:
[vibeDescription]

OUTPUT REQUIREMENTS:
- Generate a Vibe Mapping Table with 3 columns: Your Keyword | I understand it as... | I will build...
- NO technical jargon (no CSS, hex codes, padding) in the table
- End with a confirmation question: "Do you approve this Vibe Mapping?"
- Do NOT start designing or coding until User types "Approve Vibe"`,
        outputExpected: ['Vibe Mapping Table (3 columns)', 'Plain-language descriptions', 'User confirmation step'],
    },
    {
        id: 'vibe_logic_mapping',
        name: 'Vibe Logic Mapping',
        icon: '🗂️',
        description: 'Biến vibe đã duyệt thành style brief builder-ready mà không buộc non-coder phải khai tech stack hay tự dịch sang spec kỹ thuật.',
        category: 'development',
        difficulty: 'easy',
        parentFolder: 'vibe_workflow_folder',
        fields: [
            { id: 'approvedVibe', type: 'textarea', label: 'Approved Vibe Keywords', placeholder: 'e.g. "Professional, Minimal, Fast"', required: true, rows: 2, section: 'required', hint: 'Copy the approved vibe keywords from the Vibe-to-Spec step' },
            { id: 'productSurface', type: 'text', label: 'Product Surface', placeholder: 'e.g. Dashboard, settings page, onboarding flow', required: true, section: 'required', hint: 'Name the surface the builder is styling, in plain language.', example: 'Internal analytics dashboard' },
            { id: 'userOutcome', type: 'text', label: 'User Outcome', placeholder: 'What should users feel or accomplish on this surface?', required: true, section: 'required', hint: 'Give the main user outcome this vibe needs to support.', example: 'Users should scan key metrics quickly and feel confident taking action.' },
            { id: 'mustPreserve', type: 'textarea', label: 'Must Preserve', placeholder: 'Logic, existing flows, approval boundaries, or brand rules that cannot be broken', required: false, rows: 2, section: 'advanced', hint: 'This keeps the style translation grounded and safe.', example: 'Keep existing navigation labels, approval wording, and metric definitions unchanged.' },
        ],
        intentPattern: `INTENT:
Apply CVF Skill: Vibe Logic Mapping

PRODUCT SURFACE: [productSurface]
USER OUTCOME: [userOutcome]

APPROVED VIBE:
[approvedVibe]

MUST PRESERVE:
[mustPreserve]

OUTPUT REQUIREMENTS:
- Generate a builder-ready style brief instead of asking for stack details
- For each vibe keyword, explain what it means for layout, component tone, and visual rhythm
- Include rationale in plain language and list preserved constraints
- No contradictions between different vibes`,
        outputExpected: ['Style brief by vibe keyword', 'Layout / component implications', 'Rationale', 'Preservation notes'],
        outputTemplate: `# Vibe Implementation Brief

## 1. Approved Vibe

## 2. Layout Implications

## 3. Component Implications

## 4. Preservation Notes

## 5. Builder Handoff`,
    },
    {
        id: 'project_init_checklist',
        name: 'Project Init Checklist',
        icon: '✅',
        description: 'Run this before starting any new CVF project. Ensures all foundations are ready before AI begins working.',
        category: 'development',
        difficulty: 'easy',
        parentFolder: 'vibe_workflow_folder',
        fields: [
            { id: 'projectName', type: 'text', label: 'Project Name', placeholder: 'e.g. FinanceTracker', required: true, section: 'required', hint: 'Short, memorable name for the project', example: 'FinanceTracker' },
            { id: 'projectDescription', type: 'text', label: 'One-line Description', placeholder: 'e.g. Offline household expense tracker', required: true, section: 'required', hint: 'What the app does — in one sentence', example: 'Offline expense tracker for homemakers' },
            { id: 'operatingSystem', type: 'select', label: 'Operating System', options: ['Windows 10/11', 'macOS', 'Linux', 'Multiple'], required: true, section: 'required', hint: 'Which OS is the user working on?' },
            { id: 'pythonInstalled', type: 'select', label: 'Python Installed?', options: ['Yes', 'No', 'Not sure'], required: true, section: 'required', hint: 'Python is required for most CVF Streamlit projects' },
        ],
        intentPattern: `INTENT:
Apply CVF Skill: Project Init Checklist

PROJECT: [projectName]
DESCRIPTION: [projectDescription]
OS: [operatingSystem]
PYTHON: [pythonInstalled]

OUTPUT REQUIREMENTS:
- Generate an 8-item checklist covering: Foundation, The Idea, CVF Compliance
- Show current tally: "[X]/8 items ✅"
- Ask User to confirm with "Checklist Pass" before proceeding
- After confirmation: create governance/PROJECT_PROGRESS.md tracking file
- Do NOT discuss project content until checklist passes ≥ 80%`,
        outputExpected: ['8-item Init Checklist', 'Tally display', 'Confirmation prompt', 'PROJECT_PROGRESS.md'],
    },
    {
        id: 'non_coder_debug',
        name: 'Non-Coder Debug',
        icon: '🔍',
        description: 'App crashed or showing wrong results? Describe what you see — AI diagnoses and fixes in plain language.',
        category: 'development',
        difficulty: 'easy',
        parentFolder: 'vibe_workflow_folder',
        fields: [
            { id: 'errorSymptom', type: 'textarea', label: 'What did you see?', placeholder: 'e.g. "Clicking Save makes the app go blank"', required: true, rows: 3, section: 'required', hint: 'Describe exactly what happened — no technical words needed', example: '"The app shows a strange number like 1e+06 instead of 1,000,000"' },
            { id: 'stepsToReproduce', type: 'textarea', label: 'How to trigger it again', placeholder: 'e.g. "Enter a negative number then click Save"', required: true, rows: 2, section: 'required', hint: 'Step-by-step to make the error happen again', example: 'Enter an amount over 1 million then click Calculate' },
            { id: 'whenItStarted', type: 'text', label: 'When did it start?', placeholder: 'e.g. "After I added the Notes column"', required: false, section: 'advanced', hint: 'Any recent change that might have caused this', example: 'After adding a new input field yesterday' },
        ],
        intentPattern: `INTENT:
Apply CVF Skill: Non-Coder Debug

STEPS TO REPRODUCE:
[stepsToReproduce]

WHEN IT STARTED: [whenItStarted]

ERROR SYMPTOM:
[errorSymptom]

OUTPUT REQUIREMENTS:
- Generate a plain-language Bug Report with sections: Symptom | Root Cause | How I Fixed It | Test Results
- NO technical jargon, error codes, or stack traces visible to user
- Root cause must use real-world analogies
- Include at least 3 test cases in Test Results
- Do NOT blame the hardware or environment before checking code logic`,
        outputExpected: ['Plain-language Bug Report', 'Root cause in plain terms', 'At least 3 test case results'],
    },
    {
        id: 'auto_documentation',
        name: 'Auto Documentation',
        icon: '📖',
        description: 'Generate a USER_GUIDE.md for your app — plain-language Quick Start, feature list, and common error fixes.',
        category: 'development',
        difficulty: 'easy',
        parentFolder: 'vibe_workflow_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'e.g. FinanceTracker — Household Expense Manager', required: true, section: 'required', hint: 'Full name of the app for the document title', example: 'StockCheck — Supermarket Inventory' },
            { id: 'howToLaunch', type: 'text', label: 'How to Launch', placeholder: 'e.g. Double-click START.bat / streamlit run app.py', required: true, section: 'required', hint: 'The exact command or file the user clicks to start the app', example: 'Double-click START.bat in the folder' },
            { id: 'coreFeatures', type: 'textarea', label: 'Core Features (3–5)', placeholder: '1. Record expenses\n2. View monthly report\n3. Export to Excel', required: true, rows: 4, section: 'required', hint: 'The features users will use most often', example: '1. Scan barcode\n2. View stock levels\n3. Receive goods\n4. Generate report' },
            { id: 'operatingSystem', type: 'select', label: 'Operating System', options: ['Windows 10/11', 'macOS', 'Linux', 'Cross-platform'], required: true, section: 'required', hint: 'The OS the app runs on — affects installation instructions' },
            { id: 'commonErrors', type: 'textarea', label: 'Common Errors (optional)', placeholder: 'e.g. App won\'t open, data not saving', required: false, rows: 2, section: 'advanced', hint: 'Known issues users might encounter', example: 'Blank screen on first launch, export button not working' },
        ],
        intentPattern: `INTENT:
Apply CVF Skill: Auto Documentation

APP NAME: [appName]
HOW TO LAUNCH: [howToLaunch]
OPERATING SYSTEM: [operatingSystem]

CORE FEATURES:
[coreFeatures]

KNOWN ERRORS:
[commonErrors]

OUTPUT REQUIREMENTS:
- Create a complete USER_GUIDE.md file (not just describe it — actually generate the full content)
- Sections: Quick Start (≤ 5 steps) | Core Features | Common Issues & Fixes | Support Contact
- Quick Start must NOT require terminal, conda, virtualenv, or Docker
- Include at least 3 common errors with plain-language fixes
- No unexplained technical jargon`,
        outputExpected: ['Full USER_GUIDE.md content', 'Quick Start ≤ 5 steps', '3+ Common Errors with fixes'],
    },
];
