import { Template } from '@/types';

export const productTemplates: Template[] = [
    {
        id: 'product_design_wizard',
        name: '🎨 Thiết kế Sản phẩm',
        icon: '🎨',
        description: 'Multi-step wizard tạo Product Design Spec với governed packet và live path để đối soát',
        category: 'product',
        difficulty: 'medium',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Product Design Spec', 'User Personas', 'User Flows', 'Design Brief'],
    },
    {
        id: 'ab_test_review',
        name: 'Review A/B Test',
        icon: '🧪',
        description: 'Đánh giá A/B test design và results',
        category: 'product',
        difficulty: 'advanced',
        fields: [
            { id: 'hypothesis', type: 'textarea', label: 'Hypothesis', placeholder: 'Giả thuyết: Nếu... thì...', required: true, rows: 2, section: 'required', hint: 'Viết theo format: "Nếu [thay đổi X] thì [metric Y] sẽ [tăng/giảm]"', example: 'Nếu đổi CTA từ "Sign up" sang "Start free trial" thì conversion rate sẽ tăng 15%' },
            { id: 'metric', type: 'text', label: 'Primary Metric', placeholder: 'VD: Conversion rate, CTR...', required: true, section: 'required', hint: 'Metric chính dùng để đo lường kết quả', example: 'Sign-up conversion rate' },
            { id: 'variants', type: 'textarea', label: 'Variants', placeholder: 'Control vs Treatment descriptions', required: true, rows: 3, section: 'required', hint: 'Mô tả rõ sự khác biệt giữa Control và Treatment', example: 'Control: Nút xanh "Sign up", text nhỏ\nTreatment: Nút cam "Start free trial", text lớn hơn + testimonial' },
            { id: 'sampleSize', type: 'text', label: 'Sample Size', placeholder: 'Số users mỗi variant', required: false, section: 'advanced', hint: 'Để trống nếu muốn AI tính sample size cần thiết', example: '5,000 users mỗi variant (từ Google Optimize)' },
            { id: 'results', type: 'textarea', label: 'Results (nếu có)', placeholder: 'Kết quả từ tool', required: false, rows: 3, section: 'advanced', hint: 'Dán kết quả từ A/B testing tool nếu đã chạy xong', example: 'Control: 2.1% CR, Treatment: 2.8% CR, p-value: 0.03, 14 ngày' },
        ],
        intentPattern: `INTENT:
Tôi muốn review A/B test.

HYPOTHESIS: [hypothesis]
PRIMARY METRIC: [metric]
VARIANTS: [variants]
SAMPLE SIZE: [sampleSize]
RESULTS: [results]

SUCCESS CRITERIA:
- Hypothesis quality check
- Statistical validity
- Sample size adequacy
- Result interpretation`,
        outputExpected: ['Test Design Assessment', 'Statistical Analysis', 'Winner Recommendation', 'Next Steps'],
    },
    {
        id: 'accessibility_audit',
        name: 'Kiểm tra Accessibility',
        icon: '♿',
        description: 'Kiểm tra WCAG compliance',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'url', type: 'text', label: 'Page URL', placeholder: 'https://example.com/page', required: true, section: 'required', hint: 'URL trang cần kiểm tra accessibility', example: 'https://shopx.vn/checkout' },
            { id: 'level', type: 'select', label: 'WCAG Level', options: ['A', 'AA', 'AAA'], default: 'AA', required: true, section: 'required', hint: 'AA là mức tiêu chuẩn phổ biến nhất, AAA là cao nhất' },
            { id: 'audience', type: 'text', label: 'Target Users', placeholder: 'Đối tượng sử dụng có disability nào?', required: false, section: 'advanced', hint: 'Loại disability cần ưu tiên hỗ trợ', example: 'Người khiếm thị sử dụng screen reader, người cao tuổi' },
            { id: 'issues', type: 'textarea', label: 'Known Issues', placeholder: 'Các issues đã biết', required: false, rows: 3, section: 'advanced', hint: 'Liệt kê issues accessibility đã biết (nếu có)', example: 'Form checkout không navigate được bằng keyboard, contrast thấp ở footer' },
        ],
        intentPattern: `INTENT:
Tôi muốn audit accessibility cho page [url].

TARGET WCAG LEVEL: [level]
TARGET USERS: [audience]
KNOWN ISSUES: [issues]

SUCCESS CRITERIA:
- Visual accessibility check
- Keyboard navigation
- Screen reader compatibility
- Color contrast analysis`,
        outputExpected: ['WCAG Compliance Score', 'Critical Issues', 'Recommended Fixes', 'Testing Checklist'],
    },
    {
        id: 'user_flow_analysis',
        name: 'Phân tích User Flow',
        icon: '🔄',
        description: 'Phân tích và tối ưu user journeys',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'flow', type: 'textarea', label: 'User Flow', placeholder: 'Mô tả các steps từ entry đến goal', required: true, rows: 6, section: 'required', hint: 'Mô tả từng bước user đi qua, từ lúc vào trang đến khi hoàn thành', example: '1. Landing page → 2. Click "Xem giá" → 3. Pricing page → 4. Chọn gói → 5. Form đăng ký → 6. Thanh toán → 7. Confirmation' },
            { id: 'goal', type: 'text', label: 'Conversion Goal', placeholder: 'VD: Complete purchase', required: true, section: 'required', hint: 'Hành động cuối cùng mà user cần thực hiện', example: 'Hoàn thành thanh toán và nhận mã đơn hàng' },
            { id: 'dropoff', type: 'textarea', label: 'Drop-off Points', placeholder: 'Các điểm users rời khỏi flow', required: false, rows: 3, section: 'advanced', hint: 'Các bước mà users thường bỏ dở', example: 'Bước 5 (form đăng ký): 45% drop-off\nBước 6 (thanh toán): 20% drop-off' },
            { id: 'metrics', type: 'text', label: 'Current Metrics', placeholder: 'Conversion rates at each step', required: false, section: 'advanced', hint: 'Tỷ lệ conversion tại mỗi bước (nếu có)', example: 'Overall CR: 1.8%, Step 3→4: 65%, Step 5→6: 55%' },
        ],
        intentPattern: `INTENT:
Tôi muốn phân tích user flow.

FLOW DESCRIPTION:
[flow]

CONVERSION GOAL: [goal]
DROP-OFF POINTS: [dropoff]
CURRENT METRICS: [metrics]

SUCCESS CRITERIA:
- Friction point identification
- Drop-off analysis
- Optimization recommendations
- Quick wins vs long-term fixes`,
        outputExpected: ['Flow Diagram', 'Friction Analysis', 'Drop-off Causes', 'Optimization Roadmap'],
    },
    {
        id: 'ux_heuristic_evaluation',
        name: 'Đánh giá UX Heuristic',
        icon: '📋',
        description: 'Đánh giá UX theo Nielsen\'s 10 Heuristics',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'product', type: 'text', label: 'Product/Feature', placeholder: 'Tên sản phẩm hoặc feature', required: true, section: 'required', hint: 'Tên sản phẩm hoặc feature cần đánh giá UX', example: 'TaskFlow — Dashboard quản lý dự án' },
            { id: 'description', type: 'textarea', label: 'Description', placeholder: 'Mô tả product/feature', required: true, rows: 4, section: 'required', hint: 'Mô tả chức năng chính và cách user tương tác', example: 'Dashboard hiển thị tất cả projects, tasks, và deadlines. Có drag-and-drop, filter, và search.' },
            { id: 'url', type: 'text', label: 'URL (nếu có)', placeholder: 'Link đến product', required: false, section: 'advanced', hint: 'URL để AI có thể tham khảo giao diện' },
            { id: 'focus', type: 'text', label: 'Focus Areas', placeholder: 'Các areas cần focus', required: false, section: 'advanced', hint: 'Tập trung vào những heuristic nào?', example: 'Error prevention, User control, Consistency' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá UX heuristics cho [product].

DESCRIPTION: [description]
URL: [url]
FOCUS AREAS: [focus]

SUCCESS CRITERIA:
- Đánh giá theo Nielsen's 10 Heuristics
- Severity rating cho issues
- Priority recommendations
- Before/After examples`,
        outputExpected: ['Heuristic Scores', 'Issue Severity Matrix', 'Top Issues', 'Recommendations'],
    },
    {
        id: 'feature_prioritization',
        name: 'Ưu tiên Tính năng',
        icon: '⚖️',
        description: 'RICE/ICE framework cho feature prioritization',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'features', type: 'textarea', label: 'Feature List', placeholder: 'Danh sách features cần prioritize', required: true, rows: 6, section: 'required', hint: 'Mỗi feature 1 dòng, kèm mô tả ngắn', example: '1. Real-time collaboration\n2. Mobile app\n3. Gantt chart view\n4. Custom fields\n5. Automations' },
            { id: 'goal', type: 'text', label: 'Product Goal', placeholder: 'Mục tiêu product hiện tại', required: true, section: 'required', hint: 'Mục tiêu chính của product trong quý này', example: 'Tăng DAU từ 5K lên 15K và giảm churn xuống dưới 5%' },
            { id: 'constraints', type: 'text', label: 'Constraints', placeholder: 'Budget, timeline, resources...', required: false, section: 'advanced', hint: 'Giới hạn về nguồn lực và thời gian', example: '2 engineers, 1 designer, deadline Q2 2026' },
            { id: 'framework', type: 'select', label: 'Framework', options: ['RICE', 'ICE', 'MoSCoW', 'Kano'], default: 'RICE', required: false, section: 'advanced', hint: 'RICE = Reach, Impact, Confidence, Effort. ICE = Impact, Confidence, Ease' },
        ],
        intentPattern: `INTENT:
Tôi muốn prioritize features bằng [framework] framework.

FEATURES:
[features]

PRODUCT GOAL: [goal]
CONSTRAINTS: [constraints]

SUCCESS CRITERIA:
- Score mỗi feature theo framework
- Prioritized list
- Quick wins identification
- Roadmap suggestion`,
        outputExpected: ['Scoring Matrix', 'Prioritized List', 'Quick Wins', 'Roadmap Recommendation'],
    },
    {
        id: 'user_persona',
        name: 'Xây dựng User Persona',
        icon: '👤',
        description: 'Tạo user personas dựa trên data',
        category: 'product',
        difficulty: 'easy',
        fields: [
            { id: 'product', type: 'text', label: 'Product/Service', placeholder: 'Tên sản phẩm/dịch vụ', required: true, section: 'required', hint: 'Sản phẩm/dịch vụ cần tạo persona', example: 'TaskFlow — ứng dụng quản lý dự án' },
            { id: 'data', type: 'textarea', label: 'User Data', placeholder: 'Demographics, behaviors, interviews...', required: true, rows: 6, section: 'required', hint: 'Dữ liệu về users: từ survey, analytics, phỏng vấn...', example: '70% users là PM/team lead, 60% dùng mobile, pain point chính: track deadlines và assign tasks' },
            { id: 'segments', type: 'text', label: 'User Segments', placeholder: 'Các segments đã biết', required: false, section: 'advanced', hint: 'Các nhóm users đã xác định (nếu có)', example: 'Freelancers, Small teams (2-10), Mid-size teams (10-50)' },
            { id: 'goals', type: 'text', label: 'Business Goals', placeholder: 'Mục tiêu kinh doanh', required: false, section: 'advanced', hint: 'Mục tiêu kinh doanh liên quan đến personas', example: 'Tăng adoption từ small teams, giảm churn segment freelancer' },
        ],
        intentPattern: `INTENT:
Tôi muốn tạo user personas cho [product].

USER DATA:
[data]

SEGMENTS: [segments]
BUSINESS GOALS: [goals]

SUCCESS CRITERIA:
- 2-4 distinct personas
- Demographics, goals, pain points
- Jobs to be done
- Decision criteria`,
        outputExpected: ['Persona Profiles', 'User Journey Maps', 'Pain Points', 'Opportunities'],
    },
    {
        id: 'error_handling_ux',
        name: 'UX Xử lý Lỗi',
        icon: '🛑',
        description: 'Cải thiện cách handle errors',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'errors', type: 'textarea', label: 'Current Error Messages', placeholder: 'Paste các error messages hiện tại', required: true, rows: 6, section: 'required', hint: 'Dán các error messages người dùng đang thấy', example: '"Error 500: Internal Server Error"\n"Something went wrong. Try again later."\n"Invalid input"' },
            { id: 'context', type: 'text', label: 'Error Context', placeholder: 'Form, checkout, login, etc.', required: true, section: 'required', hint: 'Màn hình/chức năng nơi error xuất hiện', example: 'Form checkout và trang tạo tài khoản' },
            { id: 'audience', type: 'text', label: 'User Type', placeholder: 'Technical users hay end users?', required: false, section: 'advanced', hint: 'Mức độ kỹ thuật của người dùng', example: 'End users không có kiến thức kỹ thuật' },
            { id: 'tone', type: 'select', label: 'Brand Tone', options: ['Friendly', 'Professional', 'Technical', 'Playful'], default: 'Friendly', required: false, section: 'advanced', hint: 'Phong cách ngôn ngữ phù hợp với brand' },
        ],
        intentPattern: `INTENT:
Tôi muốn cải thiện error handling UX cho context [context].

CURRENT ERRORS:
[errors]

USER TYPE: [audience]
BRAND TONE: [tone]

SUCCESS CRITERIA:
- Error message clarity
- User guidance
- Recovery options
- Consistent tone`,
        outputExpected: ['Error Analysis', 'Rewritten Messages', 'UX Improvements', 'Best Practices'],
    },
    {
        id: 'onboarding_review',
        name: 'Review Onboarding',
        icon: '🎓',
        description: 'Tối ưu first-time user experience',
        category: 'product',
        difficulty: 'medium',
        fields: [
            { id: 'product', type: 'text', label: 'Product', placeholder: 'Tên sản phẩm', required: true, section: 'required', hint: 'Tên sản phẩm cần đánh giá onboarding', example: 'TaskFlow' },
            { id: 'flow', type: 'textarea', label: 'Current Onboarding Flow', placeholder: 'Mô tả các steps hiện tại', required: true, rows: 6, section: 'required', hint: 'Liệt kê từng bước onboarding từ lúc đăng ký đến khi user thấy giá trị', example: '1. Sign up form (email + password)\n2. Email verification\n3. Chọn workspace name\n4. Invite team members\n5. Tạo project đầu tiên\n6. Tour hướng dẫn' },
            { id: 'ttv', type: 'text', label: 'Time to Value', placeholder: 'Hiện tại bao lâu để user thấy value?', required: false, section: 'advanced', hint: 'Thời gian trung bình từ đăng ký đến "aha moment"', example: '~15 phút, aha moment = tạo task đầu tiên và assign cho team' },
            { id: 'dropoff', type: 'text', label: 'Drop-off Rate', placeholder: '% users drop-off during onboarding', required: false, section: 'advanced', hint: 'Tỷ lệ users bỏ cuộc giữa chừng onboarding', example: '40% drop-off ở bước 4 (invite team)' },
        ],
        intentPattern: `INTENT:
Tôi muốn review onboarding experience cho [product].

CURRENT FLOW:
[flow]

TIME TO VALUE: [ttv]
DROP-OFF RATE: [dropoff]

SUCCESS CRITERIA:
- Identify friction points
- Reduce time to value
- Progressive disclosure
- Personalization opportunities`,
        outputExpected: ['Onboarding Assessment', 'Friction Points', 'Optimization Recommendations', 'Metrics to Track'],
    },
    {
        id: 'grandma_ux_test',
        name: 'Grandma UX Test',
        icon: '👵',
        description: 'Non-technical UX review — can a 60-year-old grandma use your app? Tests simplicity, clarity, and button design.',
        category: 'product',
        difficulty: 'easy',
        fields: [
            { id: 'appDescription', type: 'textarea', label: 'App Description', placeholder: 'e.g. "Household expense tracker for homemakers"', required: true, rows: 2, section: 'required', hint: 'What does the app do and who is it for?', example: 'Medication reminder app for elderly users — reminds them daily and tracks compliance' },
            { id: 'coreFeatures', type: 'textarea', label: 'Core Features to Test', placeholder: 'e.g. "Record expense, view monthly report"', required: true, rows: 3, section: 'required', hint: 'The most common tasks users perform — these will be tested for clarity', example: 'Set a reminder, mark medication as taken, view history' },
            { id: 'uiDescription', type: 'textarea', label: 'UI Description (optional)', placeholder: 'e.g. "Left sidebar, data table in center, big green button on top"', required: false, rows: 2, section: 'advanced', hint: 'Brief description of the current interface layout', example: 'Top navigation with icons, medication list below, large colored buttons for each action' },
        ],
        intentPattern: `INTENT:
Apply CVF Skill: Grandma UX Test

APP: [appDescription]
UI: [uiDescription]

CORE FEATURES TO TEST:
[coreFeatures]

OUTPUT REQUIREMENTS:
- Generate a Grandma UX Test Report with exactly 3 Quick Start steps (each ≤ 2 sentences)
- Evaluate each UX rule: button size/color, language clarity, status feedback
- Classify issues as: Must Fix | Should Fix | Optional
- Include an overall UX Score out of 10
- NO technical jargon (no "component", "state", "render", "API")
- Ask: "Could a 60-year-old grandma do this on her own?"`,
        outputExpected: ['3-Step Quick Start', 'UX Evaluation by category', 'Prioritized Issue List', 'UX Score /10'],
    },
];
