// CVF v2.0 — Type Definitions
// Non-Coder Safety Runtime Layer

// ─── Modes ───────────────────────────────────────────────────────────────────

export type SafetyMode = 'SAFE' | 'BALANCED' | 'CREATIVE'

/**
 * Kernel policy object passed to v1.8 LifecycleController at INTENT phase.
 * Generated by ModeMapper from SafetyMode selection.
 */
export interface KernelPolicy {
    mode: SafetyMode
    /** Max files allowed per execution */
    maxFiles: number
    /** Max lines changed per execution */
    maxLines: number
    /** R-level ceiling — executions exceeding this are auto-rejected */
    riskCeiling: 'R0' | 'R1' | 'R2' | 'R3'
    /** Always confirm before any file change */
    confirmAll: boolean
    /** Confirm if risk is at R2 level */
    confirmR2: boolean
    /** Confirm if risk is at R3 level */
    confirmR3: boolean
}

// ─── Intent ───────────────────────────────────────────────────────────────────

export type IntentAction =
    | 'read'
    | 'analyze'
    | 'refactor'
    | 'fix'
    | 'add-feature'
    | 'restructure'
    | 'delete'
    | 'unknown'

export type EstimatedRiskLevel = 'R0' | 'R1' | 'R2' | 'R3'

export interface ParsedIntent {
    /** Raw user input */
    rawInput: string
    /** Classified action type */
    action: IntentAction
    /** Estimated scope */
    scope: 'single-file' | 'module' | 'cross-module' | 'global'
    /** Estimated risk before kernel assessment */
    estimatedRisk: EstimatedRiskLevel
    /** Confidence 0–1 that classification is correct */
    confidence: number
    /** Human-readable explanation of the parsed intent */
    summary: string
}

// ─── Confirmation ─────────────────────────────────────────────────────────────

export interface ConfirmationRequest {
    executionId: string
    mode: SafetyMode
    currentRisk: 'R0' | 'R1' | 'R2' | 'R3' | 'R3+'
    action: string
    requiresConfirm: boolean
    reason: string
}
