/**
 * CVF Governance Adapter for VS Code / External AI Agents
 * ========================================================
 * Generates governance context that can be injected into AI agents
 * operating in IDE environments (Windsurf, Cursor, VS Code Copilot).
 *
 * Usage:
 *   import { generateGovernancePrompt } from './vscode-governance-adapter';
 *   const prompt = generateGovernancePrompt({ phase: 'BUILD', riskLevel: 'R1' });
 *   // Inject `prompt` as system context for the AI agent
 *
 * @module governance/adapters/vscode-governance-adapter
 */

import type { CanonicalCVFPhase, CVFPhase, CVFRiskLevel, CVFRole } from 'cvf-guard-contract';
import {
  PHASE_ROLE_MATRIX,
  PHASE_DESCRIPTIONS,
  RESTRICTED_ACTIONS,
  DEFAULT_MUTATION_BUDGETS,
  RISK_DESCRIPTIONS,
  PROTECTED_PATHS,
} from 'cvf-guard-contract';

// ─── Types ────────────────────────────────────────────────────────────

export interface GovernanceSession {
  phase: CVFPhase;
  riskLevel: CVFRiskLevel;
  role: CVFRole;
  projectName?: string;
  mutationBudget?: number;
  mutationCount?: number;
}

function normalizePhaseAlias(phase: CVFPhase): CanonicalCVFPhase {
  return phase === 'DISCOVERY' ? 'INTAKE' : phase;
}

// ─── Prompt Generator ─────────────────────────────────────────────────

/**
 * Generates a governance context prompt for injection into AI agent system prompts.
 * This is the PRIMARY mechanism for enforcing CVF governance in IDE contexts.
 */
export function generateGovernancePrompt(session: GovernanceSession): string {
  const budget = session.mutationBudget ?? DEFAULT_MUTATION_BUDGETS[session.riskLevel];
  const count = session.mutationCount ?? 0;
  const normalizedPhase = normalizePhaseAlias(session.phase);
  const allowedRoles = PHASE_ROLE_MATRIX[normalizedPhase];
  const restricted = RESTRICTED_ACTIONS[session.role];
  const phaseDesc = PHASE_DESCRIPTIONS[normalizedPhase];
  const riskDesc = RISK_DESCRIPTIONS[session.riskLevel];

  return `
## CVF GOVERNANCE CONTEXT — MANDATORY RULES

You are operating under the **Controlled Vibe Framework (CVF)** governance protocol.
These rules are NON-NEGOTIABLE. Violating them will invalidate your work.

### Current Session State
- **Phase:** ${normalizedPhase} — ${phaseDesc}
- **Risk Level:** ${session.riskLevel} — ${riskDesc}
- **Your Role:** ${session.role}
- **Mutation Budget:** ${count}/${budget} changes used
${session.projectName ? `- **Project:** ${session.projectName}` : ''}

### Phase Rules
The CVF process follows 5 phases: INTAKE → DESIGN → BUILD → REVIEW → FREEZE.
You are currently in **${normalizedPhase}**. Only these roles can operate in this phase: ${allowedRoles.join(', ')}.
${session.role === 'AI_AGENT' && !allowedRoles.includes('AI_AGENT')
    ? `⚠️ WARNING: As AI_AGENT, you are NOT authorized for ${normalizedPhase} phase. AI_AGENT activity is limited to controlled builder-class phases.`
    : ''}

### Risk Rules
${session.riskLevel === 'R0' ? '✅ Risk is R0 (Safe). You may proceed freely within your role boundaries.' : ''}
${session.riskLevel === 'R1' ? '⚠️ Risk is R1 (Low). Proceed with attention, log your actions.' : ''}
${session.riskLevel === 'R2' ? '🔶 Risk is R2 (Elevated). You MUST present a plan and get human approval before executing.' : ''}
${session.riskLevel === 'R3' ? '🔴 Risk is R3 (Critical). You CANNOT proceed autonomously. Request human sign-off for every action.' : ''}

### Restricted Actions
${restricted.length > 0
    ? `As ${session.role}, you CANNOT perform: ${restricted.join(', ')}. Delegate these to the appropriate role.`
    : `As ${session.role}, you have no action restrictions.`}

### Protected Paths — DO NOT MODIFY
${PROTECTED_PATHS.map(p => `- \`${p}\``).join('\n')}

### Mutation Budget
You have used ${count} of ${budget} allowed mutations.
${count > budget * 0.8
    ? `⚠️ You are at ${Math.round((count / budget) * 100)}% of your budget. Prioritize remaining changes carefully.`
    : `You have ${budget - count} mutations remaining.`}

### Audit Requirements
- Every action MUST have a unique requestId for traceability.
${session.role === 'AI_AGENT' ? '- You MUST include your agentId with every action.\n' : ''}
${session.riskLevel === 'R2' || session.riskLevel === 'R3' ? '- You MUST include a traceHash for verification.\n' : ''}

---
*This governance context is generated by the CVF Guard Contract. Compliance is mandatory.*
`.trim();
}

/**
 * Generates a minimal JSON governance payload for programmatic use.
 */
export function generateGovernancePayload(session: GovernanceSession): Record<string, unknown> {
  const budget = session.mutationBudget ?? DEFAULT_MUTATION_BUDGETS[session.riskLevel];
  const normalizedPhase = normalizePhaseAlias(session.phase);
  return {
    cvf_version: '2.0',
    phase: normalizedPhase,
    phase_description: PHASE_DESCRIPTIONS[normalizedPhase],
    risk_level: session.riskLevel,
    risk_description: RISK_DESCRIPTIONS[session.riskLevel],
    role: session.role,
    allowed_roles_in_phase: PHASE_ROLE_MATRIX[normalizedPhase],
    restricted_actions: RESTRICTED_ACTIONS[session.role],
    mutation_budget: budget,
    mutation_count: session.mutationCount ?? 0,
    protected_paths: PROTECTED_PATHS,
    channel: 'ide',
  };
}
