import { Template } from '@/types';

export const templates: Template[] = [
    // BUSINESS TEMPLATES
    // Business Strategy Wizard - Multi-step
    {
        id: 'business_strategy_wizard',
        name: '📈 Business Strategy Wizard',
        icon: '📈',
        description: 'Multi-step wizard tạo Strategic Decision Document qua 4 bước. Context → Options → SWOT/Risk → Review',
        category: 'business',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Strategy Document', 'SWOT Analysis', 'Options Matrix', 'Recommendation'],
    },
    {
        id: 'strategy_analysis',
        name: 'Strategy Analysis',
        icon: '📊',
        description: 'Phân tích chiến lược kinh doanh, so sánh các phương án',
        category: 'business',
        fields: [
            { id: 'topic', type: 'text', label: 'Chủ đề chiến lược', placeholder: 'VD: Mở rộng thị trường miền Trung', required: true, section: 'required' },
            { id: 'context', type: 'textarea', label: 'Bối cảnh', placeholder: 'Mô tả ngành, quy mô, thị trường...', required: true, rows: 4, section: 'required' },
            { id: 'options', type: 'textarea', label: 'Các phương án (nếu có)', placeholder: 'Liệt kê các options đang cân nhắc', required: false, rows: 3, section: 'advanced' },
            { id: 'constraints', type: 'text', label: 'Ràng buộc', placeholder: 'Budget, timeline, resources...', required: false, section: 'advanced' },
            { id: 'priority', type: 'select', label: 'Ưu tiên', options: ['Growth', 'Stability', 'Cost Optimization'], default: 'Growth', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn phân tích chiến lược [topic].

CONTEXT:
[context]

OPTIONS:
[options]

CONSTRAINTS:
[constraints]

PRIORITY: [priority]

SUCCESS CRITERIA:
- Phân tích rõ ưu/nhược điểm
- Xác định rủi ro chính  
- Đưa ra khuyến nghị có căn cứ`,
        outputExpected: ['Executive Summary', 'Assumptions & Missing Data', 'SWOT Analysis', 'Options Comparison', 'Risk Assessment', 'Recommendations', 'Success Criteria Check', 'Next Actions'],
        outputTemplate: `# Strategy Analysis Output

## Executive Summary
- Goal:
- Primary recommendation:
- Rationale:

## Assumptions & Missing Data
- Missing inputs:
- Assumptions used:

## SWOT Analysis
| Strengths | Weaknesses | Opportunities | Threats |
| --- | --- | --- | --- |
| ... | ... | ... | ... |

## Options Comparison
| Option | Pros | Cons | Cost/Impact | Risks | Notes |
| --- | --- | --- | --- | --- | --- |
| Option A |  |  |  |  |  |
| Option B |  |  |  |  |  |

## Risk Assessment
- Top risks (ranked):
1. ...
2. ...
- Mitigations:
- ...

## Recommendations
- Recommendation 1:
- Recommendation 2 (if needed):

## Success Criteria Check
- [ ] Phân tích rõ ưu/nhược điểm
- [ ] Xác định rủi ro chính
- [ ] Đưa ra khuyến nghị có căn cứ

## Next Actions
- Questions for user:
- Data to confirm:
`,
        sampleOutput: `# Strategy Analysis: Market Expansion

## Executive Summary
Strategic analysis suggests that expanding into the Central region is a viable growth path (Score: 8.5/10), provided that logistics challenges can be mitigated.

## ROI Analysis
- **Estimated Cost:** $500,000
- **Projected Revenue (Year 1):** $1,200,000
- **Break-even Point:** Month 9

## Strategic Options
| Option | Pros | Cons |
|--------|------|------|
| **Direct Expansion** | High control, higher margins | High capex, slow rollout |
| **Partnership** | Fast market entry, low risk | Lower margins, brand dilution risk |

## Recommendation
Proceed with **Partnership** model for the first 12 months to test market demand before committing significant Capex.
`,
    },
    {
        id: 'risk_assessment',
        name: 'Risk Assessment',
        icon: '⚠️',
        description: 'Đánh giá rủi ro với kế hoạch giảm thiểu',
        category: 'business',
        fields: [
            { id: 'subject', type: 'text', label: 'Chủ đề đánh giá', placeholder: 'VD: Dự án cloud migration', required: true, section: 'required' },
            { id: 'description', type: 'textarea', label: 'Mô tả chi tiết', placeholder: 'Mô tả dự án/quyết định cần đánh giá', required: true, rows: 4, section: 'required' },
            { id: 'stakeholders', type: 'text', label: 'Stakeholders', placeholder: 'Ai bị ảnh hưởng?', required: false, section: 'advanced' },
            { id: 'timeline', type: 'text', label: 'Timeline', placeholder: 'Thời gian thực hiện', required: false, section: 'advanced' },
            { id: 'tolerance', type: 'select', label: 'Risk Tolerance', options: ['Low', 'Medium', 'High'], default: 'Medium', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá rủi ro của [subject].

DESCRIPTION:
[description]

STAKEHOLDERS: [stakeholders]
TIMELINE: [timeline]
RISK TOLERANCE: [tolerance]

SUCCESS CRITERIA:
- Xác định 5-10 rủi ro chính
- Phân loại theo mức độ (High/Medium/Low)
- Đề xuất mitigation cho mỗi rủi ro`,
        outputExpected: ['Risk Matrix', 'Top Risks', 'Mitigation Plans', 'Contingency Plans', 'Recommendations'],
    },
    {
        id: 'competitor_review',
        name: 'Competitor Review',
        icon: '🔍',
        description: 'Phân tích đối thủ cạnh tranh',
        category: 'business',
        fields: [
            { id: 'company', type: 'text', label: 'Công ty của bạn', placeholder: 'Tên và mô tả ngắn', required: true, section: 'required' },
            { id: 'competitors', type: 'textarea', label: 'Đối thủ chính', placeholder: 'Liệt kê các đối thủ cần phân tích', required: true, rows: 3, section: 'required' },
            { id: 'industry', type: 'text', label: 'Ngành', placeholder: 'VD: E-commerce, Fintech...', required: true, section: 'required' },
            { id: 'criteria', type: 'textarea', label: 'Tiêu chí so sánh', placeholder: 'Giá, chất lượng, marketing, tech...', required: false, rows: 2, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn phân tích đối thủ cạnh tranh trong ngành [industry].

MY COMPANY: [company]

COMPETITORS:
[competitors]

COMPARISON CRITERIA:
[criteria]

SUCCESS CRITERIA:
- Ma trận so sánh các đối thủ
- Điểm mạnh/yếu từng đối thủ
- Cơ hội khác biệt hóa`,
        outputExpected: ['Competitor Matrix', 'SWOT per Competitor', 'Differentiation Opportunities', 'Market Positioning'],
    },

    // TECHNICAL TEMPLATES
    // System Design Wizard - Multi-step
    {
        id: 'system_design_wizard',
        name: '🔧 System Design Wizard',
        icon: '🔧',
        description: 'Multi-step wizard tạo System Design Document qua 5 bước. Requirements → Estimations → Design → Deep Dive → Review',
        category: 'technical',
        fields: [],
        intentPattern: '',
        outputExpected: ['System Design Doc', 'Architecture Diagram', 'API Design', 'Scaling Strategy'],
    },
    {
        id: 'code_review',
        name: 'Code Review',
        icon: '💻',
        description: 'Review code về chất lượng, security, performance',
        category: 'technical',
        fields: [
            { id: 'code', type: 'textarea', label: 'Code cần review', placeholder: 'Paste code vào đây...', required: true, rows: 10, section: 'required' },
            { id: 'language', type: 'text', label: 'Ngôn ngữ', placeholder: 'VD: Python, TypeScript...', required: true, section: 'required' },
            { id: 'context', type: 'textarea', label: 'Context', placeholder: 'Code này làm gì? Thuộc module nào?', required: false, rows: 2, section: 'advanced' },
            { id: 'focus', type: 'multiselect', label: 'Focus areas', options: ['Security', 'Performance', 'Readability', 'Best Practices'], required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn review code [language].

CODE:
\`\`\`[language]
[code]
\`\`\`

CONTEXT: [context]
FOCUS AREAS: [focus]

SUCCESS CRITERIA:
- Phát hiện bugs và issues
- Đề xuất improvements
- Đánh giá overall quality`,
        outputExpected: ['Issues Found', 'Security Concerns', 'Performance Issues', 'Suggestions', 'Overall Rating'],
    },
    {
        id: 'architecture_review',
        name: 'Architecture Review',
        icon: '🏗️',
        description: 'Review kiến trúc hệ thống',
        category: 'technical',
        fields: [
            { id: 'system', type: 'text', label: 'Tên hệ thống', placeholder: 'VD: Payment Service', required: true, section: 'required' },
            { id: 'description', type: 'textarea', label: 'Mô tả kiến trúc', placeholder: 'Các components, data flow, integrations...', required: true, rows: 6, section: 'required' },
            { id: 'requirements', type: 'textarea', label: 'Requirements', placeholder: 'NFRs: scalability, availability...', required: false, rows: 3, section: 'advanced' },
            { id: 'concerns', type: 'text', label: 'Điểm lo ngại', placeholder: 'Có gì cần focus?', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn review kiến trúc của [system].

ARCHITECTURE:
[description]

REQUIREMENTS:
[requirements]

CONCERNS: [concerns]

SUCCESS CRITERIA:
- Đánh giá design principles
- Phát hiện bottlenecks
- Đề xuất improvements`,
        outputExpected: ['Architecture Assessment', 'Strengths', 'Weaknesses', 'Bottlenecks', 'Recommendations'],
    },

    // CONTENT TEMPLATES
    // Content Strategy Wizard - Multi-step
    {
        id: 'content_strategy_wizard',
        name: '✍️ Content Strategy Wizard',
        icon: '✍️',
        description: 'Multi-step wizard tạo Content Strategy qua 5 bước. Brand → Audience → Pillars → Channels → Review',
        category: 'content',
        fields: [],
        intentPattern: '',
        outputExpected: ['Content Strategy', 'Editorial Calendar', 'Content Pillars', 'Channel Plan'],
    },
    {
        id: 'documentation',
        name: 'Documentation',
        icon: '📝',
        description: 'Tạo technical documentation',
        category: 'content',
        fields: [
            { id: 'subject', type: 'text', label: 'Chủ đề', placeholder: 'VD: API Authentication Guide', required: true, section: 'required' },
            { id: 'content', type: 'textarea', label: 'Nội dung cần document', placeholder: 'Mô tả feature/API/process...', required: true, rows: 6, section: 'required' },
            { id: 'audience', type: 'select', label: 'Đối tượng', options: ['Developers', 'End Users', 'Admins', 'All'], default: 'Developers', required: false, section: 'advanced' },
            { id: 'format', type: 'select', label: 'Format', options: ['Tutorial', 'Reference', 'How-to', 'Explanation'], default: 'Reference', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn tạo documentation cho [subject].

CONTENT:
[content]

AUDIENCE: [audience]
FORMAT: [format]

SUCCESS CRITERIA:
- Cấu trúc rõ ràng
- Có examples
- Dễ follow`,
        outputExpected: ['Overview', 'Prerequisites', 'Step-by-step Guide', 'Examples', 'Troubleshooting', 'FAQ'],
    },
    {
        id: 'email_template',
        name: 'Email Templates',
        icon: '📧',
        description: 'Tạo email chuyên nghiệp',
        category: 'content',
        fields: [
            { id: 'purpose', type: 'text', label: 'Mục đích email', placeholder: 'VD: Follow-up sau meeting', required: true, section: 'required' },
            { id: 'context', type: 'textarea', label: 'Context', placeholder: 'Tình huống cụ thể...', required: true, rows: 4, section: 'required' },
            { id: 'recipient', type: 'text', label: 'Người nhận', placeholder: 'VD: Khách hàng, đồng nghiệp...', required: false, section: 'advanced' },
            { id: 'tone', type: 'select', label: 'Tone', options: ['Formal', 'Professional', 'Friendly', 'Urgent'], default: 'Professional', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn soạn email [purpose].

CONTEXT:
[context]

RECIPIENT: [recipient]
TONE: [tone]

SUCCESS CRITERIA:
- Chuyên nghiệp
- Rõ ràng call-to-action
- Phù hợp context`,
        outputExpected: ['Subject Line', 'Opening', 'Body', 'Call to Action', 'Closing'],
    },

    // RESEARCH TEMPLATES
    // Research Project Wizard - Multi-step
    {
        id: 'research_project_wizard',
        name: '🔬 Research Project Wizard',
        icon: '🔬',
        description: 'Multi-step wizard tạo Research Proposal qua 4 bước. Question → Methodology → Resources → Review',
        category: 'research',
        fields: [],
        intentPattern: '',
        outputExpected: ['Research Proposal', 'Methodology', 'Literature Review Outline', 'Timeline'],
    },
    // Data Analysis Wizard - Multi-step
    {
        id: 'data_analysis_wizard',
        name: '📊 Data Analysis Wizard',
        icon: '📊',
        description: 'Multi-step wizard tạo Data Analysis Plan qua 5 bước. Problem → Understanding → Methodology → Deliverables → Review',
        category: 'research',
        fields: [],
        intentPattern: '',
        outputExpected: ['Analysis Plan', 'Data Profile', 'Methodology', 'Deliverables'],
    },
    {
        id: 'data_analysis',
        name: 'Data Analysis',
        icon: '📊',
        description: 'Phân tích dữ liệu và rút insights',
        category: 'research',
        fields: [
            { id: 'dataset', type: 'textarea', label: 'Mô tả dataset', placeholder: 'Loại data, sources, format...', required: true, rows: 4, section: 'required' },
            { id: 'questions', type: 'textarea', label: 'Câu hỏi nghiên cứu', placeholder: 'Bạn muốn tìm hiểu điều gì?', required: true, rows: 3, section: 'required' },
            { id: 'methods', type: 'text', label: 'Phương pháp', placeholder: 'VD: Regression, clustering...', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn phân tích dữ liệu.

DATASET:
[dataset]

RESEARCH QUESTIONS:
[questions]

METHODS: [methods]

SUCCESS CRITERIA:
- Insights rõ ràng
- Có supporting evidence
- Actionable recommendations`,
        outputExpected: ['Dataset Overview', 'Key Findings', 'Statistical Analysis', 'Visualizations', 'Insights', 'Recommendations'],
    },

    // MARKETING & SEO TEMPLATES (Phase 1)
    // Marketing Campaign Wizard - Multi-step
    {
        id: 'marketing_campaign_wizard',
        name: '📣 Marketing Campaign Wizard',
        icon: '📣',
        description: 'Multi-step wizard tạo Campaign Brief qua 5 bước. Goals → Audience → Channels → Content → Review',
        category: 'marketing',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Campaign Brief', 'Channel Strategy', 'Content Calendar', 'Ad Copy'],
    },
    {
        id: 'seo_audit',
        name: 'SEO Audit',
        icon: '🔍',
        description: 'Đánh giá website về Technical SEO, On-page, Off-page',
        category: 'marketing',
        fields: [
            { id: 'url', type: 'text', label: 'URL Website', placeholder: 'https://example.com', required: true, section: 'required' },
            { id: 'industry', type: 'text', label: 'Ngành/Lĩnh vực', placeholder: 'VD: E-commerce, SaaS, Blog...', required: true, section: 'required' },
            { id: 'keywords', type: 'textarea', label: 'Target Keywords', placeholder: 'Các từ khóa đang target', required: false, rows: 2, section: 'advanced' },
            { id: 'competitors', type: 'text', label: 'Đối thủ chính', placeholder: '2-3 website đối thủ', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn audit SEO cho website [url].

INDUSTRY: [industry]
TARGET KEYWORDS: [keywords]
COMPETITORS: [competitors]

SUCCESS CRITERIA:
- Đánh giá Technical SEO (SSL, speed, mobile)
- Đánh giá On-page SEO (title, meta, content)
- Đánh giá Off-page SEO (backlinks)
- Xác định priority issues`,
        outputExpected: ['Technical SEO Report', 'On-Page Analysis', 'Content Quality Score', 'Priority Issues', 'Action Plan'],
    },
    {
        id: 'copywriting_evaluation',
        name: 'Copywriting Evaluation',
        icon: '✍️',
        description: 'Đánh giá và cải thiện marketing copy',
        category: 'marketing',
        fields: [
            { id: 'copy', type: 'textarea', label: 'Copy Text', placeholder: 'Paste đoạn copy cần đánh giá...', required: true, rows: 6, section: 'required' },
            { id: 'type', type: 'select', label: 'Loại Copy', options: ['Headline', 'Ad', 'Email', 'Landing Page', 'Product Description'], default: 'Headline', required: true, section: 'required' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Đối tượng mục tiêu', required: true, section: 'required' },
            { id: 'cta', type: 'text', label: 'Mục tiêu CTA', placeholder: 'Mua hàng, đăng ký, tải app...', required: true, section: 'required' },
            { id: 'tone', type: 'select', label: 'Tone of Voice', options: ['Professional', 'Casual', 'Urgent', 'Friendly', 'Premium'], default: 'Professional', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá [type] copy.

COPY:
[copy]

TARGET AUDIENCE: [audience]
CTA GOAL: [cta]
TONE: [tone]

SUCCESS CRITERIA:
- Đánh giá clarity, benefits, emotional triggers
- Đánh giá CTA effectiveness
- Đề xuất cải thiện
- Viết lại phiên bản tối ưu`,
        outputExpected: ['Copy Score (/10)', 'Strengths', 'Issues', 'Rewritten Version', 'A/B Test Ideas'],
    },
    {
        id: 'landing_page_cro',
        name: 'Landing Page CRO',
        icon: '🎯',
        description: 'Tối ưu conversion rate cho landing pages',
        category: 'marketing',
        fields: [
            { id: 'url', type: 'text', label: 'Landing Page URL', placeholder: 'https://example.com/landing', required: true, section: 'required' },
            { id: 'goal', type: 'select', label: 'Mục tiêu conversion', options: ['Sign up', 'Purchase', 'Download', 'Contact', 'Free Trial'], default: 'Sign up', required: true, section: 'required' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Đối tượng mục tiêu', required: true, section: 'required' },
            { id: 'traffic', type: 'select', label: 'Traffic Source', options: ['Paid Ads', 'Organic', 'Email', 'Social', 'Mixed'], default: 'Mixed', required: false, section: 'advanced' },
            { id: 'currentCR', type: 'text', label: 'Current Conversion Rate', placeholder: 'VD: 2.5%', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn tối ưu conversion rate cho landing page [url].

CONVERSION GOAL: [goal]
TARGET AUDIENCE: [audience]
TRAFFIC SOURCE: [traffic]
CURRENT CR: [currentCR]

SUCCESS CRITERIA:
- Đánh giá above the fold elements
- Xác định friction points
- Priority quick wins
- Đề xuất A/B tests`,
        outputExpected: ['CRO Score (/100)', 'Above the Fold Analysis', 'Friction Points', 'Quick Wins', 'A/B Test Suggestions'],
    },
    {
        id: 'pricing_strategy',
        name: 'Pricing Strategy Review',
        icon: '💰',
        description: 'Đánh giá và tối ưu pricing strategy',
        category: 'marketing',
        fields: [
            { id: 'product', type: 'text', label: 'Sản phẩm/Dịch vụ', placeholder: 'Mô tả offering', required: true, section: 'required' },
            { id: 'currentPrice', type: 'text', label: 'Giá hiện tại', placeholder: 'Pricing structure hiện tại', required: true, section: 'required' },
            { id: 'model', type: 'select', label: 'Pricing Model', options: ['One-time', 'Subscription', 'Tiered', 'Freemium', 'Usage-based'], default: 'Subscription', required: true, section: 'required' },
            { id: 'target', type: 'select', label: 'Target Customer', options: ['B2B Enterprise', 'B2B SMB', 'B2C Premium', 'B2C Mass'], default: 'B2B SMB', required: true, section: 'required' },
            { id: 'competitors', type: 'text', label: 'Giá đối thủ', placeholder: 'Pricing của competitors', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá pricing strategy cho [product].

CURRENT PRICING: [currentPrice]
MODEL: [model]
TARGET: [target]
COMPETITOR PRICES: [competitors]

SUCCESS CRITERIA:
- Value-based pricing analysis
- Competitive positioning
- Pricing psychology
- Đề xuất tối ưu`,
        outputExpected: ['Pricing Assessment', 'Value Analysis', 'Competitive Position', 'Optimization Opportunities', 'Recommended Structure'],
    },
    {
        id: 'content_quality',
        name: 'Content Quality Checklist',
        icon: '📄',
        description: 'Đánh giá chất lượng content với E-E-A-T',
        category: 'marketing',
        fields: [
            { id: 'content', type: 'textarea', label: 'Content URL/Text', placeholder: 'Link hoặc paste nội dung', required: true, rows: 4, section: 'required' },
            { id: 'type', type: 'select', label: 'Content Type', options: ['Blog', 'Guide', 'Landing page', 'Product page', 'How-to'], default: 'Blog', required: true, section: 'required' },
            { id: 'keyword', type: 'text', label: 'Target Keyword', placeholder: 'Từ khóa chính muốn rank', required: true, section: 'required' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Đối tượng đọc content', required: true, section: 'required' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá chất lượng [type] content.

CONTENT:
[content]

TARGET KEYWORD: [keyword]
AUDIENCE: [audience]

SUCCESS CRITERIA:
- E-E-A-T assessment
- SEO optimization check
- Readability score
- Gap analysis vs competitors`,
        outputExpected: ['Content Score (/10)', 'SEO Analysis', 'Readability Report', 'E-E-A-T Assessment', 'Improvement Recommendations'],
    },
    {
        id: 'email_campaign',
        name: 'Email Campaign Review',
        icon: '📧',
        description: 'Đánh giá email marketing campaigns',
        category: 'marketing',
        fields: [
            { id: 'email', type: 'textarea', label: 'Email Content', placeholder: 'Paste full email (subject + body)', required: true, rows: 8, section: 'required' },
            { id: 'type', type: 'select', label: 'Email Type', options: ['Newsletter', 'Promotional', 'Transactional', 'Nurture', 'Re-engagement'], default: 'Promotional', required: true, section: 'required' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Segment này là ai?', required: true, section: 'required' },
            { id: 'goal', type: 'select', label: 'Campaign Goal', options: ['CTR', 'Sales', 'Engagement', 'Re-engagement'], default: 'CTR', required: true, section: 'required' },
        ],
        intentPattern: `INTENT:
Tôi muốn review [type] email campaign.

EMAIL:
[email]

AUDIENCE: [audience]
GOAL: [goal]

SUCCESS CRITERIA:
- Subject line effectiveness
- Body content quality
- CTA clarity
- Mobile-friendliness`,
        outputExpected: ['Email Score (/10)', 'Subject Line Analysis', 'Content Review', 'Deliverability Check', 'Rewritten Version'],
    },
    {
        id: 'social_ad_review',
        name: 'Social Media Ad Review',
        icon: '📱',
        description: 'Tối ưu ads trên Facebook, Instagram, TikTok',
        category: 'marketing',
        fields: [
            { id: 'creative', type: 'textarea', label: 'Ad Creative', placeholder: 'Mô tả image/video hoặc link', required: true, rows: 3, section: 'required' },
            { id: 'copy', type: 'textarea', label: 'Ad Copy', placeholder: 'Headline + Primary text + CTA', required: true, rows: 4, section: 'required' },
            { id: 'platform', type: 'select', label: 'Platform', options: ['Facebook', 'Instagram', 'TikTok', 'LinkedIn', 'YouTube'], default: 'Facebook', required: true, section: 'required' },
            { id: 'objective', type: 'select', label: 'Campaign Objective', options: ['Traffic', 'Conversions', 'Leads', 'Awareness', 'Engagement'], default: 'Conversions', required: true, section: 'required' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Demographics, interests, behaviors', required: true, section: 'required' },
        ],
        intentPattern: `INTENT:
Tôi muốn review [platform] ad cho mục tiêu [objective].

CREATIVE:
[creative]

AD COPY:
[copy]

AUDIENCE: [audience]

SUCCESS CRITERIA:
- Creative effectiveness (thumb-stopping)
- Copy quality (hook, benefits, CTA)
- Platform optimization
- Predicted performance`,
        outputExpected: ['Ad Score (/10)', 'Creative Analysis', 'Copy Review', 'Platform Optimization', 'A/B Test Ideas', 'Rewritten Ad'],
    },
    {
        id: 'brand_voice',
        name: 'Brand Voice Consistency',
        icon: '🎙️',
        description: 'Đảm bảo brand voice nhất quán',
        category: 'marketing',
        fields: [
            { id: 'brand', type: 'text', label: 'Brand Name', placeholder: 'Tên thương hiệu', required: true, section: 'required' },
            { id: 'industry', type: 'text', label: 'Industry', placeholder: 'Ngành nghề', required: true, section: 'required' },
            { id: 'audience', type: 'text', label: 'Target Audience', placeholder: 'Customer persona chính', required: true, section: 'required' },
            { id: 'samples', type: 'textarea', label: 'Sample Content', placeholder: '3-5 samples từ các channels khác nhau', required: true, rows: 6, section: 'required' },
            { id: 'values', type: 'text', label: 'Brand Values', placeholder: 'Core values của brand', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá brand voice consistency cho [brand].

INDUSTRY: [industry]
TARGET AUDIENCE: [audience]
BRAND VALUES: [values]

SAMPLE CONTENT:
[samples]

SUCCESS CRITERIA:
- Voice attributes assessment
- Cross-channel consistency
- Tone appropriateness
- Improvement recommendations`,
        outputExpected: ['Voice Audit', 'Consistency Score (/10)', 'Voice Attributes', 'Tone Matrix', 'Language Guidelines'],
    },

    // PRODUCT & UX TEMPLATES (Phase 2)
    // Product Design Wizard - Multi-step
    {
        id: 'product_design_wizard',
        name: '🎨 Product Design Wizard',
        icon: '🎨',
        description: 'Multi-step wizard tạo Product Design Spec qua 6 bước. Problem → User → Solution → UX → Visual → Review',
        category: 'product',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Product Design Spec', 'User Personas', 'User Flows', 'Design Brief'],
    },
    {
        id: 'ab_test_review',
        name: 'A/B Test Review',
        icon: '🧪',
        description: 'Đánh giá A/B test design và results',
        category: 'product',
        fields: [
            { id: 'hypothesis', type: 'textarea', label: 'Hypothesis', placeholder: 'Giả thuyết: Nếu... thì...', required: true, rows: 2, section: 'required' },
            { id: 'metric', type: 'text', label: 'Primary Metric', placeholder: 'VD: Conversion rate, CTR...', required: true, section: 'required' },
            { id: 'variants', type: 'textarea', label: 'Variants', placeholder: 'Control vs Treatment descriptions', required: true, rows: 3, section: 'required' },
            { id: 'sampleSize', type: 'text', label: 'Sample Size', placeholder: 'Số users mỗi variant', required: false, section: 'advanced' },
            { id: 'results', type: 'textarea', label: 'Results (nếu có)', placeholder: 'Kết quả từ tool', required: false, rows: 3, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn review A/B test.

HYPOTHESIS: [hypothesis]
PRIMARY METRIC: [metric]
VARIANTS: [variants]
SAMPLE SIZE: [sampleSize]
RESULTS: [results]

SUCCESS CRITERIA:
- Hypothesis quality check
- Statistical validity
- Sample size adequacy
- Result interpretation`,
        outputExpected: ['Test Design Assessment', 'Statistical Analysis', 'Winner Recommendation', 'Next Steps'],
    },
    {
        id: 'accessibility_audit',
        name: 'Accessibility Audit',
        icon: '♿',
        description: 'Kiểm tra WCAG compliance',
        category: 'product',
        fields: [
            { id: 'url', type: 'text', label: 'Page URL', placeholder: 'https://example.com/page', required: true, section: 'required' },
            { id: 'level', type: 'select', label: 'WCAG Level', options: ['A', 'AA', 'AAA'], default: 'AA', required: true, section: 'required' },
            { id: 'audience', type: 'text', label: 'Target Users', placeholder: 'Đối tượng sử dụng có disability nào?', required: false, section: 'advanced' },
            { id: 'issues', type: 'textarea', label: 'Known Issues', placeholder: 'Các issues đã biết', required: false, rows: 3, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn audit accessibility cho page [url].

TARGET WCAG LEVEL: [level]
TARGET USERS: [audience]
KNOWN ISSUES: [issues]

SUCCESS CRITERIA:
- Visual accessibility check
- Keyboard navigation
- Screen reader compatibility
- Color contrast analysis`,
        outputExpected: ['WCAG Compliance Score', 'Critical Issues', 'Recommended Fixes', 'Testing Checklist'],
    },
    {
        id: 'user_flow_analysis',
        name: 'User Flow Analysis',
        icon: '🔄',
        description: 'Phân tích và tối ưu user journeys',
        category: 'product',
        fields: [
            { id: 'flow', type: 'textarea', label: 'User Flow', placeholder: 'Mô tả các steps từ entry đến goal', required: true, rows: 6, section: 'required' },
            { id: 'goal', type: 'text', label: 'Conversion Goal', placeholder: 'VD: Complete purchase', required: true, section: 'required' },
            { id: 'dropoff', type: 'textarea', label: 'Drop-off Points', placeholder: 'Các điểm users rời khỏi flow', required: false, rows: 3, section: 'advanced' },
            { id: 'metrics', type: 'text', label: 'Current Metrics', placeholder: 'Conversion rates at each step', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn phân tích user flow.

FLOW DESCRIPTION:
[flow]

CONVERSION GOAL: [goal]
DROP-OFF POINTS: [dropoff]
CURRENT METRICS: [metrics]

SUCCESS CRITERIA:
- Friction point identification
- Drop-off analysis
- Optimization recommendations
- Quick wins vs long-term fixes`,
        outputExpected: ['Flow Diagram', 'Friction Analysis', 'Drop-off Causes', 'Optimization Roadmap'],
    },
    {
        id: 'ux_heuristic_evaluation',
        name: 'UX Heuristic Evaluation',
        icon: '📋',
        description: 'Đánh giá UX theo Nielsen\'s 10 Heuristics',
        category: 'product',
        fields: [
            { id: 'product', type: 'text', label: 'Product/Feature', placeholder: 'Tên sản phẩm hoặc feature', required: true, section: 'required' },
            { id: 'description', type: 'textarea', label: 'Description', placeholder: 'Mô tả product/feature', required: true, rows: 4, section: 'required' },
            { id: 'url', type: 'text', label: 'URL (nếu có)', placeholder: 'Link đến product', required: false, section: 'advanced' },
            { id: 'focus', type: 'text', label: 'Focus Areas', placeholder: 'Các areas cần focus', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn đánh giá UX heuristics cho [product].

DESCRIPTION: [description]
URL: [url]
FOCUS AREAS: [focus]

SUCCESS CRITERIA:
- Đánh giá theo Nielsen's 10 Heuristics
- Severity rating cho issues
- Priority recommendations
- Before/After examples`,
        outputExpected: ['Heuristic Scores', 'Issue Severity Matrix', 'Top Issues', 'Recommendations'],
    },
    {
        id: 'feature_prioritization',
        name: 'Feature Prioritization',
        icon: '🎯',
        description: 'RICE/ICE framework cho feature prioritization',
        category: 'product',
        fields: [
            { id: 'features', type: 'textarea', label: 'Feature List', placeholder: 'Danh sách features cần prioritize', required: true, rows: 6, section: 'required' },
            { id: 'goal', type: 'text', label: 'Product Goal', placeholder: 'Mục tiêu product hiện tại', required: true, section: 'required' },
            { id: 'constraints', type: 'text', label: 'Constraints', placeholder: 'Budget, timeline, resources...', required: false, section: 'advanced' },
            { id: 'framework', type: 'select', label: 'Framework', options: ['RICE', 'ICE', 'MoSCoW', 'Kano'], default: 'RICE', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn prioritize features bằng [framework] framework.

FEATURES:
[features]

PRODUCT GOAL: [goal]
CONSTRAINTS: [constraints]

SUCCESS CRITERIA:
- Score mỗi feature theo framework
- Prioritized list
- Quick wins identification
- Roadmap suggestion`,
        outputExpected: ['Scoring Matrix', 'Prioritized List', 'Quick Wins', 'Roadmap Recommendation'],
    },
    {
        id: 'user_persona',
        name: 'User Persona Development',
        icon: '👤',
        description: 'Tạo user personas dựa trên data',
        category: 'product',
        fields: [
            { id: 'product', type: 'text', label: 'Product/Service', placeholder: 'Tên sản phẩm/dịch vụ', required: true, section: 'required' },
            { id: 'data', type: 'textarea', label: 'User Data', placeholder: 'Demographics, behaviors, interviews...', required: true, rows: 6, section: 'required' },
            { id: 'segments', type: 'text', label: 'User Segments', placeholder: 'Các segments đã biết', required: false, section: 'advanced' },
            { id: 'goals', type: 'text', label: 'Business Goals', placeholder: 'Mục tiêu kinh doanh', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn tạo user personas cho [product].

USER DATA:
[data]

SEGMENTS: [segments]
BUSINESS GOALS: [goals]

SUCCESS CRITERIA:
- 2-4 distinct personas
- Demographics, goals, pain points
- Jobs to be done
- Decision criteria`,
        outputExpected: ['Persona Profiles', 'User Journey Maps', 'Pain Points', 'Opportunities'],
    },
    {
        id: 'error_handling_ux',
        name: 'Error Handling UX',
        icon: '⚠️',
        description: 'Cải thiện cách handle errors',
        category: 'product',
        fields: [
            { id: 'errors', type: 'textarea', label: 'Current Error Messages', placeholder: 'Paste các error messages hiện tại', required: true, rows: 6, section: 'required' },
            { id: 'context', type: 'text', label: 'Error Context', placeholder: 'Form, checkout, login, etc.', required: true, section: 'required' },
            { id: 'audience', type: 'text', label: 'User Type', placeholder: 'Technical users hay end users?', required: false, section: 'advanced' },
            { id: 'tone', type: 'select', label: 'Brand Tone', options: ['Friendly', 'Professional', 'Technical', 'Playful'], default: 'Friendly', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn cải thiện error handling UX cho context [context].

CURRENT ERRORS:
[errors]

USER TYPE: [audience]
BRAND TONE: [tone]

SUCCESS CRITERIA:
- Error message clarity
- User guidance
- Recovery options
- Consistent tone`,
        outputExpected: ['Error Analysis', 'Rewritten Messages', 'UX Improvements', 'Best Practices'],
    },
    {
        id: 'onboarding_review',
        name: 'Onboarding Experience Review',
        icon: '🚀',
        description: 'Tối ưu first-time user experience',
        category: 'product',
        fields: [
            { id: 'product', type: 'text', label: 'Product', placeholder: 'Tên sản phẩm', required: true, section: 'required' },
            { id: 'flow', type: 'textarea', label: 'Current Onboarding Flow', placeholder: 'Mô tả các steps hiện tại', required: true, rows: 6, section: 'required' },
            { id: 'ttv', type: 'text', label: 'Time to Value', placeholder: 'Hiện tại bao lâu để user thấy value?', required: false, section: 'advanced' },
            { id: 'dropoff', type: 'text', label: 'Drop-off Rate', placeholder: '% users drop-off during onboarding', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn review onboarding experience cho [product].

CURRENT FLOW:
[flow]

TIME TO VALUE: [ttv]
DROP-OFF RATE: [dropoff]

SUCCESS CRITERIA:
- Identify friction points
- Reduce time to value
- Progressive disclosure
- Personalization opportunities`,
        outputExpected: ['Onboarding Assessment', 'Friction Points', 'Optimization Recommendations', 'Metrics to Track'],
    },

    // SECURITY & COMPLIANCE TEMPLATES (Phase 3)
    // Security Assessment Wizard - Multi-step
    {
        id: 'security_assessment_wizard',
        name: '🔐 Security Assessment Wizard',
        icon: '🔐',
        description: 'Multi-step wizard tạo Security Assessment Report qua 5 bước. Scope → Threats → Vulns → Risk → Review',
        category: 'security',
        fields: [],
        intentPattern: '',
        outputExpected: ['Security Assessment', 'Threat Model', 'Risk Matrix', 'Remediation Plan'],
    },
    {
        id: 'api_security',
        name: 'API Security Checklist',
        icon: '🔒',
        description: 'OWASP Top 10 API security audit',
        category: 'security',
        fields: [
            { id: 'endpoints', type: 'textarea', label: 'API Endpoints', placeholder: 'List các endpoints cần audit', required: true, rows: 4, section: 'required' },
            { id: 'authType', type: 'select', label: 'Authentication', options: ['JWT', 'OAuth', 'API Key', 'Session', 'None'], default: 'JWT', required: true, section: 'required' },
            { id: 'apiType', type: 'select', label: 'API Type', options: ['REST', 'GraphQL', 'gRPC', 'WebSocket'], default: 'REST', required: true, section: 'required' },
            { id: 'dataSensitivity', type: 'select', label: 'Data Sensitivity', options: ['Public', 'Internal', 'Confidential', 'PII', 'PCI'], default: 'Internal', required: true, section: 'required' },
        ],
        intentPattern: `INTENT:
Tôi muốn audit API security.

ENDPOINTS:
[endpoints]

AUTH TYPE: [authType]
API TYPE: [apiType]
DATA SENSITIVITY: [dataSensitivity]

SUCCESS CRITERIA:
- OWASP API Top 10 check
- Authentication/Authorization review
- Input validation
- Rate limiting assessment`,
        outputExpected: ['Security Score', 'Vulnerability Assessment', 'Critical Issues', 'Remediation Guide'],
    },
    {
        id: 'gdpr_compliance',
        name: 'GDPR Compliance Review',
        icon: '🇪🇺',
        description: 'EU data protection compliance check',
        category: 'security',
        fields: [
            { id: 'product', type: 'text', label: 'Website/App', placeholder: 'URL hoặc tên app', required: true, section: 'required' },
            { id: 'dataCollected', type: 'textarea', label: 'Data Collected', placeholder: 'Types of personal data', required: true, rows: 3, section: 'required' },
            { id: 'purpose', type: 'textarea', label: 'Processing Purpose', placeholder: 'Why data is collected', required: true, rows: 2, section: 'required' },
            { id: 'thirdParties', type: 'text', label: 'Third Parties', placeholder: 'Analytics, payment, ads...', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn review GDPR compliance cho [product].

DATA COLLECTED:
[dataCollected]

PROCESSING PURPOSE: [purpose]
THIRD PARTIES: [thirdParties]

SUCCESS CRITERIA:
- Consent mechanism check
- User rights implementation
- Privacy policy review
- Cookie compliance`,
        outputExpected: ['Compliance Score', 'Gap Analysis', 'Privacy Policy Review', 'Remediation Plan'],
    },
    {
        id: 'privacy_policy_audit',
        name: 'Privacy Policy Audit',
        icon: '📜',
        description: 'Privacy policy review và cải thiện',
        category: 'security',
        fields: [
            { id: 'policy', type: 'textarea', label: 'Policy URL/Text', placeholder: 'Link hoặc paste policy', required: true, rows: 6, section: 'required' },
            { id: 'businessType', type: 'select', label: 'Business Type', options: ['E-commerce', 'SaaS', 'Mobile App', 'Website', 'Marketplace'], default: 'SaaS', required: true, section: 'required' },
            { id: 'markets', type: 'text', label: 'Target Markets', placeholder: 'US, EU, APAC, Global...', required: true, section: 'required' },
            { id: 'dataTypes', type: 'text', label: 'Data Types', placeholder: 'Types of personal data collected', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn audit privacy policy.

POLICY:
[policy]

BUSINESS TYPE: [businessType]
TARGET MARKETS: [markets]
DATA TYPES: [dataTypes]

SUCCESS CRITERIA:
- Required elements check
- Readability assessment
- Regional compliance
- Third-party coverage`,
        outputExpected: ['Compliance Score', 'Missing Elements', 'Readability Score', 'Improvement Suggestions'],
    },
    {
        id: 'incident_response',
        name: 'Incident Response Plan',
        icon: '🚨',
        description: 'Security incident response planning',
        category: 'security',
        fields: [
            { id: 'companySize', type: 'select', label: 'Company Size', options: ['Startup', 'SMB', 'Enterprise'], default: 'SMB', required: true, section: 'required' },
            { id: 'industry', type: 'text', label: 'Industry', placeholder: 'Tech, Finance, Healthcare...', required: true, section: 'required' },
            { id: 'criticalSystems', type: 'textarea', label: 'Critical Systems', placeholder: 'Most important systems/data', required: true, rows: 3, section: 'required' },
            { id: 'currentPlan', type: 'textarea', label: 'Current Plan (nếu có)', placeholder: 'Existing IRP', required: false, rows: 3, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn xây dựng/review incident response plan.

COMPANY SIZE: [companySize]
INDUSTRY: [industry]
CRITICAL SYSTEMS: [criticalSystems]
CURRENT PLAN: [currentPlan]

SUCCESS CRITERIA:
- Team roles definition
- Severity levels
- Response procedures
- Communication templates`,
        outputExpected: ['IRP Assessment', 'Team Roles', 'Response Playbooks', 'Communication Templates'],
    },
    {
        id: 'data_handling',
        name: 'Data Handling Review',
        icon: '📊',
        description: 'Data lifecycle management review',
        category: 'security',
        fields: [
            { id: 'dataTypes', type: 'textarea', label: 'Data Types', placeholder: 'PII, PCI, PHI, Business data...', required: true, rows: 3, section: 'required' },
            { id: 'sources', type: 'text', label: 'Data Sources', placeholder: 'Where data comes from', required: true, section: 'required' },
            { id: 'storage', type: 'text', label: 'Storage Systems', placeholder: 'Databases, cloud, files...', required: true, section: 'required' },
            { id: 'regulations', type: 'text', label: 'Regulations', placeholder: 'GDPR, HIPAA, PCI-DSS...', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn review data handling practices.

DATA TYPES: [dataTypes]
DATA SOURCES: [sources]
STORAGE SYSTEMS: [storage]
REGULATIONS: [regulations]

SUCCESS CRITERIA:
- Classification scheme
- Retention policies
- Security controls
- Deletion procedures`,
        outputExpected: ['Data Inventory', 'Classification Matrix', 'Gap Analysis', 'Policy Recommendations'],
    },
    {
        id: 'tos_review',
        name: 'Terms of Service Review',
        icon: '📋',
        description: 'Terms of Service coverage và fairness',
        category: 'security',
        fields: [
            { id: 'tos', type: 'textarea', label: 'ToS URL/Text', placeholder: 'Link hoặc paste ToS', required: true, rows: 6, section: 'required' },
            { id: 'serviceType', type: 'select', label: 'Service Type', options: ['SaaS', 'Marketplace', 'Mobile App', 'Website', 'API'], default: 'SaaS', required: true, section: 'required' },
            { id: 'model', type: 'select', label: 'Business Model', options: ['Subscription', 'Free', 'Freemium', 'One-time', 'Usage-based'], default: 'Subscription', required: true, section: 'required' },
            { id: 'markets', type: 'text', label: 'Target Markets', placeholder: 'US, EU, Global...', required: true, section: 'required' },
        ],
        intentPattern: `INTENT:
Tôi muốn review Terms of Service.

TOS:
[tos]

SERVICE TYPE: [serviceType]
BUSINESS MODEL: [model]
TARGET MARKETS: [markets]

SUCCESS CRITERIA:
- Essential sections coverage
- User-friendliness
- Fairness assessment
- Regional compliance`,
        outputExpected: ['ToS Score', 'Coverage Analysis', 'Fairness Review', 'Improvement Suggestions'],
    },

    // ========================================
    // APP DEVELOPMENT TEMPLATES
    // ========================================

    // OPTION 0: APP BUILDER WIZARD (Multi-step wizard - RECOMMENDED)
    {
        id: 'app_builder_wizard',
        name: '🧙 App Builder Wizard',
        icon: '🧙',
        description: 'Multi-step wizard tạo spec qua 8 bước. Khuyên dùng cho app phức tạp!',
        category: 'development',
        fields: [], // No fields - handled by wizard component
        intentPattern: '', // Generated by wizard
        outputExpected: ['Complete App Spec', 'All Design Decisions', 'Build Ready Output'],
    },

    // OPTION 1: BUILD MY APP (Simple - for non-coders)
    {
        id: 'build_my_app',
        name: '🚀 Build My App',
        icon: '🚀',
        description: 'Mô tả ý tưởng app → AI tự quyết định mọi thứ và build cho bạn. Dành cho người không biết code.',
        category: 'development',
        fields: [
            { id: 'appIdea', type: 'textarea', label: 'Ý tưởng App', placeholder: 'VD: "Tôi muốn app quản lý công việc cá nhân, có thể thêm task, đặt deadline, nhắc nhở..."', required: true, rows: 4, section: 'required' },
            { id: 'appType', type: 'select', label: 'Loại App', options: ['Desktop App (cài trên máy)', 'CLI Tool (dòng lệnh)', 'Web App', 'Mobile App'], required: true, section: 'required' },
            { id: 'targetUser', type: 'text', label: 'Ai sẽ dùng?', placeholder: 'VD: Tôi dùng cá nhân, Team nhỏ 5 người, Khách hàng...', required: true, section: 'required' },
            { id: 'platform', type: 'select', label: 'Chạy trên', options: ['Windows', 'macOS', 'Linux', 'Cả 3 hệ điều hành', 'Web Browser'], required: true, section: 'required' },
            { id: 'preferences', type: 'textarea', label: 'Yêu cầu thêm (optional)', placeholder: 'VD: Giao diện tối, đơn giản, offline được...', required: false, rows: 2, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn AI build cho tôi một [appType].

Ý TƯỞNG:
[appIdea]

THÔNG TIN:
- Người dùng: [targetUser]
- Platform: [platform]
- Yêu cầu thêm: [preferences]

QUAN TRỌNG - YÊU CẦU CHO AI:
Đây là Vibe Coding - User chỉ mô tả ý tưởng, AI chịu trách nhiệm 100% về:
1. Phân tích requirements
2. Chọn tech stack phù hợp
3. Thiết kế architecture
4. Thiết kế database (nếu cần)
5. Build toàn bộ app
6. Test và packaging

User chỉ đánh giá kết quả cuối cùng.`,
        outputExpected: ['Complete Working App', 'Setup Instructions', 'User Guide'],
    },

    // OPTION 2: APP BUILDER COMPLETE (Advanced - comprehensive spec)
    {
        id: 'app_builder_complete',
        name: '📦 App Builder Complete',
        icon: '📦',
        description: 'Tạo spec hoàn chỉnh với đầy đủ thông tin kỹ thuật. Dành cho người hiểu quy trình CVF.',
        category: 'development',
        fields: [
            // Section 1: Requirements
            { id: 'appName', type: 'text', label: '1. Tên App', placeholder: 'VD: TaskFlow', required: true, section: 'required' },
            { id: 'appType', type: 'select', label: '2. Loại App', options: ['Desktop (Cross-platform)', 'CLI Tool', 'Desktop + CLI', 'Web SPA', 'Mobile'], required: true, section: 'required' },
            { id: 'problem', type: 'textarea', label: '3. Vấn đề cần giải quyết', placeholder: 'Mô tả vấn đề user đang gặp phải', required: true, rows: 3, section: 'required' },
            { id: 'targetUsers', type: 'text', label: '4. Target Users', placeholder: 'VD: Developer cá nhân, Team nhỏ', required: true, section: 'required' },
            { id: 'coreFeatures', type: 'textarea', label: '5. Core Features (3-5)', placeholder: '1. Feature A\n2. Feature B\n3. Feature C', required: true, rows: 4, section: 'required' },

            // Section 2: Technical Preferences
            { id: 'platforms', type: 'text', label: '6. Target Platforms', placeholder: 'Windows, macOS, Linux...', required: true, section: 'required' },
            { id: 'techPreference', type: 'text', label: '7. Tech Preference (optional)', placeholder: 'VD: Tauri, Electron, Python...', required: false, section: 'advanced' },
            { id: 'dataStorage', type: 'select', label: '8. Data Storage', options: ['None', 'Local Files (JSON/YAML)', 'Local Database (SQLite)', 'Cloud Database'], required: false, section: 'advanced' },
            { id: 'offlineRequired', type: 'select', label: '9. Offline Mode', options: ['Required', 'Nice to have', 'Not needed'], required: false, section: 'advanced' },

            // Section 3: App-specific
            { id: 'uiStyle', type: 'select', label: '10. UI Style', options: ['Modern Dark', 'Clean Light', 'Minimal', 'No UI (CLI only)'], required: false, section: 'advanced' },
            { id: 'specialFeatures', type: 'textarea', label: '11. Special Features', placeholder: 'VD: System tray, Keyboard shortcuts, Notifications...', required: false, rows: 2, section: 'advanced' },

            // Section 4: Constraints
            { id: 'outOfScope', type: 'textarea', label: '12. Out of Scope', placeholder: 'Những gì KHÔNG làm trong v1', required: false, rows: 2, section: 'advanced' },
            { id: 'constraints', type: 'text', label: '13. Constraints', placeholder: 'VD: Bundle < 50MB, No internet required', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tạo Complete App Specification cho [appName] - một [appType].

═══════════════════════════════════════════════════
SECTION 1: REQUIREMENTS
═══════════════════════════════════════════════════

**Problem Statement:**
[problem]

**Target Users:** [targetUsers]

**Core Features:**
[coreFeatures]

**Out of Scope:**
[outOfScope]

═══════════════════════════════════════════════════
SECTION 2: TECHNICAL REQUIREMENTS
═══════════════════════════════════════════════════

**Platforms:** [platforms]
**Tech Preference:** [techPreference]
**Data Storage:** [dataStorage]
**Offline Mode:** [offlineRequired]
**Constraints:** [constraints]

═══════════════════════════════════════════════════
SECTION 3: UI/UX REQUIREMENTS
═══════════════════════════════════════════════════

**UI Style:** [uiStyle]
**Special Features:** [specialFeatures]

═══════════════════════════════════════════════════
AI INSTRUCTIONS
═══════════════════════════════════════════════════

Dựa trên spec này, hãy thực hiện THEO THỨ TỰ:

**Phase A - Discovery:** Xác nhận bạn hiểu đúng requirements.

**Phase B - Design:** 
- Chọn tech stack (KHÔNG hỏi user chọn)
- Thiết kế architecture
- Thiết kế database schema (nếu cần)
- Thiết kế API/commands (nếu cần)

**Phase C - Build:**
- Build từng component
- Tạo full source code
- Tạo config files

**Phase D - Review:**
- Tóm tắt những gì đã build
- Hướng dẫn setup và chạy
- Hướng dẫn packaging/distribution`,
        outputExpected: [
            'Tech Stack Decision',
            'Architecture Diagram',
            'Database Schema (if needed)',
            'Complete Source Code',
            'Setup & Run Instructions',
            'Packaging Guide'
        ],
    },

    // ========================================
    // INDIVIDUAL SKILL TEMPLATES (8) - Hidden in folder
    // ========================================

    // Folder template that groups the 8 individual skills
    {
        id: 'individual_skills_folder',
        name: '📂 Skill Templates (8)',
        icon: '📂',
        description: '8 templates riêng lẻ cho từng khâu: Requirements, Tech Stack, Architecture, Database, API, Desktop/CLI, Deployment.',
        category: 'development',
        fields: [],
        intentPattern: '',
        outputExpected: [],
        isFolder: true, // This is a folder, not a template
    },

    {
        id: 'app_requirements_spec',
        name: 'App Requirements Spec',
        icon: '📋',
        description: 'Thu thập requirements cho app mới, định nghĩa scope và success criteria',
        category: 'development',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'VD: TaskFlow - Quản lý công việc', required: true, section: 'required' },
            { id: 'appType', type: 'select', label: 'App Type', options: ['Desktop', 'CLI Tool', 'Mobile', 'Web App', 'API Service'], required: true, section: 'required' },
            { id: 'problem', type: 'textarea', label: 'Problem Statement', placeholder: 'Vấn đề cần giải quyết là gì?', required: true, rows: 3, section: 'required' },
            { id: 'targetUsers', type: 'text', label: 'Target Users', placeholder: 'Ai sẽ dùng app này?', required: true, section: 'required' },
            { id: 'coreFeatures', type: 'textarea', label: 'Core Features (3-5)', placeholder: '1. Feature 1\n2. Feature 2\n3. Feature 3', required: true, rows: 4, section: 'required' },
            { id: 'outOfScope', type: 'textarea', label: 'Out of Scope', placeholder: 'Những gì KHÔNG làm trong phiên bản này', required: true, rows: 3, section: 'required' },
            { id: 'successCriteria', type: 'textarea', label: 'Success Criteria', placeholder: 'Khi nào app được coi là done?', required: true, rows: 2, section: 'required' },
            { id: 'platform', type: 'text', label: 'Platform', placeholder: 'Windows, macOS, Linux...', required: false, section: 'advanced' },
            { id: 'dataStorage', type: 'select', label: 'Data Storage', options: ['None', 'Local File', 'Local Database (SQLite)', 'Cloud'], required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tôi muốn tạo App Requirements Specification cho [appName].

APP INFO:
- Type: [appType]
- Target Users: [targetUsers]
- Platform: [platform]
- Data Storage: [dataStorage]

PROBLEM STATEMENT:
[problem]

CORE FEATURES:
[coreFeatures]

OUT OF SCOPE:
[outOfScope]

SUCCESS CRITERIA:
[successCriteria]

OUTPUT REQUIREMENTS:
- Problem statement rõ ràng
- Core features có priority
- Out of scope được định nghĩa
- Success criteria có thể measure được`,
        outputExpected: ['Requirements Document', 'Feature List with Priority', 'Scope Definition', 'Success Metrics'],
    },
    {
        id: 'tech_stack_selection',
        name: 'Tech Stack Selection',
        icon: '🔧',
        description: 'Chọn công nghệ phù hợp cho app dựa trên requirements',
        category: 'development',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appType', type: 'select', label: 'App Type', options: ['Desktop (Cross-platform)', 'CLI Tool', 'Mobile (Cross-platform)', 'Web SPA', 'API Backend'], required: true, section: 'required' },
            { id: 'performancePriority', type: 'select', label: 'Performance Priority', options: ['Low', 'Medium', 'High', 'Critical'], required: true, section: 'required' },
            { id: 'devSpeed', type: 'select', label: 'Development Speed Priority', options: ['Low', 'Medium', 'High'], required: true, section: 'required' },
            { id: 'platforms', type: 'text', label: 'Target Platforms', placeholder: 'Windows, macOS, Linux...', required: true, section: 'required' },
            { id: 'dataNeeds', type: 'select', label: 'Data Storage Needs', options: ['None', 'Local Only', 'Cloud Only', 'Both'], required: true, section: 'required' },
            { id: 'offlineRequired', type: 'select', label: 'Offline Required?', options: ['Yes', 'No', 'Partial'], required: true, section: 'required' },
            { id: 'teamExp', type: 'text', label: 'Team Experience', placeholder: 'VD: Python, JavaScript', required: false, section: 'advanced' },
            { id: 'langPreference', type: 'text', label: 'Language Preference', placeholder: 'Ngôn ngữ ưu tiên (nếu có)', required: false, section: 'advanced' },
            { id: 'bundleSize', type: 'text', label: 'Bundle Size Constraint', placeholder: 'VD: < 50MB', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
So sánh và recommend tech stack cho [appType].

REQUIREMENTS:
- Performance Priority: [performancePriority]
- Development Speed: [devSpeed]
- Target Platforms: [platforms]
- Data Storage: [dataNeeds]
- Offline Required: [offlineRequired]
- Bundle Size: [bundleSize]

TEAM CONTEXT:
- Experience: [teamExp]
- Language Preference: [langPreference]

OUTPUT REQUIREMENTS:
- Compare at least 2 options per layer
- Clear reasoning for each choice
- Trade-offs acknowledged
- Final stack consistent with requirements`,
        outputExpected: ['Options Comparison Tables', 'Recommended Stack', 'Trade-offs Analysis', 'Setup Commands'],
    },
    {
        id: 'architecture_design',
        name: 'Architecture Design',
        icon: '🏗️',
        description: 'Thiết kế kiến trúc hệ thống với component diagram',
        category: 'development',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required' },
            { id: 'techStack', type: 'text', label: 'Tech Stack', placeholder: 'VD: Tauri + Vue 3 + SQLite', required: true, section: 'required' },
            { id: 'coreFeatures', type: 'textarea', label: 'Core Features', placeholder: 'Các tính năng chính', required: true, rows: 3, section: 'required' },
            { id: 'appType', type: 'select', label: 'Architecture Type', options: ['Desktop App', 'CLI Tool', 'Web SPA', 'API Backend', 'Full-stack'], required: true, section: 'required' },
            { id: 'dataFlow', type: 'textarea', label: 'Data Flow', placeholder: 'VD: User → UI → Backend → DB → UI', required: true, rows: 2, section: 'required' },
            { id: 'integrations', type: 'text', label: 'External Integrations', placeholder: 'VD: REST API, File system (hoặc None)', required: false, section: 'advanced' },
            { id: 'stateComplexity', type: 'select', label: 'State Complexity', options: ['Simple', 'Medium', 'Complex'], required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Thiết kế architecture cho [appName].

TECH STACK: [techStack]
APP TYPE: [appType]

CORE FEATURES:
[coreFeatures]

DATA FLOW:
[dataFlow]

EXTERNAL INTEGRATIONS: [integrations]
STATE COMPLEXITY: [stateComplexity]

OUTPUT REQUIREMENTS:
- System diagram (ASCII art)
- Component breakdown với responsibilities
- Directory structure
- Data flow documentation
- Key design decisions`,
        outputExpected: ['System Diagram', 'Component Breakdown', 'Directory Structure', 'Data Flow', 'Design Decisions'],
    },
    {
        id: 'database_schema',
        name: 'Database Schema Design',
        icon: '🗄️',
        description: 'Thiết kế database schema với ERD và SQL',
        category: 'development',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required' },
            { id: 'dbType', type: 'select', label: 'Database Type', options: ['SQLite', 'PostgreSQL', 'MySQL', 'MongoDB'], required: true, section: 'required' },
            { id: 'entities', type: 'textarea', label: 'Main Entities', placeholder: 'VD: User, Task, Category, Tag', required: true, rows: 2, section: 'required' },
            { id: 'relationships', type: 'textarea', label: 'Relationships', placeholder: 'VD: User has many Tasks, Task belongs to Category', required: true, rows: 3, section: 'required' },
            { id: 'keyFields', type: 'textarea', label: 'Key Fields per Entity', placeholder: 'VD: Task: title, description, due_date, status', required: true, rows: 3, section: 'required' },
            { id: 'queryNeeds', type: 'textarea', label: 'Common Queries', placeholder: 'VD: Search by title, filter by status', required: false, rows: 2, section: 'advanced' },
            { id: 'audit', type: 'select', label: 'Audit Requirements', options: ['None', 'Created/Updated timestamps', 'Full audit trail'], required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Thiết kế database schema cho [appName].

DATABASE: [dbType]

ENTITIES:
[entities]

RELATIONSHIPS:
[relationships]

KEY FIELDS:
[keyFields]

COMMON QUERIES:
[queryNeeds]

AUDIT: [audit]

OUTPUT REQUIREMENTS:
- ERD diagram (ASCII art)
- Table definitions với data types
- SQL CREATE statements
- Index recommendations
- Sample queries`,
        outputExpected: ['ERD Diagram', 'Table Definitions', 'SQL Schema', 'Indexes', 'Sample Queries'],
    },
    {
        id: 'api_design',
        name: 'API Design Spec',
        icon: '🔌',
        description: 'Thiết kế REST API với endpoints và request/response format',
        category: 'development',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App/Service Name', placeholder: 'Tên API', required: true, section: 'required' },
            { id: 'apiStyle', type: 'select', label: 'API Style', options: ['REST', 'GraphQL', 'IPC (Desktop)'], required: true, section: 'required' },
            { id: 'resources', type: 'textarea', label: 'Resources/Entities', placeholder: 'VD: User, Task, Category', required: true, rows: 2, section: 'required' },
            { id: 'operations', type: 'textarea', label: 'Operations per Resource', placeholder: 'VD: Task: CRUD + complete, archive', required: true, rows: 3, section: 'required' },
            { id: 'auth', type: 'select', label: 'Authentication', options: ['None', 'JWT Bearer', 'API Key', 'OAuth2'], required: true, section: 'required' },
            { id: 'pagination', type: 'select', label: 'Pagination', options: ['Not needed', 'Offset/Limit', 'Cursor-based'], required: false, section: 'advanced' },
            { id: 'responseFormat', type: 'select', label: 'Response Format', options: ['JSON', 'XML', 'Both'], default: 'JSON', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Thiết kế API specification cho [appName].

API STYLE: [apiStyle]
AUTH: [auth]
RESPONSE FORMAT: [responseFormat]
PAGINATION: [pagination]

RESOURCES:
[resources]

OPERATIONS:
[operations]

OUTPUT REQUIREMENTS:
- All endpoints documented
- Request/Response format with examples
- Error codes and messages
- Authentication details
- Pagination for list endpoints`,
        outputExpected: ['API Overview', 'Endpoint Documentation', 'Request/Response Examples', 'Error Codes', 'Auth Details'],
    },
    {
        id: 'desktop_app_spec',
        name: 'Desktop App Spec',
        icon: '🖥️',
        description: 'Spec cho desktop app: windows, menus, shortcuts, tray',
        category: 'development',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required' },
            { id: 'framework', type: 'select', label: 'Framework', options: ['Tauri', 'Electron', 'PyQt/PySide', 'Wails', 'Native'], required: true, section: 'required' },
            { id: 'platforms', type: 'text', label: 'Target Platforms', placeholder: 'Windows, macOS, Linux', required: true, section: 'required' },
            { id: 'windowType', type: 'select', label: 'Window Type', options: ['Single Window', 'Multi-Window', 'Frameless'], required: true, section: 'required' },
            { id: 'defaultSize', type: 'text', label: 'Default Size', placeholder: 'VD: 1024x768', required: true, section: 'required' },
            { id: 'menuBar', type: 'textarea', label: 'Menu Bar', placeholder: 'VD: File (New, Save, Exit), Edit, Help', required: true, rows: 2, section: 'required' },
            { id: 'tray', type: 'select', label: 'System Tray', options: ['No', 'Yes - Basic', 'Yes - With Quick Actions'], required: false, section: 'advanced' },
            { id: 'shortcuts', type: 'textarea', label: 'Keyboard Shortcuts', placeholder: 'VD: Ctrl+N new, Ctrl+S save', required: false, rows: 2, section: 'advanced' },
            { id: 'nativeFeatures', type: 'text', label: 'Native Features', placeholder: 'VD: Notifications, File dialogs', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tạo Desktop App Specification cho [appName].

FRAMEWORK: [framework]
PLATFORMS: [platforms]
WINDOW: [windowType], [defaultSize]

MENU BAR:
[menuBar]

SYSTEM TRAY: [tray]

KEYBOARD SHORTCUTS:
[shortcuts]

NATIVE FEATURES: [nativeFeatures]

OUTPUT REQUIREMENTS:
- Window configuration complete
- Menu structure với shortcuts
- System tray behavior
- Platform-specific notes
- Lifecycle behavior (startup, close)`,
        outputExpected: ['Window Config', 'Menu Structure', 'Shortcuts Table', 'Tray Behavior', 'Platform Notes'],
    },
    {
        id: 'cli_tool_spec',
        name: 'CLI Tool Spec',
        icon: '⌨️',
        description: 'Spec cho command-line tool: commands, arguments, options',
        category: 'development',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'toolName', type: 'text', label: 'Tool Name', placeholder: 'VD: taskflow hoặc tf', required: true, section: 'required' },
            { id: 'purpose', type: 'textarea', label: 'Purpose', placeholder: 'Tool này làm gì?', required: true, rows: 2, section: 'required' },
            { id: 'commands', type: 'textarea', label: 'Commands', placeholder: 'VD: add, list, done, delete, search, config', required: true, rows: 2, section: 'required' },
            { id: 'targetUsers', type: 'text', label: 'Target Users', placeholder: 'Ai sẽ dùng?', required: true, section: 'required' },
            { id: 'language', type: 'select', label: 'Language', options: ['Python (Click)', 'Rust (Clap)', 'Go (Cobra)', 'Node.js (Commander)', 'Other'], required: true, section: 'required' },
            { id: 'configLocation', type: 'text', label: 'Config Location', placeholder: 'VD: ~/.toolname/config.yaml', required: false, section: 'advanced' },
            { id: 'dataStorage', type: 'text', label: 'Data Storage', placeholder: 'VD: ~/.toolname/data.json', required: false, section: 'advanced' },
            { id: 'outputFormats', type: 'text', label: 'Output Formats', placeholder: 'VD: text, json, table', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tạo CLI Tool Specification cho [toolName].

PURPOSE:
[purpose]

TARGET USERS: [targetUsers]
LANGUAGE: [language]

COMMANDS:
[commands]

CONFIG: [configLocation]
DATA: [dataStorage]
OUTPUT FORMATS: [outputFormats]

OUTPUT REQUIREMENTS:
- All commands documented
- Arguments và options clear
- Exit codes defined
- Config file format
- Examples cho mỗi command`,
        outputExpected: ['Command Documentation', 'Arguments/Options', 'Exit Codes', 'Config Format', 'Usage Examples'],
    },
    {
        id: 'local_deployment',
        name: 'Local Deployment Spec',
        icon: '📦',
        description: 'Packaging và distribution spec cho local apps',
        category: 'development',
        parentFolder: 'individual_skills_folder',
        fields: [
            { id: 'appName', type: 'text', label: 'App Name', placeholder: 'Tên app', required: true, section: 'required' },
            { id: 'appType', type: 'select', label: 'App Type', options: ['Desktop (Tauri)', 'Desktop (Electron)', 'CLI Tool', 'Service'], required: true, section: 'required' },
            { id: 'platforms', type: 'text', label: 'Target Platforms', placeholder: 'Windows, macOS, Linux', required: true, section: 'required' },
            { id: 'distribution', type: 'select', label: 'Distribution Method', options: ['GitHub Releases', 'Website Download', 'Package Manager (npm/pip)', 'Internal Only'], required: true, section: 'required' },
            { id: 'autoUpdate', type: 'select', label: 'Auto-Update', options: ['No', 'Yes - Prompt User', 'Yes - Silent'], required: false, section: 'advanced' },
            { id: 'signing', type: 'select', label: 'Code Signing', options: ['No', 'Windows Only', 'macOS Only', 'Both'], required: false, section: 'advanced' },
            { id: 'dependencies', type: 'text', label: 'Runtime Dependencies', placeholder: 'VD: None, .NET, Python', required: false, section: 'advanced' },
        ],
        intentPattern: `INTENT:
Tạo Deployment Specification cho [appName].

APP TYPE: [appType]
PLATFORMS: [platforms]
DISTRIBUTION: [distribution]

AUTO-UPDATE: [autoUpdate]
CODE SIGNING: [signing]
DEPENDENCIES: [dependencies]

OUTPUT REQUIREMENTS:
- Build artifacts for all platforms
- Build commands
- Installer configuration
- Distribution process
- Code signing steps (if applicable)
- Testing checklist`,
        outputExpected: ['Build Artifacts', 'Build Commands', 'Installer Config', 'CI/CD Config', 'Distribution Process'],
    },
];

export function getTemplateById(id: string): Template | undefined {
    return templates.find(t => t.id === id);
}

export function getTemplatesByCategory(category: string): Template[] {
    return templates.filter(t => t.category === category);
}

export function generateIntent(template: Template, values: Record<string, string>): string {
    let intent = template.intentPattern;

    Object.entries(values).forEach(([key, value]) => {
        intent = intent.replace(new RegExp(`\\[${key}\\]`, 'g'), value || 'N/A');
    });

    return intent;
}

/**
 * Generate a complete CVF specification document
 * Ready for copy/paste into any AI (ChatGPT, Claude, Gemini, etc.)
 */
export function generateCompleteSpec(
    template: Template,
    values: Record<string, string>,
    userIntent?: string
): string {
    const date = new Date().toISOString().split('T')[0];
    const intent = generateIntent(template, values);

    // Build user input section
    const userInputLines = Object.entries(values)
        .filter(([, value]) => value && value.trim())
        .map(([key, value]) => {
            const field = template.fields.find(f => f.id === key);
            const label = field?.label || key;
            return `- **${label}:** ${value}`;
        })
        .join('\n');

    // Build expected output section
    const expectedOutput = template.outputExpected
        ?.map(item => `- ${item}`)
        .join('\n') || '- Comprehensive analysis\n- Actionable recommendations';
    const outputTemplate = template.outputTemplate || (template.outputExpected?.length
        ? template.outputExpected.map(section => `## ${section}\n- ...`).join('\n\n')
        : '');

    const requiredFields = template.fields.filter(field => field.required);
    const missingRequired = requiredFields.filter(field => {
        const value = values[field.id];
        return !value || !value.trim() || value.trim().toLowerCase() === 'n/a';
    });
    const inputCoverage = requiredFields.length
        ? [
            '| Field | Provided |',
            '| --- | --- |',
            ...requiredFields.map(field => {
                const value = values[field.id];
                const provided = value && value.trim() && value.trim().toLowerCase() !== 'n/a';
                return `| ${field.label} | ${provided ? '✅' : '❌'} |`;
            })
        ].join('\n')
        : '(No required inputs)';

    const executionConstraints = `## ⛔ Execution Constraints
- Do not invent missing inputs. If required inputs are missing, stop and ask for clarification.
- Follow the Output Template headings exactly (no reordering).
- Stay within the scope defined by the Task section.
- If data is unavailable, state it explicitly as "Unknown".`;

    const validationHooks = `## ✅ Validation Hooks
- Check required inputs against the Input Coverage table.
- Ensure every Expected Output section is present.
- Include a Success Criteria Check.
- If any item is missing, mark the result as "Not Ready" and list what's missing.`;

    const spec = `---
# CVF Task Specification
**Generated:** ${date}
**Template:** ${template.name}
**Category:** ${template.category}
---

## 📋 Context

**Template:** ${template.icon} ${template.name}

${template.description}

---

## 📝 User Input

${userInputLines || '(No input provided)'}

---

## ✅ Input Coverage

${inputCoverage}
${missingRequired.length ? `\n\n**Missing Required Inputs:** ${missingRequired.map(field => field.label).join(', ')}` : ''}

---

## 🎯 Task

${intent}

---

## 📤 Expected Output Format

${expectedOutput}

${outputTemplate ? `\n---\n\n## 📐 Output Template\n\n\`\`\`markdown\n${outputTemplate}\n\`\`\`\n` : ''}

---

${executionConstraints}

---

${validationHooks}

---

## 💡 Instructions for AI

Please analyze the information provided above and generate a comprehensive response that:
1. Addresses all the success criteria listed in the Task section
2. Follows the Expected Output Format structure
3. Provides actionable insights and recommendations
4. Uses clear, professional language
5. Includes specific examples where applicable

---

> **CVF v1.5 UX Platform**
> Copy this entire specification and paste into your preferred AI assistant (ChatGPT, Claude, Gemini, etc.)
`;

    return spec;
}

