param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectPath,

    [switch]$Force
)

$ErrorActionPreference = "Stop"
$projectResolved = [System.IO.Path]::GetFullPath($ProjectPath)
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$cvfCorePath = Split-Path -Parent $scriptDir

Write-Host ""
Write-Host "CVF Hook Installer (opt-in)" -ForegroundColor Cyan
Write-Host "============================" -ForegroundColor Cyan
Write-Host "Project: $projectResolved"
Write-Host "CVF Core: $cvfCorePath"
Write-Host ""

if (-not (Test-Path $projectResolved -PathType Container)) {
    Write-Host "[FAIL] Project path not found: $projectResolved" -ForegroundColor Red
    exit 1
}

$gitDir = Join-Path $projectResolved ".git"
if (-not (Test-Path $gitDir -PathType Container)) {
    Write-Host "[WARN] No .git directory found - hooks require a git repository." -ForegroundColor Yellow
    Write-Host "       Initialize git first: git init" -ForegroundColor Yellow
    exit 0
}

$hooksDir = Join-Path $gitDir "hooks"
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir | Out-Null
}

$doctorScript = Join-Path $cvfCorePath "scripts\check_cvf_workspace_agent_enforcement.ps1"

# pre-commit hook
$preCommitPath = Join-Path $hooksDir "pre-commit"
if ((Test-Path $preCommitPath) -and -not $Force) {
    Write-Host "[WARN] pre-commit hook already exists. Use -Force to overwrite." -ForegroundColor Yellow
}
else {
    $preCommitContent = @"
#!/bin/sh
# CVF Workspace Enforcement pre-commit hook
# Auto-generated by CVF scripts/install_cvf_hooks.ps1
# Remove this file to disable the hook.

PROJECT_PATH="`$(pwd)"
CVF_DOCTOR="$($doctorScript -replace '\\', '/')"

if [ -f "`$CVF_DOCTOR" ]; then
    powershell.exe -ExecutionPolicy Bypass -File "`$CVF_DOCTOR" -ProjectPath "`$PROJECT_PATH"
    if [ `$? -ne 0 ]; then
        echo "[CVF] Pre-commit hook: enforcement doctor failed. Fix missing artifacts before committing."
        exit 1
    fi
fi
exit 0
"@
    Set-Content -Path $preCommitPath -Value $preCommitContent -Encoding ascii -NoNewline
    Write-Host "[OK]   Installed pre-commit hook: $preCommitPath" -ForegroundColor Green
}

# CI workflow sample
$ciSampleSrc = Join-Path $cvfCorePath "governance\toolkit\05_OPERATION\CVF_CI_ENFORCEMENT_SAMPLE.yml"
$githubWorkflowsDir = Join-Path $projectResolved ".github\workflows"
$ciDest = Join-Path $githubWorkflowsDir "cvf-enforcement.yml"

if (Test-Path $ciSampleSrc) {
    if ((Test-Path $ciDest) -and -not $Force) {
        Write-Host "[WARN] CI workflow already exists: $ciDest" -ForegroundColor Yellow
        Write-Host "       Use -Force to overwrite, or copy manually from:" -ForegroundColor Yellow
        Write-Host "       $ciSampleSrc" -ForegroundColor Yellow
    }
    else {
        if (-not (Test-Path $githubWorkflowsDir)) {
            New-Item -ItemType Directory -Path $githubWorkflowsDir -Force | Out-Null
        }
        Copy-Item -Path $ciSampleSrc -Destination $ciDest -Force
        Write-Host "[OK]   Installed CI workflow: $ciDest" -ForegroundColor Green
    }
}
else {
    Write-Host "[WARN] CI sample not found: $ciSampleSrc" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "[OK]   CVF hook installation complete." -ForegroundColor Green
Write-Host "       The pre-commit hook runs the workspace doctor before each commit." -ForegroundColor Cyan
Write-Host "       The CI workflow runs the doctor on every push/PR." -ForegroundColor Cyan
Write-Host ""
Write-Host "To uninstall: delete $preCommitPath" -ForegroundColor DarkGray
