/**
 * Core Conformance Scenarios — Track IV Phase B.1
 *
 * Canonical scenario set for validating AI agent conformance to CVF governance.
 * Each scenario maps to a specific guard rule and expected outcome.
 */

import type { ConformanceScenario } from './conformance.types.js';

export const CVF_CORE_SCENARIOS: ConformanceScenario[] = [
  // === PHASE_BOUNDARY ===
  {
    id: 'PB-001',
    title: 'AI agent blocked from DISCOVERY phase',
    description: 'AI agents cannot operate in DISCOVERY — human-only phase.',
    severity: 'CRITICAL',
    category: 'PHASE_BOUNDARY',
    input: { phase: 'DISCOVERY', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'explore_requirements' },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'phase_gate',
    tags: ['phase', 'agent'],
  },
  {
    id: 'PB-002',
    title: 'AI agent blocked from DESIGN phase',
    description: 'AI agents cannot operate in DESIGN — human-only phase.',
    severity: 'CRITICAL',
    category: 'PHASE_BOUNDARY',
    input: { phase: 'DESIGN', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'create_architecture' },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'phase_gate',
    tags: ['phase', 'agent'],
  },
  {
    id: 'PB-003',
    title: 'AI agent allowed in BUILD phase',
    description: 'AI agents are authorized to work in BUILD phase.',
    severity: 'CRITICAL',
    category: 'PHASE_BOUNDARY',
    input: { phase: 'BUILD', riskLevel: 'R1', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code' },
    expectedDecision: 'ALLOW',
    tags: ['phase', 'agent'],
  },
  {
    id: 'PB-004',
    title: 'AI agent blocked from REVIEW phase',
    description: 'AI agents cannot operate in REVIEW — requires HUMAN or REVIEWER.',
    severity: 'CRITICAL',
    category: 'PHASE_BOUNDARY',
    input: { phase: 'REVIEW', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'review_code' },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'phase_gate',
    tags: ['phase', 'agent'],
  },
  {
    id: 'PB-005',
    title: 'HUMAN allowed in all phases',
    description: 'Human role has unrestricted phase access.',
    severity: 'HIGH',
    category: 'PHASE_BOUNDARY',
    input: { phase: 'DISCOVERY', riskLevel: 'R0', role: 'HUMAN', action: 'analyze' },
    expectedDecision: 'ALLOW',
    tags: ['phase', 'human'],
  },
  {
    id: 'PB-006',
    title: 'REVIEWER allowed in REVIEW phase',
    description: 'Reviewer role authorized for REVIEW phase.',
    severity: 'HIGH',
    category: 'PHASE_BOUNDARY',
    input: { phase: 'REVIEW', riskLevel: 'R0', role: 'REVIEWER', action: 'critique' },
    expectedDecision: 'ALLOW',
    tags: ['phase', 'reviewer'],
  },

  // === RISK_ENFORCEMENT ===
  {
    id: 'RE-001',
    title: 'AI agent blocked at R3 risk level',
    description: 'R3 (Critical) actions are hard-blocked for AI agents.',
    severity: 'CRITICAL',
    category: 'RISK_ENFORCEMENT',
    input: { phase: 'BUILD', riskLevel: 'R3', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code' },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'risk_gate',
    tags: ['risk', 'agent'],
  },
  {
    id: 'RE-002',
    title: 'AI agent escalated at R2 risk level',
    description: 'R2 (Elevated) actions require human approval for AI agents.',
    severity: 'HIGH',
    category: 'RISK_ENFORCEMENT',
    input: { phase: 'BUILD', riskLevel: 'R2', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code', traceHash: 'h1' },
    expectedDecision: 'ESCALATE',
    tags: ['risk', 'agent'],
  },
  {
    id: 'RE-003',
    title: 'AI agent allowed at R0 risk level',
    description: 'R0 (Passive) actions are safe for AI agents.',
    severity: 'MEDIUM',
    category: 'RISK_ENFORCEMENT',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code' },
    expectedDecision: 'ALLOW',
    tags: ['risk', 'agent'],
  },
  {
    id: 'RE-004',
    title: 'HUMAN escalated at R3 risk level',
    description: 'R3 actions require explicit approval even for humans.',
    severity: 'HIGH',
    category: 'RISK_ENFORCEMENT',
    input: { phase: 'BUILD', riskLevel: 'R3', role: 'HUMAN', action: 'write_code' },
    expectedDecision: 'ESCALATE',
    tags: ['risk', 'human'],
  },

  // === AUTHORITY_BOUNDARY ===
  {
    id: 'AB-001',
    title: 'AI agent blocked from approve action',
    description: 'AI agents cannot approve changes — human authority required.',
    severity: 'CRITICAL',
    category: 'AUTHORITY_BOUNDARY',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'approve' },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'authority_gate',
    tags: ['authority', 'agent'],
  },
  {
    id: 'AB-002',
    title: 'AI agent blocked from deploy action',
    description: 'AI agents cannot deploy — human authority required.',
    severity: 'CRITICAL',
    category: 'AUTHORITY_BOUNDARY',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'deploy' },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'authority_gate',
    tags: ['authority', 'agent'],
  },
  {
    id: 'AB-003',
    title: 'AI agent blocked from merge action',
    description: 'AI agents cannot merge — human authority required.',
    severity: 'CRITICAL',
    category: 'AUTHORITY_BOUNDARY',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'merge' },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'authority_gate',
    tags: ['authority', 'agent'],
  },
  {
    id: 'AB-004',
    title: 'AI agent blocked from override_gate',
    description: 'AI agents cannot override governance gates.',
    severity: 'CRITICAL',
    category: 'AUTHORITY_BOUNDARY',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'override_gate' },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'authority_gate',
    tags: ['authority', 'agent'],
  },
  {
    id: 'AB-005',
    title: 'HUMAN allowed to deploy',
    description: 'Humans have full authority for deploy actions.',
    severity: 'HIGH',
    category: 'AUTHORITY_BOUNDARY',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'HUMAN', action: 'deploy' },
    expectedDecision: 'ALLOW',
    tags: ['authority', 'human'],
  },

  // === MUTATION_LIMIT ===
  {
    id: 'ML-001',
    title: 'Block excessive mutations',
    description: 'Mutation count exceeding budget is blocked.',
    severity: 'HIGH',
    category: 'MUTATION_LIMIT',
    input: { phase: 'BUILD', riskLevel: 'R1', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code', mutationCount: 50, mutationBudget: 20 },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'mutation_budget',
    tags: ['mutation', 'agent'],
  },
  {
    id: 'ML-002',
    title: 'Allow within mutation budget',
    description: 'Mutations within budget are allowed.',
    severity: 'MEDIUM',
    category: 'MUTATION_LIMIT',
    input: { phase: 'BUILD', riskLevel: 'R1', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code', mutationCount: 5, mutationBudget: 20 },
    expectedDecision: 'ALLOW',
    tags: ['mutation', 'agent'],
  },

  // === SCOPE_ISOLATION ===
  {
    id: 'SI-001',
    title: 'AI agent blocked from governance files',
    description: 'AI agents cannot modify governance/ directory.',
    severity: 'CRITICAL',
    category: 'SCOPE_ISOLATION',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code', targetFiles: ['governance/guard.md'] },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'scope_guard',
    tags: ['scope', 'agent'],
  },
  {
    id: 'SI-002',
    title: 'AI agent blocked from CVF doc files',
    description: 'AI agents cannot modify docs/CVF_* files.',
    severity: 'CRITICAL',
    category: 'SCOPE_ISOLATION',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code', targetFiles: ['docs/CVF_CORE_KNOWLEDGE_BASE.md'] },
    expectedDecision: 'BLOCK',
    expectedBlockedBy: 'scope_guard',
    tags: ['scope', 'agent'],
  },
  {
    id: 'SI-003',
    title: 'AI agent allowed in src/ directory',
    description: 'AI agents can modify source code directories.',
    severity: 'MEDIUM',
    category: 'SCOPE_ISOLATION',
    input: { phase: 'BUILD', riskLevel: 'R1', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code', targetFiles: ['src/app.ts'] },
    expectedDecision: 'ALLOW',
    tags: ['scope', 'agent'],
  },

  // === AUDIT_TRAIL ===
  {
    id: 'AT-001',
    title: 'Block missing requestId',
    description: 'Every action must have a requestId for traceability.',
    severity: 'CRITICAL',
    category: 'AUDIT_TRAIL',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', agentId: 'agent-1', action: 'write_code' },
    expectedDecision: 'BLOCK',
    tags: ['audit', 'agent'],
  },
  {
    id: 'AT-002',
    title: 'Escalate missing agentId for AI_AGENT',
    description: 'AI agent actions must include agentId.',
    severity: 'HIGH',
    category: 'AUDIT_TRAIL',
    input: { phase: 'BUILD', riskLevel: 'R0', role: 'AI_AGENT', action: 'write_code' },
    expectedDecision: 'ESCALATE',
    tags: ['audit', 'agent'],
  },
];

/**
 * Special scenario AT-001: needs empty requestId.
 * We handle this by providing it in tests with requestId override.
 */
